//! A participant's own declared rows, read from the root rather than compiled in.
//!
//! B70/CP2 step 2. Every fabric participant needs one fact about itself before
//! it can attach a ring: the KEEP_LAST depth the fabric formatted that ring at.
//! It read that from `FABRIC_HISTORY_DEPTHS`, a table `components/bins/build.rs`
//! generated by parsing the manifest — so the component could not be built
//! outside this crate against this generation.
//!
//! `CAPABILITY GRAPH READ` answers it instead. A non-holder reads its own rows
//! and nothing else, which is the same scoping `resolve_binding` applies: the
//! component learns what the generation declares *about it*, which is exactly
//! what the generated table told it, and learns nothing about anyone else.
//!
//! # Why the ring header cannot answer this
//!
//! The mapped ring's header carries `slot_count`, and it is tempting to read it
//! there. It must not be: the ring crosses as a *writable* loan, so the header
//! is in memory the peer can write, and `Ring::attach` takes `expected_slots`
//! from the caller's own record precisely so a hostile peer cannot choose the
//! value the reader trusts. The header carries the number and the caller
//! supplies it independently; `valid_ring_header` compares them, and that
//! agreement is the check. This module supplies the caller's half.

use boot_contracts::fabric_graph::{PARTICIPANT_ENTRY_BYTES, TransportQos};

/// Rows one read may return. A component's own share is small — the largest any
/// seL4 manifest declares for one participant is two — so a single call is
/// always enough and the loop below is a bound, not a pager.
const MAX_OWN_ROWS: usize = 8;

/// Byte offsets into a participant record. Named from the contract's own
/// decoder (`FabricGraph::participant`) rather than re-derived, and used only to
/// read fields out of a record this component received whole. They must stay in
/// step with that decoder: the root stages raw `participant_bytes`, so these
/// offsets are this side's half of one contract layout.
const COMPONENT_IDENTITY: core::ops::Range<usize> = 32..64;
const ROUTE_INDEX: core::ops::Range<usize> = 64..68;
const DIRECTION: core::ops::Range<usize> = 68..72;
const VISIBILITY: core::ops::Range<usize> = 72..76;
const DEADLINE_NS: core::ops::Range<usize> = 80..88;
const LIFESPAN_NS: core::ops::Range<usize> = 88..96;
const LEASE_NS: core::ops::Range<usize> = 96..104;
const HISTORY_DEPTH: core::ops::Range<usize> = 104..108;
const RETAINED_DEPTH: core::ops::Range<usize> = 108..112;
const RELIABILITY: usize = 112;
const DURABILITY: usize = 113;
const LIVELINESS: usize = 114;

/// The KEEP_LAST depth this component's row declares for `route_index`, or
/// `None` if the generation declares no such row.
///
/// `route_index` comes from `slime_rt::graph_route_index`, which resolves the
/// identity a participant folds from its own route name, interface identity,
/// and contract kind.
pub fn history_depth(route_index: u32) -> Option<usize> {
    let mut rows = [0u8; MAX_OWN_ROWS * PARTICIPANT_ENTRY_BYTES];
    let count = slime_rt::graph_read(0, &mut rows).ok()?;
    // See `rows`: the root's per-call bound and `MAX_OWN_ROWS` are derived
    // independently, so a reply naming more rows than were staged is drift to
    // refuse rather than an index to trust.
    if count > MAX_OWN_ROWS {
        return None;
    }
    for row in 0..count {
        let bytes = &rows[row * PARTICIPANT_ENTRY_BYTES..(row + 1) * PARTICIPANT_ENTRY_BYTES];
        let declared = u32::from_le_bytes(bytes[ROUTE_INDEX].try_into().ok()?);
        if declared == route_index {
            return Some(u32::from_le_bytes(bytes[HISTORY_DEPTH].try_into().ok()?) as usize);
        }
    }
    None
}

/// This component's declared KEEP_LAST depth for the route it names, floored at
/// the ring's own minimum exactly as the fabric floors it.
///
/// The whole path a participant needs: fold the route identity, ask the root
/// which index the graph gives it, then read this component's own row.
pub fn ring_slots(route_identity: &[u8; 32]) -> Option<usize> {
    let index = slime_rt::graph_route_index(route_identity).ok()?;
    let depth = history_depth(index as u32)?;
    Some(depth.max(slime_proto::fabric_ring::MIN_RING_SLOTS))
}

/// The KEEP_LAST depth declared for `component` on `route_index`.
///
/// For the graph's declared holder, which reads every row: the four
/// participants above ask about themselves and can use `history_depth`, but the
/// fabric provisions a ring *for* each participant and so must ask about
/// someone else. A non-holder calling this sees only its own rows, so it can
/// answer only about itself -- which is the scoping, not a limitation of this
/// function.
pub fn history_depth_of(component_identity: &[u8; 32], route_index: u32) -> Option<usize> {
    let mut rows = [0u8; MAX_OWN_ROWS * PARTICIPANT_ENTRY_BYTES];
    let mut cursor = 0usize;
    loop {
        let count = slime_rt::graph_read(cursor, &mut rows).ok()?;
        if count == 0 {
            return None;
        }
        if count > MAX_OWN_ROWS {
            return None;
        }
        for row in 0..count {
            let bytes = &rows[row * PARTICIPANT_ENTRY_BYTES..(row + 1) * PARTICIPANT_ENTRY_BYTES];
            if &bytes[COMPONENT_IDENTITY] != component_identity.as_slice() {
                continue;
            }
            let declared = u32::from_le_bytes(bytes[ROUTE_INDEX].try_into().ok()?);
            if declared == route_index {
                return Some(u32::from_le_bytes(bytes[HISTORY_DEPTH].try_into().ok()?) as usize);
            }
        }
        cursor += count;
        if count < MAX_OWN_ROWS {
            return None;
        }
    }
}

/// A whole-graph read that did not complete.
///
/// Distinct from an empty table, and named rather than `()` so a caller cannot
/// read it as "no rows": every negative assertion a broker makes about the
/// graph — that some component holds no declared edge — is unfounded on this
/// value, and treating it as an empty result would satisfy that assertion out
/// of a failed syscall.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct IncompleteRead;

/// Rows a whole-graph read may need to hold at once. The largest seL4 graph
/// declares 15 participants; the contract ceiling is 32.
pub const MAX_GRAPH_ROWS: usize = 32;

/// One participant row, decoded to the fields a broker asks about.
///
/// `history_depth` is kept as its own field because it predates the rest and
/// several callers read only it; it is the same number as `qos.history_depth`.
#[derive(Clone, Copy)]
pub struct Row {
    pub component_identity: [u8; 32],
    pub route_index: u32,
    pub direction: u32,
    pub visibility: u32,
    pub history_depth: usize,
    pub qos: TransportQos,
}

/// Every row this caller may read, in the order the resource stores them.
///
/// For the graph's declared holder that is the whole participant table; for
/// anyone else it is their own rows plus those of components they share a
/// declared edge with. The caller supplies the buffer because a `no_std`
/// component has no allocator, and `MAX_GRAPH_ROWS` bounds what one can hold.
///
/// `Ok(n)` is a complete read of `n` rows; a short count is the end of the
/// table, not an error. `Err` is a read that did not complete, and callers must
/// not treat it as an empty table: a broker asserting that some component holds
/// *no* declared edge would otherwise satisfy that assertion out of a failed
/// syscall rather than out of the graph. Truncation at `MAX_GRAPH_ROWS` is an
/// error for the same reason -- the rows past the bound went unread, so any
/// negative claim over them would be unfounded.
pub fn rows(out: &mut [Row; MAX_GRAPH_ROWS]) -> Result<usize, IncompleteRead> {
    let mut buffer = [0u8; MAX_OWN_ROWS * PARTICIPANT_ENTRY_BYTES];
    let mut cursor = 0usize;
    let mut written = 0usize;
    loop {
        let Ok(count) = slime_rt::graph_read(cursor, &mut buffer) else {
            return Err(IncompleteRead);
        };
        if count == 0 {
            return Ok(written);
        }
        // The reply cannot name more rows than the buffer it was staged into.
        // `MAX_OWN_ROWS` here and `GRAPH_ROWS_PER_CALL` in the root both work out
        // to eight, but they are derived independently -- one from this array, one
        // from the transfer window's staging bound. If they ever drift apart, this
        // is a short read to re-ask, not a licence to index past the buffer.
        if count > MAX_OWN_ROWS {
            return Err(IncompleteRead);
        }
        for row in 0..count {
            if written == out.len() {
                return Err(IncompleteRead);
            }
            let bytes = &buffer[row * PARTICIPANT_ENTRY_BYTES..(row + 1) * PARTICIPANT_ENTRY_BYTES];
            let Ok(component_identity) = <[u8; 32]>::try_from(&bytes[COMPONENT_IDENTITY]) else {
                return Err(IncompleteRead);
            };
            let Ok(route) = bytes[ROUTE_INDEX].try_into() else {
                return Err(IncompleteRead);
            };
            let Ok(direction) = bytes[DIRECTION].try_into() else {
                return Err(IncompleteRead);
            };
            let Ok(depth) = bytes[HISTORY_DEPTH].try_into() else {
                return Err(IncompleteRead);
            };
            let Ok(visibility) = bytes[VISIBILITY].try_into() else {
                return Err(IncompleteRead);
            };
            let Ok(deadline) = bytes[DEADLINE_NS].try_into() else {
                return Err(IncompleteRead);
            };
            let Ok(lifespan) = bytes[LIFESPAN_NS].try_into() else {
                return Err(IncompleteRead);
            };
            let Ok(lease) = bytes[LEASE_NS].try_into() else {
                return Err(IncompleteRead);
            };
            let Ok(retained) = bytes[RETAINED_DEPTH].try_into() else {
                return Err(IncompleteRead);
            };
            let (Some(reliability), Some(durability), Some(liveliness)) = (
                bytes.get(RELIABILITY).copied(),
                bytes.get(DURABILITY).copied(),
                bytes.get(LIVELINESS).copied(),
            ) else {
                return Err(IncompleteRead);
            };
            out[written] = Row {
                component_identity,
                route_index: u32::from_le_bytes(route),
                direction: u32::from_le_bytes(direction),
                visibility: u32::from_le_bytes(visibility),
                history_depth: u32::from_le_bytes(depth) as usize,
                qos: TransportQos {
                    deadline_ns: u64::from_le_bytes(deadline),
                    lifespan_ns: u64::from_le_bytes(lifespan),
                    lease_ns: u64::from_le_bytes(lease),
                    history_depth: u32::from_le_bytes(depth),
                    retained_depth: u32::from_le_bytes(retained),
                    reliability,
                    durability,
                    liveliness,
                },
            };
            written += 1;
        }
        cursor += count;
        if count < MAX_OWN_ROWS {
            return Ok(written);
        }
    }
}

/// The empty row set, for a caller sizing its own array.
pub const EMPTY_ROWS: [Row; MAX_GRAPH_ROWS] = [Row {
    component_identity: [0; 32],
    route_index: 0,
    direction: 0,
    visibility: 0,
    history_depth: 0,
    qos: TransportQos {
        deadline_ns: 0,
        lifespan_ns: 0,
        lease_ns: 0,
        history_depth: 0,
        retained_depth: 0,
        reliability: 0,
        durability: 0,
        liveliness: 0,
    },
}; MAX_GRAPH_ROWS];
