#!/usr/bin/env python3
"""Generate the diagnostic receipt's host constants and structural codec."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "lib"))

from harness import ROOT  # noqa: E402
from zutai_cli import STDLIB, binary  # noqa: E402

SOURCE = ROOT / "contracts/devloop-diagnostics/v1/bindings.zt"
OUTPUT = ROOT / "scripts/lib/devloop_diagnostics_contract.py"


def render() -> str:
    environment = dict(os.environ, ZUTAI_STDLIB_ROOT=str(STDLIB))
    result = subprocess.run(
        [str(binary()), "json", str(SOURCE)],
        cwd=ROOT,
        env=environment,
        capture_output=True,
        text=True,
        check=True,
    )
    values = json.loads(result.stdout)
    constants = {
        "FORMAT_VERSION": values["formatVersion"],
        "KIND": values["kind"],
        "MAX_RECEIPT_BYTES": values["maxReceiptBytes"],
        "MAX_OUTPUT_BYTES": values["maxOutputBytes"],
        "MAX_PATH_BYTES": values["maxPathBytes"],
    }
    fields = {
        "RECEIPT_FIELDS": tuple(field["name"] for field in values["receiptFields"]),
        "IDENTITY_FIELDS": tuple(field["name"] for field in values["identityFields"]),
    }
    return (
        "# @generated by contracts/devloop-diagnostics/v1/bindings.zt; do not edit.\n"
        "import json\n\n"
        + "".join(f"{name} = {value!r}\n" for name, value in (constants | fields).items())
        + """

def encode(receipt):
    if set(receipt) != set(RECEIPT_FIELDS) or set(receipt["identity"]) != set(IDENTITY_FIELDS):
        raise ValueError("diagnostic receipt fields do not match schema")
    def value(item):
        if isinstance(item, dict):
            return "{" + "".join(name + "=" + value(part) + ";" for name, part in item.items()) + "}"
        if type(item) is bool:
            return "true" if item else "false"
        if type(item) is int:
            return str(item)
        if isinstance(item, str):
            return json.dumps(item)
        raise ValueError("unsupported diagnostic receipt value")
    encoded = (value(receipt) + "\\n").encode()
    if len(encoded) > MAX_RECEIPT_BYTES:
        raise ValueError("diagnostic receipt exceeds schema bound")
    return encoded
"""
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != rendered:
            raise SystemExit(f"stale {OUTPUT.relative_to(ROOT)}; run {Path(__file__).name}")
        print("devloop diagnostic bindings are current")
    else:
        OUTPUT.write_text(rendered)
        print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
