#!/usr/bin/env python3
"""Generate the observation refusal replay constants and structural codec."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "lib"))
from harness import ROOT  # noqa: E402
from zutai_cli import STDLIB, binary  # noqa: E402

SOURCE = ROOT / "contracts/observation-capacity-refusal/v1/bindings.zt"
OUTPUT = ROOT / "scripts/lib/observation_capacity_contract.py"


def render() -> str:
    result = subprocess.run(
        [str(binary()), "json", str(SOURCE)],
        cwd=ROOT,
        env=dict(os.environ, ZUTAI_STDLIB_ROOT=str(STDLIB)),
        capture_output=True,
        text=True,
        check=True,
    )
    value = json.loads(result.stdout)
    names = {
        "FORMAT_VERSION": "formatVersion",
        "KIND": "kind",
        "OUTCOME": "outcome",
        "GATE": "gate",
        "STDERR_LIMIT_BYTES": "stderrLimitBytes",
        "MAX_RECEIPT_BYTES": "maxReceiptBytes",
        "MAX_PATH_BYTES": "maxPathBytes",
        "REUSE_SECONDS": "reuseSeconds",
    }
    constants = {name: value[field] for name, field in names.items()}
    constants["RECEIPT_FIELDS"] = tuple(field["name"] for field in value["receiptFields"])
    constants["IDENTITY_FIELDS"] = tuple(field["name"] for field in value["identityFields"])
    return (
        "# @generated by contracts/observation-capacity-refusal/v1/bindings.zt; do not edit.\nimport json\n\n"
        + "".join(f"{k} = {v!r}\n" for k, v in constants.items())
        + """

def encode(receipt):
    if set(receipt) != set(RECEIPT_FIELDS) or set(receipt["identity"]) != set(IDENTITY_FIELDS):
        raise ValueError("capacity refusal fields do not match schema")
    def value(item):
        if isinstance(item, dict):
            return "{" + "".join(k + "=" + value(v) + ";" for k,v in item.items()) + "}"
        if type(item) is int:
            return str(item)
        if isinstance(item, str):
            return json.dumps(item)
        raise ValueError("unsupported capacity refusal value")
    raw = (value(receipt) + "\\n").encode()
    if len(raw) > MAX_RECEIPT_BYTES:
        raise ValueError("capacity refusal exceeds schema bound")
    return raw
"""
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text() != text:
            raise SystemExit("observation capacity bindings stale")
        print("observation capacity bindings are current")
    else:
        OUTPUT.write_text(text)
        print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
