[package]
name = "entry_point"
version = "0.1.0"
edition = "2024"



[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"
serde_json = "1.0"
bootloader = "0.11"
cargo-emit = "0.1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"