[build]
target = "x86_64-unknown-none"


[target.x86_64-unknown-none]
rustflags = [
    "-C",
    "link-args=--entry=_start", # Specify entry point explicitly
    "-C",
    "link-args=-z nostart-stop-gc", # Prevent garbage collection of linkme symbols
]
runner = "../entry_point/target/release/entry_point"
