[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "--cfg", "curve25519_dalek_backend=\"serial\"",
    "-C", "force-frame-pointers",
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--gc-sections",
    "-C", "codegen-units=1",
]
runner = "scripts/run-kernel.sh"
