set(KernelPlatform "cv1800b-duo" CACHE STRING "")
set(KernelSel4Arch "riscv64" CACHE STRING "")
set(KernelIsMCS OFF CACHE BOOL "")
set(KernelMaxNumNodes 1 CACHE STRING "")
set(KernelVerificationBuild OFF CACHE BOOL "")
set(KernelDebugBuild ON CACHE BOOL "")
set(KernelPrinting ON CACHE BOOL "")
set(KernelRiscvExportTimeUser ON CACHE BOOL "")
