/* @generated by contracts/pwm-servo/v1/gen_rust.zt; do not edit. */
/* Source contract: contracts/pwm-servo/v1/schema.zt */
#ifndef SLIME_PWM_SERVO_H
#define SLIME_PWM_SERVO_H

#include <stddef.h>
#include <stdint.h>

#define SLIME_PWM_SERVO_FORMAT_VERSION 1U
#define SLIME_PWM_SERVO_MAGIC 1397577552U
#define SLIME_PWM_SERVO_REQUEST_LEN 32U
#define SLIME_PWM_SERVO_REPLY_LEN 16U
#define SLIME_PWM_SERVO_MAX_CHANNEL 5U
#define SLIME_PWM_SERVO_MIN_PERIOD_US 2000U
#define SLIME_PWM_SERVO_MAX_PERIOD_US 20000U
#define SLIME_PWM_SERVO_MIN_PULSE_US 1000U
#define SLIME_PWM_SERVO_MAX_PULSE_US 2000U
#define SLIME_PWM_SERVO_PULSE_DISABLE 0U
#define SLIME_PWM_SERVO_CLOCK_HZ 1000000U
#define SLIME_PWM_SERVO_STATUS_OK 0
#define SLIME_PWM_SERVO_STATUS_BAD_CHANNEL (-1)
#define SLIME_PWM_SERVO_STATUS_BAD_PERIOD (-2)
#define SLIME_PWM_SERVO_STATUS_BAD_PULSE (-3)
#define SLIME_PWM_SERVO_STATUS_NO_DEVICE (-4)
#define SLIME_PWM_SERVO_STATUS_DEVICE_ERROR (-5)
#define SLIME_PWM_SERVO_STATUS_MALFORMED (-6)

#define SLIME_PWM_SERVO_OFF_REQUEST_MAGIC 0U
#define SLIME_PWM_SERVO_OFF_REQUEST_VERSION 4U
#define SLIME_PWM_SERVO_OFF_REQUEST_CHANNEL 8U
#define SLIME_PWM_SERVO_OFF_REQUEST_PERIOD_US 12U
#define SLIME_PWM_SERVO_OFF_REQUEST_PULSE_US 16U
#define SLIME_PWM_SERVO_OFF_REQUEST_FLAGS 20U
#define SLIME_PWM_SERVO_OFF_REQUEST_RESERVED 24U
#define SLIME_PWM_SERVO_OFF_REPLY_MAGIC 0U
#define SLIME_PWM_SERVO_OFF_REPLY_VERSION 4U
#define SLIME_PWM_SERVO_OFF_REPLY_STATUS 8U
#define SLIME_PWM_SERVO_OFF_REPLY_DETAIL 12U

typedef struct {
    uint32_t channel;
    uint32_t period_us;
    uint32_t pulse_us;
    uint32_t flags;
} SlimePwmServoRequest;

typedef struct {
    int32_t status;
    uint32_t detail;
} SlimePwmServoReply;

static inline void slime_pwm_servo_store_u32(uint8_t *out, uint32_t value)
{
    size_t index;
    for (index = 0; index < 4; ++index) { out[index] = (uint8_t)(value >> (index * 8)); }
}

static inline uint32_t slime_pwm_servo_load_u32(const uint8_t *in)
{
    size_t index;
    uint32_t value = 0;
    for (index = 0; index < 4; ++index) { value |= (uint32_t)in[index] << (index * 8); }
    return value;
}

static inline void slime_pwm_servo_request_encode(const SlimePwmServoRequest *request, uint8_t out[SLIME_PWM_SERVO_REQUEST_LEN])
{
    size_t index;
    for (index = 0; index < SLIME_PWM_SERVO_REQUEST_LEN; ++index) { out[index] = 0; }
    slime_pwm_servo_store_u32(out + SLIME_PWM_SERVO_OFF_REQUEST_MAGIC, SLIME_PWM_SERVO_MAGIC);
    slime_pwm_servo_store_u32(out + SLIME_PWM_SERVO_OFF_REQUEST_VERSION, SLIME_PWM_SERVO_FORMAT_VERSION);
    slime_pwm_servo_store_u32(out + SLIME_PWM_SERVO_OFF_REQUEST_CHANNEL, request->channel);
    slime_pwm_servo_store_u32(out + SLIME_PWM_SERVO_OFF_REQUEST_PERIOD_US, request->period_us);
    slime_pwm_servo_store_u32(out + SLIME_PWM_SERVO_OFF_REQUEST_PULSE_US, request->pulse_us);
    slime_pwm_servo_store_u32(out + SLIME_PWM_SERVO_OFF_REQUEST_FLAGS, request->flags);
}

static inline int slime_pwm_servo_reply_decode(const uint8_t *in, size_t len, SlimePwmServoReply *reply)
{
    if (len < SLIME_PWM_SERVO_REPLY_LEN || reply == NULL
        || slime_pwm_servo_load_u32(in + SLIME_PWM_SERVO_OFF_REPLY_MAGIC) != SLIME_PWM_SERVO_MAGIC
        || slime_pwm_servo_load_u32(in + SLIME_PWM_SERVO_OFF_REPLY_VERSION) != SLIME_PWM_SERVO_FORMAT_VERSION) { return 0; }
    reply->status = (int32_t)slime_pwm_servo_load_u32(in + SLIME_PWM_SERVO_OFF_REPLY_STATUS);
    reply->detail = slime_pwm_servo_load_u32(in + SLIME_PWM_SERVO_OFF_REPLY_DETAIL);
    return 1;
}

#endif
