/* @generated by contracts/spawn/v1/gen_rust.zt; do not edit. */
/* Source contract: contracts/spawn/v1/schema.zt */
#ifndef SLIME_SPAWN_H
#define SLIME_SPAWN_H

#include <stddef.h>
#include <stdint.h>

#define SLIME_SPAWN_FORMAT_VERSION 1U
#define SLIME_SPAWN_MAGIC 1313559123U
#define SLIME_SPAWN_REQUEST_LEN 64U
#define SLIME_SPAWN_REPLY_LEN 64U
#define SLIME_SPAWN_MAX_COMMAND_BYTES 16U
#define SLIME_SPAWN_REQUEST_FLAG_WAIT 1U
#define SLIME_SPAWN_REQUEST_FLAG_DETACHED 4U

#define SLIME_SPAWN_OFF_REQUEST_MAGIC 0U
#define SLIME_SPAWN_OFF_REQUEST_VERSION 4U
#define SLIME_SPAWN_OFF_REQUEST_FLAGS 8U
#define SLIME_SPAWN_OFF_REQUEST_COMMAND_LEN 12U
#define SLIME_SPAWN_OFF_REQUEST_ARGUMENT_COUNT 14U
#define SLIME_SPAWN_OFF_REQUEST_ENVIRONMENT_COUNT 15U
#define SLIME_SPAWN_OFF_REQUEST_CAPABILITY_ROLES 16U
#define SLIME_SPAWN_OFF_REQUEST_CLIENT_BUDGET 17U
#define SLIME_SPAWN_OFF_REQUEST_COMMAND 18U
#define SLIME_SPAWN_OFF_REQUEST_ARGUMENTS 34U
#define SLIME_SPAWN_OFF_REQUEST_ENVIRONMENT 42U
#define SLIME_SPAWN_OFF_REQUEST_GRANT_RIGHTS 50U
#define SLIME_SPAWN_OFF_REQUEST_RESERVED 54U
#define SLIME_SPAWN_OFF_REPLY_MAGIC 0U
#define SLIME_SPAWN_OFF_REPLY_VERSION 4U
#define SLIME_SPAWN_OFF_REPLY_STATUS 8U
#define SLIME_SPAWN_OFF_REPLY_TERMINATION_KIND 12U
#define SLIME_SPAWN_OFF_REPLY_SUPERVISION_SLOT 16U
#define SLIME_SPAWN_OFF_REPLY_DETAIL 20U

typedef struct {
    uint32_t flags;
    uint16_t command_len;
    uint8_t argument_count;
    uint8_t environment_count;
    uint8_t capability_roles;
    uint8_t client_budget;
    uint8_t command[16];
    uint8_t arguments[8];
    uint8_t environment[8];
    uint32_t grant_rights;
} SlimeSpawnRequest;

typedef struct {
    int32_t status;
    uint32_t termination_kind;
    uint32_t supervision_slot;
    uint64_t detail;
} SlimeSpawnReply;

static inline void slime_spawn_store_u16(uint8_t *out, uint16_t value)
{
    out[0] = (uint8_t)value;
    out[1] = (uint8_t)(value >> 8);
}

static inline void slime_spawn_store_u32(uint8_t *out, uint32_t value)
{
    size_t index;
    for (index = 0; index < 4; ++index) { out[index] = (uint8_t)(value >> (index * 8)); }
}

static inline uint32_t slime_spawn_load_u32(const uint8_t *in)
{
    size_t index;
    uint32_t value = 0;
    for (index = 0; index < 4; ++index) { value |= (uint32_t)in[index] << (index * 8); }
    return value;
}

static inline uint64_t slime_spawn_load_u64(const uint8_t *in)
{
    size_t index;
    uint64_t value = 0;
    for (index = 0; index < 8; ++index) { value |= (uint64_t)in[index] << (index * 8); }
    return value;
}

static inline void slime_spawn_request_encode(const SlimeSpawnRequest *request, uint8_t out[SLIME_SPAWN_REQUEST_LEN])
{
    size_t index;
    for (index = 0; index < SLIME_SPAWN_REQUEST_LEN; ++index) { out[index] = 0; }
    slime_spawn_store_u32(out + SLIME_SPAWN_OFF_REQUEST_MAGIC, SLIME_SPAWN_MAGIC);
    slime_spawn_store_u32(out + SLIME_SPAWN_OFF_REQUEST_VERSION, SLIME_SPAWN_FORMAT_VERSION);
    slime_spawn_store_u32(out + SLIME_SPAWN_OFF_REQUEST_FLAGS, request->flags);
    slime_spawn_store_u16(out + SLIME_SPAWN_OFF_REQUEST_COMMAND_LEN, request->command_len);
    out[SLIME_SPAWN_OFF_REQUEST_ARGUMENT_COUNT] = request->argument_count;
    out[SLIME_SPAWN_OFF_REQUEST_ENVIRONMENT_COUNT] = request->environment_count;
    out[SLIME_SPAWN_OFF_REQUEST_CAPABILITY_ROLES] = request->capability_roles;
    out[SLIME_SPAWN_OFF_REQUEST_CLIENT_BUDGET] = request->client_budget;
    for (index = 0; index < sizeof(request->command); ++index) { out[SLIME_SPAWN_OFF_REQUEST_COMMAND + index] = request->command[index]; }
    for (index = 0; index < sizeof(request->arguments); ++index) { out[SLIME_SPAWN_OFF_REQUEST_ARGUMENTS + index] = request->arguments[index]; }
    for (index = 0; index < sizeof(request->environment); ++index) { out[SLIME_SPAWN_OFF_REQUEST_ENVIRONMENT + index] = request->environment[index]; }
    slime_spawn_store_u32(out + SLIME_SPAWN_OFF_REQUEST_GRANT_RIGHTS, request->grant_rights);
}

static inline int slime_spawn_reply_decode(const uint8_t *in, size_t len, SlimeSpawnReply *reply)
{
    if (len < SLIME_SPAWN_REPLY_LEN || reply == NULL
        || slime_spawn_load_u32(in + SLIME_SPAWN_OFF_REPLY_MAGIC) != SLIME_SPAWN_MAGIC
        || slime_spawn_load_u32(in + SLIME_SPAWN_OFF_REPLY_VERSION) != SLIME_SPAWN_FORMAT_VERSION) { return 0; }
    reply->status = (int32_t)slime_spawn_load_u32(in + SLIME_SPAWN_OFF_REPLY_STATUS);
    reply->termination_kind = slime_spawn_load_u32(in + SLIME_SPAWN_OFF_REPLY_TERMINATION_KIND);
    reply->supervision_slot = slime_spawn_load_u32(in + SLIME_SPAWN_OFF_REPLY_SUPERVISION_SLOT);
    reply->detail = slime_spawn_load_u64(in + SLIME_SPAWN_OFF_REPLY_DETAIL);
    return 1;
}

#endif
