// @generated by contracts/component/v1/gen_rust.zt; do not edit.
// Source contract: contracts/component/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const KERNEL_ABI_VERSION: u32 = 1;
pub const HEADER_LEN: usize = 32;
pub const SEGMENT_LEN: usize = 20;
pub const MAX_SEGMENTS: u16 = 16;
pub const MAX_IMAGE_BYTES: u64 = 16777216;
pub const MAX_STACK_BYTES: u32 = 1048576;
pub const DEFAULT_STACK_BYTES: u32 = 16384;
pub const SEGMENT_FLAG_WRITE: u16 = 1;
pub const SEGMENT_FLAG_EXEC: u16 = 2;
pub const IMAGE_MAGIC: u64 = 5786355061169409107;
pub const IMAGE_MAGIC_BYTES: [u8; 8] = IMAGE_MAGIC.to_le_bytes();

pub const OFF_HEADER_MAGIC: usize = 0;
pub const OFF_HEADER_FORMAT_VERSION: usize = 8;
pub const OFF_HEADER_HEADER_SIZE: usize = 12;
pub const OFF_HEADER_KERNEL_ABI: usize = 16;
pub const OFF_HEADER_ENTRY_OFFSET: usize = 20;
pub const OFF_HEADER_SEGMENT_COUNT: usize = 24;
pub const OFF_HEADER_RESERVED: usize = 26;
pub const OFF_HEADER_STACK_BYTES: usize = 28;

pub const OFF_SEGMENT_VADDR_OFFSET: usize = 0;
pub const OFF_SEGMENT_MEM_LEN: usize = 4;
pub const OFF_SEGMENT_FILE_OFFSET: usize = 8;
pub const OFF_SEGMENT_FILE_LEN: usize = 12;
pub const OFF_SEGMENT_FLAGS: usize = 16;
pub const OFF_SEGMENT_RESERVED: usize = 18;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireImageHeader {
    pub magic: u64,
    pub format_version: u32,
    pub header_size: u32,
    pub kernel_abi: u32,
    pub entry_offset: u32,
    pub segment_count: u16,
    pub reserved: u16,
    pub stack_bytes: u32,
}

impl WireImageHeader {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < HEADER_LEN {
            return None;
        }
        Some(Self {
            magic: u64::from_le_bytes(
                buf[OFF_HEADER_MAGIC..OFF_HEADER_MAGIC + 8]
                    .try_into()
                    .expect("generated component layout"),
            ),
            format_version: u32::from_le_bytes(
                buf[OFF_HEADER_FORMAT_VERSION..OFF_HEADER_FORMAT_VERSION + 4]
                    .try_into()
                    .expect("generated component layout"),
            ),
            header_size: u32::from_le_bytes(
                buf[OFF_HEADER_HEADER_SIZE..OFF_HEADER_HEADER_SIZE + 4]
                    .try_into()
                    .expect("generated component layout"),
            ),
            kernel_abi: u32::from_le_bytes(
                buf[OFF_HEADER_KERNEL_ABI..OFF_HEADER_KERNEL_ABI + 4]
                    .try_into()
                    .expect("generated component layout"),
            ),
            entry_offset: u32::from_le_bytes(
                buf[OFF_HEADER_ENTRY_OFFSET..OFF_HEADER_ENTRY_OFFSET + 4]
                    .try_into()
                    .expect("generated component layout"),
            ),
            segment_count: u16::from_le_bytes(
                buf[OFF_HEADER_SEGMENT_COUNT..OFF_HEADER_SEGMENT_COUNT + 2]
                    .try_into()
                    .expect("generated component layout"),
            ),
            reserved: u16::from_le_bytes(
                buf[OFF_HEADER_RESERVED..OFF_HEADER_RESERVED + 2]
                    .try_into()
                    .expect("generated component layout"),
            ),
            stack_bytes: u32::from_le_bytes(
                buf[OFF_HEADER_STACK_BYTES..OFF_HEADER_STACK_BYTES + 4]
                    .try_into()
                    .expect("generated component layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; HEADER_LEN] {
        let mut buf = [0u8; HEADER_LEN];
        buf[OFF_HEADER_MAGIC..OFF_HEADER_MAGIC + 8].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_HEADER_FORMAT_VERSION..OFF_HEADER_FORMAT_VERSION + 4]
            .copy_from_slice(&self.format_version.to_le_bytes());
        buf[OFF_HEADER_HEADER_SIZE..OFF_HEADER_HEADER_SIZE + 4]
            .copy_from_slice(&self.header_size.to_le_bytes());
        buf[OFF_HEADER_KERNEL_ABI..OFF_HEADER_KERNEL_ABI + 4]
            .copy_from_slice(&self.kernel_abi.to_le_bytes());
        buf[OFF_HEADER_ENTRY_OFFSET..OFF_HEADER_ENTRY_OFFSET + 4]
            .copy_from_slice(&self.entry_offset.to_le_bytes());
        buf[OFF_HEADER_SEGMENT_COUNT..OFF_HEADER_SEGMENT_COUNT + 2]
            .copy_from_slice(&self.segment_count.to_le_bytes());
        buf[OFF_HEADER_RESERVED..OFF_HEADER_RESERVED + 2]
            .copy_from_slice(&self.reserved.to_le_bytes());
        buf[OFF_HEADER_STACK_BYTES..OFF_HEADER_STACK_BYTES + 4]
            .copy_from_slice(&self.stack_bytes.to_le_bytes());
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireSegmentRecord {
    pub vaddr_offset: u32,
    pub mem_len: u32,
    pub file_offset: u32,
    pub file_len: u32,
    pub flags: u16,
    pub reserved: u16,
}

impl WireSegmentRecord {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < SEGMENT_LEN {
            return None;
        }
        Some(Self {
            vaddr_offset: u32::from_le_bytes(
                buf[OFF_SEGMENT_VADDR_OFFSET..OFF_SEGMENT_VADDR_OFFSET + 4]
                    .try_into()
                    .expect("generated component layout"),
            ),
            mem_len: u32::from_le_bytes(
                buf[OFF_SEGMENT_MEM_LEN..OFF_SEGMENT_MEM_LEN + 4]
                    .try_into()
                    .expect("generated component layout"),
            ),
            file_offset: u32::from_le_bytes(
                buf[OFF_SEGMENT_FILE_OFFSET..OFF_SEGMENT_FILE_OFFSET + 4]
                    .try_into()
                    .expect("generated component layout"),
            ),
            file_len: u32::from_le_bytes(
                buf[OFF_SEGMENT_FILE_LEN..OFF_SEGMENT_FILE_LEN + 4]
                    .try_into()
                    .expect("generated component layout"),
            ),
            flags: u16::from_le_bytes(
                buf[OFF_SEGMENT_FLAGS..OFF_SEGMENT_FLAGS + 2]
                    .try_into()
                    .expect("generated component layout"),
            ),
            reserved: u16::from_le_bytes(
                buf[OFF_SEGMENT_RESERVED..OFF_SEGMENT_RESERVED + 2]
                    .try_into()
                    .expect("generated component layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; SEGMENT_LEN] {
        let mut buf = [0u8; SEGMENT_LEN];
        buf[OFF_SEGMENT_VADDR_OFFSET..OFF_SEGMENT_VADDR_OFFSET + 4]
            .copy_from_slice(&self.vaddr_offset.to_le_bytes());
        buf[OFF_SEGMENT_MEM_LEN..OFF_SEGMENT_MEM_LEN + 4]
            .copy_from_slice(&self.mem_len.to_le_bytes());
        buf[OFF_SEGMENT_FILE_OFFSET..OFF_SEGMENT_FILE_OFFSET + 4]
            .copy_from_slice(&self.file_offset.to_le_bytes());
        buf[OFF_SEGMENT_FILE_LEN..OFF_SEGMENT_FILE_LEN + 4]
            .copy_from_slice(&self.file_len.to_le_bytes());
        buf[OFF_SEGMENT_FLAGS..OFF_SEGMENT_FLAGS + 2].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_SEGMENT_RESERVED..OFF_SEGMENT_RESERVED + 2]
            .copy_from_slice(&self.reserved.to_le_bytes());
        buf
    }
}
