//! A participant's own declared rows, read from the root rather than compiled in.
//!
//! B70/CP2 step 2. Every fabric participant needs one fact about itself before
//! it can attach a ring: the KEEP_LAST depth the fabric formatted that ring at.
//! It read that from `FABRIC_HISTORY_DEPTHS`, a table `components/bins/build.rs`
//! generated by parsing the manifest — so the component could not be built
//! outside this crate against this generation.
//!
//! `CAPABILITY GRAPH READ` answers it instead. A non-holder reads its own rows
//! and nothing else, which is the same scoping `resolve_binding` applies: the
//! component learns what the generation declares *about it*, which is exactly
//! what the generated table told it, and learns nothing about anyone else.
//!
//! # Why the ring header cannot answer this
//!
//! The mapped ring's header carries `slot_count`, and it is tempting to read it
//! there. It must not be: the ring crosses as a *writable* loan, so the header
//! is in memory the peer can write, and `Ring::attach` takes `expected_slots`
//! from the caller's own record precisely so a hostile peer cannot choose the
//! value the reader trusts. The header carries the number and the caller
//! supplies it independently; `valid_ring_header` compares them, and that
//! agreement is the check. This module supplies the caller's half.

use boot_contracts::fabric_graph::PARTICIPANT_ENTRY_BYTES;

/// Rows one read may return. A component's own share is small — the largest any
/// seL4 manifest declares for one participant is two — so a single call is
/// always enough and the loop below is a bound, not a pager.
const MAX_OWN_ROWS: usize = 8;

/// Byte offsets into a participant record. Named from the contract's own
/// decoder (`FabricGraph::participant`) rather than re-derived, and used only to
/// read two fields out of a record this component received whole.
const ROUTE_INDEX: core::ops::Range<usize> = 64..68;
const HISTORY_DEPTH: core::ops::Range<usize> = 104..108;

/// The KEEP_LAST depth this component's row declares for `route_index`, or
/// `None` if the generation declares no such row.
///
/// `route_index` comes from `slime_rt::graph_route_index`, which resolves the
/// identity a participant folds from its own route name, interface identity,
/// and contract kind.
pub fn history_depth(route_index: u32) -> Option<usize> {
    let mut rows = [0u8; MAX_OWN_ROWS * PARTICIPANT_ENTRY_BYTES];
    let count = slime_rt::graph_read(0, &mut rows).ok()?;
    for row in 0..count {
        let bytes = &rows[row * PARTICIPANT_ENTRY_BYTES..(row + 1) * PARTICIPANT_ENTRY_BYTES];
        let declared = u32::from_le_bytes(bytes[ROUTE_INDEX].try_into().ok()?);
        if declared == route_index {
            return Some(u32::from_le_bytes(bytes[HISTORY_DEPTH].try_into().ok()?) as usize);
        }
    }
    None
}

/// This component's declared KEEP_LAST depth for the route it names, floored at
/// the ring's own minimum exactly as the fabric floors it.
///
/// The whole path a participant needs: fold the route identity, ask the root
/// which index the graph gives it, then read this component's own row.
pub fn ring_slots(route_identity: &[u8; 32]) -> Option<usize> {
    let index = slime_rt::graph_route_index(route_identity).ok()?;
    let depth = history_depth(index as u32)?;
    Some(depth.max(slime_proto::fabric_ring::MIN_RING_SLOTS))
}
