//! A participant's own declared rows, read from the root rather than compiled in.
//!
//! B70/CP2 step 2. Every fabric participant needs one fact about itself before
//! it can attach a ring: the KEEP_LAST depth the fabric formatted that ring at.
//! It read that from `FABRIC_HISTORY_DEPTHS`, a table `components/bins/build.rs`
//! generated by parsing the manifest — so the component could not be built
//! outside this crate against this generation.
//!
//! `CAPABILITY GRAPH READ` answers it instead. A non-holder reads its own rows
//! and nothing else, which is the same scoping `resolve_binding` applies: the
//! component learns what the generation declares *about it*, which is exactly
//! what the generated table told it, and learns nothing about anyone else.
//!
//! # Why the ring header cannot answer this
//!
//! The mapped ring's header carries `slot_count`, and it is tempting to read it
//! there. It must not be: the ring crosses as a *writable* loan, so the header
//! is in memory the peer can write, and `Ring::attach` takes `expected_slots`
//! from the caller's own record precisely so a hostile peer cannot choose the
//! value the reader trusts. The header carries the number and the caller
//! supplies it independently; `valid_ring_header` compares them, and that
//! agreement is the check. This module supplies the caller's half.

use boot_contracts::fabric_graph::PARTICIPANT_ENTRY_BYTES;

/// Rows one read may return. A component's own share is small — the largest any
/// seL4 manifest declares for one participant is two — so a single call is
/// always enough and the loop below is a bound, not a pager.
const MAX_OWN_ROWS: usize = 8;

/// Byte offsets into a participant record. Named from the contract's own
/// decoder (`FabricGraph::participant`) rather than re-derived, and used only to
/// read two fields out of a record this component received whole.
const COMPONENT_IDENTITY: core::ops::Range<usize> = 32..64;
const ROUTE_INDEX: core::ops::Range<usize> = 64..68;
const DIRECTION: core::ops::Range<usize> = 68..72;
const HISTORY_DEPTH: core::ops::Range<usize> = 104..108;

/// The KEEP_LAST depth this component's row declares for `route_index`, or
/// `None` if the generation declares no such row.
///
/// `route_index` comes from `slime_rt::graph_route_index`, which resolves the
/// identity a participant folds from its own route name, interface identity,
/// and contract kind.
pub fn history_depth(route_index: u32) -> Option<usize> {
    let mut rows = [0u8; MAX_OWN_ROWS * PARTICIPANT_ENTRY_BYTES];
    let count = slime_rt::graph_read(0, &mut rows).ok()?;
    for row in 0..count {
        let bytes = &rows[row * PARTICIPANT_ENTRY_BYTES..(row + 1) * PARTICIPANT_ENTRY_BYTES];
        let declared = u32::from_le_bytes(bytes[ROUTE_INDEX].try_into().ok()?);
        if declared == route_index {
            return Some(u32::from_le_bytes(bytes[HISTORY_DEPTH].try_into().ok()?) as usize);
        }
    }
    None
}

/// This component's declared KEEP_LAST depth for the route it names, floored at
/// the ring's own minimum exactly as the fabric floors it.
///
/// The whole path a participant needs: fold the route identity, ask the root
/// which index the graph gives it, then read this component's own row.
pub fn ring_slots(route_identity: &[u8; 32]) -> Option<usize> {
    let index = slime_rt::graph_route_index(route_identity).ok()?;
    let depth = history_depth(index as u32)?;
    Some(depth.max(slime_proto::fabric_ring::MIN_RING_SLOTS))
}

/// The KEEP_LAST depth declared for `component` on `route_index`.
///
/// For the graph's declared holder, which reads every row: the four
/// participants above ask about themselves and can use `history_depth`, but the
/// fabric provisions a ring *for* each participant and so must ask about
/// someone else. A non-holder calling this sees only its own rows, so it can
/// answer only about itself -- which is the scoping, not a limitation of this
/// function.
pub fn history_depth_of(component_identity: &[u8; 32], route_index: u32) -> Option<usize> {
    let mut rows = [0u8; MAX_OWN_ROWS * PARTICIPANT_ENTRY_BYTES];
    let mut cursor = 0usize;
    loop {
        let count = slime_rt::graph_read(cursor, &mut rows).ok()?;
        if count == 0 {
            return None;
        }
        for row in 0..count {
            let bytes = &rows[row * PARTICIPANT_ENTRY_BYTES..(row + 1) * PARTICIPANT_ENTRY_BYTES];
            if &bytes[COMPONENT_IDENTITY] != component_identity.as_slice() {
                continue;
            }
            let declared = u32::from_le_bytes(bytes[ROUTE_INDEX].try_into().ok()?);
            if declared == route_index {
                return Some(u32::from_le_bytes(bytes[HISTORY_DEPTH].try_into().ok()?) as usize);
            }
        }
        cursor += count;
        if count < MAX_OWN_ROWS {
            return None;
        }
    }
}

/// Rows a whole-graph read may need to hold at once. The largest seL4 graph
/// declares 15 participants; the contract ceiling is 32.
const MAX_GRAPH_ROWS: usize = 32;

/// One participant row, decoded to the fields a broker asks about.
#[derive(Clone, Copy)]
pub struct Row {
    pub component_identity: [u8; 32],
    pub route_index: u32,
    pub direction: u32,
    pub history_depth: usize,
}

/// Every row this caller may read, in the order the resource stores them.
///
/// For the graph's declared holder that is the whole participant table; for
/// anyone else it is their own rows plus those of components they share a
/// declared edge with. The caller supplies the buffer because a `no_std`
/// component has no allocator, and `MAX_GRAPH_ROWS` bounds what one can hold.
///
/// Returns how many rows were written. A short count is the end of the table,
/// not an error.
pub fn rows(out: &mut [Row; MAX_GRAPH_ROWS]) -> usize {
    let mut buffer = [0u8; MAX_OWN_ROWS * PARTICIPANT_ENTRY_BYTES];
    let mut cursor = 0usize;
    let mut written = 0usize;
    loop {
        let Ok(count) = slime_rt::graph_read(cursor, &mut buffer) else {
            return written;
        };
        if count == 0 {
            return written;
        }
        for row in 0..count {
            if written == out.len() {
                return written;
            }
            let bytes = &buffer[row * PARTICIPANT_ENTRY_BYTES..(row + 1) * PARTICIPANT_ENTRY_BYTES];
            let Ok(component_identity) = <[u8; 32]>::try_from(&bytes[COMPONENT_IDENTITY]) else {
                return written;
            };
            let Ok(route) = bytes[ROUTE_INDEX].try_into() else {
                return written;
            };
            let Ok(direction) = bytes[DIRECTION].try_into() else {
                return written;
            };
            let Ok(depth) = bytes[HISTORY_DEPTH].try_into() else {
                return written;
            };
            out[written] = Row {
                component_identity,
                route_index: u32::from_le_bytes(route),
                direction: u32::from_le_bytes(direction),
                history_depth: u32::from_le_bytes(depth) as usize,
            };
            written += 1;
        }
        cursor += count;
        if count < MAX_OWN_ROWS {
            return written;
        }
    }
}

/// The empty row set, for a caller sizing its own array.
pub const EMPTY_ROWS: [Row; MAX_GRAPH_ROWS] = [Row {
    component_identity: [0; 32],
    route_index: 0,
    direction: 0,
    history_depth: 0,
}; MAX_GRAPH_ROWS];
