[package]
name = "slime_os-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader_api = "0.11"
volatile = { version="0.6.1", features = ["unstable"]}
spin = "0.10"
fontdue = { version = "0.9.3", default-features = false, features = ["hashbrown"]} # Disable SIMD
linked_list_allocator = "0.10.5"

