[package]
name = "slime_os-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader_api = "0.11"
volatile = "0.2.6"
spin = "0.9.8"


[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
