// @generated by contracts/block/v2/gen_rust.zt; do not edit.
// Source contract: contracts/block/v2/schema.zt

pub const FORMAT_VERSION: u16 = 2;
pub const REQUEST_LEN: usize = 56;
pub const REPLY_LEN: usize = 24;
pub const BLOCK_MAGIC: u32 = 843796546;
pub const SECTOR_BYTES: usize = 512;
pub const MAX_SECTORS_PER_REQUEST: u32 = 8;
pub const OP_READ: u8 = 1;
pub const OP_WRITE: u8 = 2;
pub const OP_FLUSH: u8 = 3;
pub const OP_GEOMETRY: u8 = 4;
pub const KNOWN_REQUEST_FLAGS: u8 = 0;
pub const DEVICE_STATUS_OK: u32 = 0;
pub const DEVICE_STATUS_IO_ERR: u32 = 1;
pub const DEVICE_STATUS_UNSUPPORTED: u32 = 2;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OP: usize = 6;
pub const OFF_REQUEST_FLAGS: usize = 7;
pub const OFF_REQUEST_LBA: usize = 8;
pub const OFF_REQUEST_SECTOR_COUNT: usize = 16;
pub const OFF_REQUEST_RESERVED: usize = 20;
pub const OFF_REQUEST_PADDING: usize = 24;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireBlockRequest {
    pub magic: u32,
    pub version: u16,
    pub op: u8,
    pub flags: u8,
    pub lba: u64,
    pub sector_count: u32,
    pub reserved: [u8; 4],
    pub padding: [u8; 32],
}

impl WireBlockRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated block-v2 layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 2]
                    .try_into()
                    .expect("generated block-v2 layout"),
            ),
            op: buf[OFF_REQUEST_OP],
            flags: buf[OFF_REQUEST_FLAGS],
            lba: u64::from_le_bytes(
                buf[OFF_REQUEST_LBA..OFF_REQUEST_LBA + 8]
                    .try_into()
                    .expect("generated block-v2 layout"),
            ),
            sector_count: u32::from_le_bytes(
                buf[OFF_REQUEST_SECTOR_COUNT..OFF_REQUEST_SECTOR_COUNT + 4]
                    .try_into()
                    .expect("generated block-v2 layout"),
            ),
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 4]
                .try_into()
                .expect("generated block-v2 layout"),
            padding: buf[OFF_REQUEST_PADDING..OFF_REQUEST_PADDING + 32]
                .try_into()
                .expect("generated block-v2 layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 2]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OP] = self.op;
        buf[OFF_REQUEST_FLAGS] = self.flags;
        buf[OFF_REQUEST_LBA..OFF_REQUEST_LBA + 8].copy_from_slice(&self.lba.to_le_bytes());
        buf[OFF_REQUEST_SECTOR_COUNT..OFF_REQUEST_SECTOR_COUNT + 4]
            .copy_from_slice(&self.sector_count.to_le_bytes());
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 4].copy_from_slice(&self.reserved);
        buf[OFF_REQUEST_PADDING..OFF_REQUEST_PADDING + 32].copy_from_slice(&self.padding);
        buf
    }
}

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_OP: usize = 6;
pub const OFF_REPLY_RESERVED: usize = 7;
pub const OFF_REPLY_SECTORS_DONE: usize = 8;
pub const OFF_REPLY_DEVICE_STATUS: usize = 12;
pub const OFF_REPLY_DETAIL: usize = 16;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireBlockReply {
    pub magic: u32,
    pub version: u16,
    pub op: u8,
    pub reserved: [u8; 1],
    pub sectors_done: u32,
    pub device_status: u32,
    pub detail: u64,
}

impl WireBlockReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated block-v2 layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 2]
                    .try_into()
                    .expect("generated block-v2 layout"),
            ),
            op: buf[OFF_REPLY_OP],
            reserved: buf[OFF_REPLY_RESERVED..OFF_REPLY_RESERVED + 1]
                .try_into()
                .expect("generated block-v2 layout"),
            sectors_done: u32::from_le_bytes(
                buf[OFF_REPLY_SECTORS_DONE..OFF_REPLY_SECTORS_DONE + 4]
                    .try_into()
                    .expect("generated block-v2 layout"),
            ),
            device_status: u32::from_le_bytes(
                buf[OFF_REPLY_DEVICE_STATUS..OFF_REPLY_DEVICE_STATUS + 4]
                    .try_into()
                    .expect("generated block-v2 layout"),
            ),
            detail: u64::from_le_bytes(
                buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 8]
                    .try_into()
                    .expect("generated block-v2 layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 2].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_OP] = self.op;
        buf[OFF_REPLY_RESERVED..OFF_REPLY_RESERVED + 1].copy_from_slice(&self.reserved);
        buf[OFF_REPLY_SECTORS_DONE..OFF_REPLY_SECTORS_DONE + 4]
            .copy_from_slice(&self.sectors_done.to_le_bytes());
        buf[OFF_REPLY_DEVICE_STATUS..OFF_REPLY_DEVICE_STATUS + 4]
            .copy_from_slice(&self.device_status.to_le_bytes());
        buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 8].copy_from_slice(&self.detail.to_le_bytes());
        buf
    }
}
