// @generated by contracts/capability-transfer/v1/gen_rust.zt; do not edit.
// Source contract: contracts/capability-transfer/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const FABRIC_REQUEST_MAGIC: u32 = 1380075091;
pub const CAPABILITY_TRANSFER_MAGIC: u32 = 1346454355;
pub const REQUEST_LEN: usize = 64;
pub const TRANSFER_LEN: usize = 64;
pub const MAX_ROUTE_NAME_BYTES: usize = 32;
pub const OBJECT_KIND_ENDPOINT: u32 = 1;
pub const OBJECT_KIND_SHARED_BUFFER: u32 = 2;
pub const OBJECT_KIND_SHARED_BUFFER_LOAN: u32 = 3;
pub const OBJECT_KIND_SUPERVISION: u32 = 4;
pub const FLAG_RETAIN_TRANSFER: u32 = 1;
pub const KNOWN_FLAGS: u32 = 1;
pub const DIRECTION_PUBLISH: u32 = 1;
pub const DIRECTION_SUBSCRIBE: u32 = 2;
pub const DIRECTION_CLIENT: u32 = 3;
pub const DIRECTION_SERVER: u32 = 4;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_FLAGS: usize = 8;
pub const OFF_REQUEST_DIRECTION: usize = 12;
pub const OFF_REQUEST_TYPE_IDENTITY: usize = 16;
pub const OFF_REQUEST_ROUTE_NAME_LEN: usize = 24;
pub const OFF_REQUEST_ROUTE_NAME: usize = 28;
pub const OFF_REQUEST_RESERVED: usize = 60;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireFabricRequest {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub direction: u32,
    pub type_identity: u64,
    pub route_name_len: u32,
    pub route_name: [u8; 32],
    pub reserved: [u8; 4],
}

impl WireFabricRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            direction: u32::from_le_bytes(
                buf[OFF_REQUEST_DIRECTION..OFF_REQUEST_DIRECTION + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_REQUEST_TYPE_IDENTITY..OFF_REQUEST_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            route_name_len: u32::from_le_bytes(
                buf[OFF_REQUEST_ROUTE_NAME_LEN..OFF_REQUEST_ROUTE_NAME_LEN + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            route_name: buf[OFF_REQUEST_ROUTE_NAME..OFF_REQUEST_ROUTE_NAME + 32]
                .try_into()
                .expect("generated capability-transfer layout"),
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 4]
                .try_into()
                .expect("generated capability-transfer layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_REQUEST_DIRECTION..OFF_REQUEST_DIRECTION + 4]
            .copy_from_slice(&self.direction.to_le_bytes());
        buf[OFF_REQUEST_TYPE_IDENTITY..OFF_REQUEST_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_REQUEST_ROUTE_NAME_LEN..OFF_REQUEST_ROUTE_NAME_LEN + 4]
            .copy_from_slice(&self.route_name_len.to_le_bytes());
        buf[OFF_REQUEST_ROUTE_NAME..OFF_REQUEST_ROUTE_NAME + 32].copy_from_slice(&self.route_name);
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 4].copy_from_slice(&self.reserved);
        buf
    }
}

pub const OFF_TRANSFER_MAGIC: usize = 0;
pub const OFF_TRANSFER_VERSION: usize = 4;
pub const OFF_TRANSFER_STATUS: usize = 8;
pub const OFF_TRANSFER_FLAGS: usize = 12;
pub const OFF_TRANSFER_OBJECT_KIND: usize = 16;
pub const OFF_TRANSFER_DIRECTION: usize = 20;
pub const OFF_TRANSFER_RIGHTS_MASK: usize = 24;
pub const OFF_TRANSFER_ROUTE_IDENTITY: usize = 32;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireCapabilityTransfer {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub flags: u32,
    pub object_kind: u32,
    pub direction: u32,
    pub rights_mask: u64,
    pub route_identity: [u8; 32],
}

impl WireCapabilityTransfer {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < TRANSFER_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_TRANSFER_MAGIC..OFF_TRANSFER_MAGIC + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_TRANSFER_VERSION..OFF_TRANSFER_VERSION + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_TRANSFER_STATUS..OFF_TRANSFER_STATUS + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_TRANSFER_FLAGS..OFF_TRANSFER_FLAGS + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            object_kind: u32::from_le_bytes(
                buf[OFF_TRANSFER_OBJECT_KIND..OFF_TRANSFER_OBJECT_KIND + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            direction: u32::from_le_bytes(
                buf[OFF_TRANSFER_DIRECTION..OFF_TRANSFER_DIRECTION + 4]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            rights_mask: u64::from_le_bytes(
                buf[OFF_TRANSFER_RIGHTS_MASK..OFF_TRANSFER_RIGHTS_MASK + 8]
                    .try_into()
                    .expect("generated capability-transfer layout"),
            ),
            route_identity: buf[OFF_TRANSFER_ROUTE_IDENTITY..OFF_TRANSFER_ROUTE_IDENTITY + 32]
                .try_into()
                .expect("generated capability-transfer layout"),
        })
    }

    pub fn encode(self) -> [u8; TRANSFER_LEN] {
        let mut buf = [0u8; TRANSFER_LEN];
        buf[OFF_TRANSFER_MAGIC..OFF_TRANSFER_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_TRANSFER_VERSION..OFF_TRANSFER_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_TRANSFER_STATUS..OFF_TRANSFER_STATUS + 4]
            .copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_TRANSFER_FLAGS..OFF_TRANSFER_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_TRANSFER_OBJECT_KIND..OFF_TRANSFER_OBJECT_KIND + 4]
            .copy_from_slice(&self.object_kind.to_le_bytes());
        buf[OFF_TRANSFER_DIRECTION..OFF_TRANSFER_DIRECTION + 4]
            .copy_from_slice(&self.direction.to_le_bytes());
        buf[OFF_TRANSFER_RIGHTS_MASK..OFF_TRANSFER_RIGHTS_MASK + 8]
            .copy_from_slice(&self.rights_mask.to_le_bytes());
        buf[OFF_TRANSFER_ROUTE_IDENTITY..OFF_TRANSFER_ROUTE_IDENTITY + 32]
            .copy_from_slice(&self.route_identity);
        buf
    }
}
