// @generated by contracts/entropy-service/v1/gen_rust.zt; do not edit.
// Source contract: contracts/entropy-service/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const ENTROPY_SERVICE_MAGIC: u32 = 1381256773;
pub const REQUEST_LEN: usize = 16;
pub const REPLY_LEN: usize = 48;
pub const MAX_DRAW: usize = 32;
pub const OP_DRAW: u32 = 1;
pub const OP_CLOSE: u32 = 2;

pub const STATUS_OK: i32 = 0;
pub const STATUS_DENIED: i32 = -1;
pub const STATUS_MALFORMED: i32 = -2;
pub const STATUS_EXHAUSTED: i32 = -3;
pub const STATUS_UNAVAILABLE: i32 = -4;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OP: usize = 8;
pub const OFF_REQUEST_LENGTH: usize = 12;

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_LENGTH: usize = 12;
pub const OFF_REPLY_BYTES: usize = 16;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireEntropyServiceRequest {
    pub magic: u32,
    pub version: u32,
    pub op: u32,
    pub length: u32,
}

impl WireEntropyServiceRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated entropy_service layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated entropy_service layout"),
            ),
            op: u32::from_le_bytes(
                buf[OFF_REQUEST_OP..OFF_REQUEST_OP + 4]
                    .try_into()
                    .expect("generated entropy_service layout"),
            ),
            length: u32::from_le_bytes(
                buf[OFF_REQUEST_LENGTH..OFF_REQUEST_LENGTH + 4]
                    .try_into()
                    .expect("generated entropy_service layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OP..OFF_REQUEST_OP + 4].copy_from_slice(&self.op.to_le_bytes());
        buf[OFF_REQUEST_LENGTH..OFF_REQUEST_LENGTH + 4].copy_from_slice(&self.length.to_le_bytes());
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireEntropyServiceReply {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub length: u32,
    pub bytes: [u8; 32],
}

impl WireEntropyServiceReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated entropy_service layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4]
                    .try_into()
                    .expect("generated entropy_service layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated entropy_service layout"),
            ),
            length: u32::from_le_bytes(
                buf[OFF_REPLY_LENGTH..OFF_REPLY_LENGTH + 4]
                    .try_into()
                    .expect("generated entropy_service layout"),
            ),
            bytes: buf[OFF_REPLY_BYTES..OFF_REPLY_BYTES + 32]
                .try_into()
                .expect("generated entropy_service layout"),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_LENGTH..OFF_REPLY_LENGTH + 4].copy_from_slice(&self.length.to_le_bytes());
        buf[OFF_REPLY_BYTES..OFF_REPLY_BYTES + 32].copy_from_slice(&self.bytes);
        buf
    }
}
