// @generated by contracts/fabric-qos/v1/gen_rust.zt; do not edit.
// Source contract: contracts/fabric-qos/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const QOS_EVENT_MAGIC: u32 = 1397702993;
pub const QOS_EVENT_LEN: usize = 64;
pub const EVENT_MATCHED: u32 = 1;
pub const EVENT_UNMATCHED: u32 = 2;
pub const EVENT_INCOMPATIBLE_QOS: u32 = 3;
pub const EVENT_LIFESPAN_EXPIRED: u32 = 4;
pub const EVENT_RETRY_EXHAUSTED: u32 = 5;
pub const EVENT_DEADLINE_MISSED: u32 = 6;
pub const EVENT_LIVELINESS_LOST: u32 = 7;
pub const EVENT_PEER_DEAD: u32 = 8;

pub const OFF_QOS_MAGIC: usize = 0;
pub const OFF_QOS_VERSION: usize = 4;
pub const OFF_QOS_EVENT: usize = 8;
pub const OFF_QOS_FLAGS: usize = 12;
pub const OFF_QOS_SEQUENCE: usize = 16;
pub const OFF_QOS_VALUE: usize = 24;
pub const OFF_QOS_TIMESTAMP_NS: usize = 32;
pub const OFF_QOS_TYPE_IDENTITY: usize = 40;
pub const OFF_QOS_RESERVED: usize = 48;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireQosEvent {
    pub magic: u32,
    pub version: u32,
    pub event: u32,
    pub flags: u32,
    pub sequence: u64,
    pub value: u64,
    pub timestamp_ns: u64,
    pub type_identity: u64,
    pub reserved: [u8; 16],
}

impl WireQosEvent {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < QOS_EVENT_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_QOS_MAGIC..OFF_QOS_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_QOS_VERSION..OFF_QOS_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            event: u32::from_le_bytes(
                buf[OFF_QOS_EVENT..OFF_QOS_EVENT + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_QOS_FLAGS..OFF_QOS_FLAGS + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            sequence: u64::from_le_bytes(
                buf[OFF_QOS_SEQUENCE..OFF_QOS_SEQUENCE + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            value: u64::from_le_bytes(
                buf[OFF_QOS_VALUE..OFF_QOS_VALUE + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            timestamp_ns: u64::from_le_bytes(
                buf[OFF_QOS_TIMESTAMP_NS..OFF_QOS_TIMESTAMP_NS + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_QOS_TYPE_IDENTITY..OFF_QOS_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            reserved: buf[OFF_QOS_RESERVED..OFF_QOS_RESERVED + 16]
                .try_into()
                .expect("generated fabric-stream layout"),
        })
    }

    pub fn encode(self) -> [u8; QOS_EVENT_LEN] {
        let mut buf = [0u8; QOS_EVENT_LEN];
        buf[OFF_QOS_MAGIC..OFF_QOS_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_QOS_VERSION..OFF_QOS_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_QOS_EVENT..OFF_QOS_EVENT + 4].copy_from_slice(&self.event.to_le_bytes());
        buf[OFF_QOS_FLAGS..OFF_QOS_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_QOS_SEQUENCE..OFF_QOS_SEQUENCE + 8].copy_from_slice(&self.sequence.to_le_bytes());
        buf[OFF_QOS_VALUE..OFF_QOS_VALUE + 8].copy_from_slice(&self.value.to_le_bytes());
        buf[OFF_QOS_TIMESTAMP_NS..OFF_QOS_TIMESTAMP_NS + 8]
            .copy_from_slice(&self.timestamp_ns.to_le_bytes());
        buf[OFF_QOS_TYPE_IDENTITY..OFF_QOS_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_QOS_RESERVED..OFF_QOS_RESERVED + 16].copy_from_slice(&self.reserved);
        buf
    }
}
