// @generated by contracts/fabric-time/v1/gen_rust.zt; do not edit.
// Source contract: contracts/fabric-time/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const TIME_ADVANCE_MAGIC: u32 = 1296650836;
pub const TIME_ADVANCE_LEN: usize = 64;

pub const OFF_TIME_MAGIC: usize = 0;
pub const OFF_TIME_VERSION: usize = 4;
pub const OFF_TIME_FLAGS: usize = 8;
pub const OFF_TIME_RESERVED0: usize = 12;
pub const OFF_TIME_NOW_NS: usize = 16;
pub const OFF_TIME_RESERVED: usize = 24;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireTimeAdvance {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub reserved0: u32,
    pub now_ns: u64,
    pub reserved: [u8; 40],
}

impl WireTimeAdvance {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < TIME_ADVANCE_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_TIME_MAGIC..OFF_TIME_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_TIME_VERSION..OFF_TIME_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_TIME_FLAGS..OFF_TIME_FLAGS + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            reserved0: u32::from_le_bytes(
                buf[OFF_TIME_RESERVED0..OFF_TIME_RESERVED0 + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            now_ns: u64::from_le_bytes(
                buf[OFF_TIME_NOW_NS..OFF_TIME_NOW_NS + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            reserved: buf[OFF_TIME_RESERVED..OFF_TIME_RESERVED + 40]
                .try_into()
                .expect("generated fabric-stream layout"),
        })
    }

    pub fn encode(self) -> [u8; TIME_ADVANCE_LEN] {
        let mut buf = [0u8; TIME_ADVANCE_LEN];
        buf[OFF_TIME_MAGIC..OFF_TIME_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_TIME_VERSION..OFF_TIME_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_TIME_FLAGS..OFF_TIME_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_TIME_RESERVED0..OFF_TIME_RESERVED0 + 4]
            .copy_from_slice(&self.reserved0.to_le_bytes());
        buf[OFF_TIME_NOW_NS..OFF_TIME_NOW_NS + 8].copy_from_slice(&self.now_ns.to_le_bytes());
        buf[OFF_TIME_RESERVED..OFF_TIME_RESERVED + 40].copy_from_slice(&self.reserved);
        buf
    }
}
