// @generated by contracts/fabric-trace/v1/gen_rust.zt; do not edit.
// Source contract: contracts/fabric-trace/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const TRACE_MAGIC: u32 = 1163084372;
pub const TRACE_RECORD_LEN: usize = 64;

/// Trace families. One record layout carries all of them; `kind` selects
/// which evidence class a record belongs to.
pub const KIND_SCHEMA: u32 = 1;
pub const KIND_ROUTE: u32 = 2;
pub const KIND_QOS: u32 = 3;
pub const KIND_CALL: u32 = 4;
pub const KIND_OPERATION: u32 = 5;
pub const KIND_VISIBILITY: u32 = 6;
pub const KIND_INTERPOSITION: u32 = 7;
pub const KIND_DENIAL: u32 = 8;
pub const KIND_FAULT: u32 = 9;
pub const KIND_RESOURCE: u32 = 10;
pub const MAX_KIND: u32 = 10;

/// Which count a `resource` record carries. A bare number is not evidence
/// unless the reader knows what was counted.
pub const RESOURCE_FRAMES: u32 = 1;
pub const RESOURCE_OPERATIONS: u32 = 2;
pub const RESOURCE_CALLS: u32 = 3;
pub const RESOURCE_SINK_DROPPED: u32 = 4;
pub const RESOURCE_ROLES: u32 = 5;
pub const RESOURCE_BUFFERS: u32 = 6;
pub const RESOURCE_RETRIES: u32 = 7;
pub const RESOURCE_RETAINED: u32 = 8;
pub const RESOURCE_QUEUE: u32 = 9;
pub const RESOURCE_HISTORY: u32 = 10;
pub const RESOURCE_EVENT: u32 = 11;
pub const RESOURCE_LOAN: u32 = 12;
pub const RESOURCE_COMPLETE: u32 = 13;
pub const MAX_RESOURCE_COUNTER: u32 = 13;

/// What a `visibility` or `interposition` record's `event` names. Both
/// families are graph-shaped -- an edge, no outcome, and an event saying
/// what was observed or traversed over it -- so the event is the only
/// field carrying meaning, and a bare nonzero number would not be
/// evidence.
pub const GRAPH_VIEW_ANSWERED: u32 = 1;
pub const GRAPH_HOP_TRAVERSED: u32 = 2;
pub const MAX_GRAPH_EVENT: u32 = 2;

/// The declared total tie order at one simulated instant: data, then
/// acknowledgement, then peer death, then the clock advance that closes it.
pub const ORDER_DATA: u32 = 1;
pub const ORDER_ACK: u32 = 2;
pub const ORDER_PEER_DEATH: u32 = 3;
pub const ORDER_TIME: u32 = 4;
pub const MAX_ORDER_CLASS: u32 = 4;

pub const FLAG_TERMINAL: u32 = 1;
pub const FLAG_DROPPED: u32 = 2;
pub const KNOWN_FLAGS: u32 = 3;

/// Sink overflow discipline, fixed by the generation profile.
pub const OVERFLOW_SATURATE: u32 = 1;
pub const MAX_OVERFLOW: u32 = 1;

/// Structural ceiling on a declared sink capacity, and the slots held
/// back so a saturated sink can still record that the trace ended.
pub const MAX_TRACE_DEPTH: usize = 64;
pub const TERMINAL_RESERVE: usize = 2;

pub const OFF_TRACE_MAGIC: usize = 0;
pub const OFF_TRACE_VERSION: usize = 4;
pub const OFF_TRACE_KIND: usize = 8;
pub const OFF_TRACE_FLAGS: usize = 12;
pub const OFF_TRACE_ROUTE_IDENTITY: usize = 16;
pub const OFF_TRACE_CORRELATION: usize = 24;
pub const OFF_TRACE_SEQUENCE: usize = 32;
pub const OFF_TRACE_NOW_NS: usize = 40;
pub const OFF_TRACE_STATUS: usize = 48;
pub const OFF_TRACE_EVENT: usize = 52;
pub const OFF_TRACE_HIGH_WATER: usize = 56;
pub const OFF_TRACE_ORDER_CLASS: usize = 60;
pub const OFF_TRACE_RESERVED: usize = 61;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireTraceRecord {
    pub magic: u32,
    pub version: u32,
    pub kind: u32,
    pub flags: u32,
    pub route_identity: u64,
    pub correlation: u64,
    pub sequence: u64,
    pub now_ns: u64,
    pub status: i32,
    pub event: u32,
    pub high_water: u32,
    pub order_class: u8,
    pub reserved: [u8; 3],
}

impl WireTraceRecord {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < TRACE_RECORD_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_TRACE_MAGIC..OFF_TRACE_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_TRACE_VERSION..OFF_TRACE_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            kind: u32::from_le_bytes(
                buf[OFF_TRACE_KIND..OFF_TRACE_KIND + 4]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_TRACE_FLAGS..OFF_TRACE_FLAGS + 4]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            route_identity: u64::from_le_bytes(
                buf[OFF_TRACE_ROUTE_IDENTITY..OFF_TRACE_ROUTE_IDENTITY + 8]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            correlation: u64::from_le_bytes(
                buf[OFF_TRACE_CORRELATION..OFF_TRACE_CORRELATION + 8]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            sequence: u64::from_le_bytes(
                buf[OFF_TRACE_SEQUENCE..OFF_TRACE_SEQUENCE + 8]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            now_ns: u64::from_le_bytes(
                buf[OFF_TRACE_NOW_NS..OFF_TRACE_NOW_NS + 8]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_TRACE_STATUS..OFF_TRACE_STATUS + 4]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            event: u32::from_le_bytes(
                buf[OFF_TRACE_EVENT..OFF_TRACE_EVENT + 4]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            high_water: u32::from_le_bytes(
                buf[OFF_TRACE_HIGH_WATER..OFF_TRACE_HIGH_WATER + 4]
                    .try_into()
                    .expect("generated fabric-trace layout"),
            ),
            order_class: buf[OFF_TRACE_ORDER_CLASS],
            reserved: buf[OFF_TRACE_RESERVED..OFF_TRACE_RESERVED + 3]
                .try_into()
                .expect("generated fabric-trace layout"),
        })
    }

    pub fn encode(self) -> [u8; TRACE_RECORD_LEN] {
        let mut buf = [0u8; TRACE_RECORD_LEN];
        buf[OFF_TRACE_MAGIC..OFF_TRACE_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_TRACE_VERSION..OFF_TRACE_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_TRACE_KIND..OFF_TRACE_KIND + 4].copy_from_slice(&self.kind.to_le_bytes());
        buf[OFF_TRACE_FLAGS..OFF_TRACE_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_TRACE_ROUTE_IDENTITY..OFF_TRACE_ROUTE_IDENTITY + 8]
            .copy_from_slice(&self.route_identity.to_le_bytes());
        buf[OFF_TRACE_CORRELATION..OFF_TRACE_CORRELATION + 8]
            .copy_from_slice(&self.correlation.to_le_bytes());
        buf[OFF_TRACE_SEQUENCE..OFF_TRACE_SEQUENCE + 8]
            .copy_from_slice(&self.sequence.to_le_bytes());
        buf[OFF_TRACE_NOW_NS..OFF_TRACE_NOW_NS + 8].copy_from_slice(&self.now_ns.to_le_bytes());
        buf[OFF_TRACE_STATUS..OFF_TRACE_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_TRACE_EVENT..OFF_TRACE_EVENT + 4].copy_from_slice(&self.event.to_le_bytes());
        buf[OFF_TRACE_HIGH_WATER..OFF_TRACE_HIGH_WATER + 4]
            .copy_from_slice(&self.high_water.to_le_bytes());
        buf[OFF_TRACE_ORDER_CLASS] = self.order_class;
        buf[OFF_TRACE_RESERVED..OFF_TRACE_RESERVED + 3].copy_from_slice(&self.reserved);
        buf
    }
}
