// @generated by contracts/fabric-call/v1/gen_rust.zt; do not edit.
// Source contract: contracts/fabric-call/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const CALL_MAGIC: u32 = 1280065875;
pub const CALL_TIME_MAGIC: u32 = 1296253251;
pub const CALL_LEN: usize = 64;
pub const CALL_TIME_LEN: usize = 64;
pub const INLINE_BYTES: usize = 8;
pub const KIND_REQUEST: u32 = 1;
pub const KIND_REPLY: u32 = 2;
pub const KIND_CANCEL: u32 = 3;
pub const KIND_TERMINAL: u32 = 4;
pub const FLAG_NON_IDEMPOTENT: u32 = 1;
pub const FLAG_SHARED_PAYLOAD: u32 = 2;
pub const KNOWN_FLAGS: u32 = 3;
pub const STATUS_SUCCESS: i32 = 0;
pub const STATUS_REJECTED: i32 = 1;
pub const STATUS_TIMEOUT: i32 = 2;
pub const STATUS_CANCELLED: i32 = 3;
pub const STATUS_RETRY_EXHAUSTED: i32 = 4;
pub const STATUS_MALFORMED_REPLY: i32 = 5;
pub const STATUS_PEER_DEAD: i32 = 6;
pub const STATUS_DUPLICATE: i32 = 7;
pub const STATUS_STALE: i32 = 8;

pub const OFF_CALL_MAGIC: usize = 0;
pub const OFF_CALL_VERSION: usize = 4;
pub const OFF_CALL_KIND: usize = 8;
pub const OFF_CALL_FLAGS: usize = 12;
pub const OFF_CALL_SESSION: usize = 16;
pub const OFF_CALL_REQUEST_ID: usize = 24;
pub const OFF_CALL_TYPE_IDENTITY: usize = 32;
pub const OFF_CALL_STATUS: usize = 40;
pub const OFF_CALL_PAYLOAD_LEN: usize = 44;
pub const OFF_CALL_PAYLOAD: usize = 48;

pub const OFF_CALL_TIME_MAGIC: usize = 0;
pub const OFF_CALL_TIME_VERSION: usize = 4;
pub const OFF_CALL_TIME_FLAGS: usize = 8;
pub const OFF_CALL_TIME_RESERVED0: usize = 12;
pub const OFF_CALL_TIME_NOW_NS: usize = 16;
pub const OFF_CALL_TIME_RESERVED: usize = 24;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireCallEnvelope {
    pub magic: u32,
    pub version: u32,
    pub kind: u32,
    pub flags: u32,
    pub session: u64,
    pub request_id: u64,
    pub type_identity: u64,
    pub status: i32,
    pub payload_len: u32,
    pub payload: [u8; 16],
}

impl WireCallEnvelope {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < CALL_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_CALL_MAGIC..OFF_CALL_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_CALL_VERSION..OFF_CALL_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            kind: u32::from_le_bytes(
                buf[OFF_CALL_KIND..OFF_CALL_KIND + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_CALL_FLAGS..OFF_CALL_FLAGS + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            session: u64::from_le_bytes(
                buf[OFF_CALL_SESSION..OFF_CALL_SESSION + 8]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            request_id: u64::from_le_bytes(
                buf[OFF_CALL_REQUEST_ID..OFF_CALL_REQUEST_ID + 8]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_CALL_TYPE_IDENTITY..OFF_CALL_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_CALL_STATUS..OFF_CALL_STATUS + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            payload_len: u32::from_le_bytes(
                buf[OFF_CALL_PAYLOAD_LEN..OFF_CALL_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            payload: buf[OFF_CALL_PAYLOAD..OFF_CALL_PAYLOAD + 16]
                .try_into()
                .expect("generated fabric-call layout"),
        })
    }

    pub fn encode(self) -> [u8; CALL_LEN] {
        let mut buf = [0u8; CALL_LEN];
        buf[OFF_CALL_MAGIC..OFF_CALL_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_CALL_VERSION..OFF_CALL_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_CALL_KIND..OFF_CALL_KIND + 4].copy_from_slice(&self.kind.to_le_bytes());
        buf[OFF_CALL_FLAGS..OFF_CALL_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_CALL_SESSION..OFF_CALL_SESSION + 8].copy_from_slice(&self.session.to_le_bytes());
        buf[OFF_CALL_REQUEST_ID..OFF_CALL_REQUEST_ID + 8]
            .copy_from_slice(&self.request_id.to_le_bytes());
        buf[OFF_CALL_TYPE_IDENTITY..OFF_CALL_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_CALL_STATUS..OFF_CALL_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_CALL_PAYLOAD_LEN..OFF_CALL_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_CALL_PAYLOAD..OFF_CALL_PAYLOAD + 16].copy_from_slice(&self.payload);
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireCallTimeAdvance {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub reserved0: u32,
    pub now_ns: u64,
    pub reserved: [u8; 40],
}

impl WireCallTimeAdvance {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < CALL_TIME_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_CALL_TIME_MAGIC..OFF_CALL_TIME_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_CALL_TIME_VERSION..OFF_CALL_TIME_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_CALL_TIME_FLAGS..OFF_CALL_TIME_FLAGS + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            reserved0: u32::from_le_bytes(
                buf[OFF_CALL_TIME_RESERVED0..OFF_CALL_TIME_RESERVED0 + 4]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            now_ns: u64::from_le_bytes(
                buf[OFF_CALL_TIME_NOW_NS..OFF_CALL_TIME_NOW_NS + 8]
                    .try_into()
                    .expect("generated fabric-call layout"),
            ),
            reserved: buf[OFF_CALL_TIME_RESERVED..OFF_CALL_TIME_RESERVED + 40]
                .try_into()
                .expect("generated fabric-call layout"),
        })
    }

    pub fn encode(self) -> [u8; CALL_TIME_LEN] {
        let mut buf = [0u8; CALL_TIME_LEN];
        buf[OFF_CALL_TIME_MAGIC..OFF_CALL_TIME_MAGIC + 4]
            .copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_CALL_TIME_VERSION..OFF_CALL_TIME_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_CALL_TIME_FLAGS..OFF_CALL_TIME_FLAGS + 4]
            .copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_CALL_TIME_RESERVED0..OFF_CALL_TIME_RESERVED0 + 4]
            .copy_from_slice(&self.reserved0.to_le_bytes());
        buf[OFF_CALL_TIME_NOW_NS..OFF_CALL_TIME_NOW_NS + 8]
            .copy_from_slice(&self.now_ns.to_le_bytes());
        buf[OFF_CALL_TIME_RESERVED..OFF_CALL_TIME_RESERVED + 40].copy_from_slice(&self.reserved);
        buf
    }
}
