// @generated by contracts/fabric-stream/v2/gen_rust.zt; do not edit.
// Source contract: contracts/fabric-stream/v2/schema.zt

pub const FORMAT_VERSION: u32 = 2;
pub const RING_HEADER_LEN: usize = 64;
pub const RING_SLOT_LEN: usize = 64;
pub const MAX_INLINE_BYTES: usize = 32;
pub const MIN_RING_SLOTS: usize = 2;
pub const MAX_RING_SLOTS: usize = 256;
pub const RING_MAGIC: u32 = 1196250195;
pub const SLOT_MAGIC: u32 = 1414743379;
pub const PRODUCER_ACTIVE: u32 = 0;
pub const PRODUCER_FINISHED: u32 = 1;
pub const PRODUCER_DEAD: u32 = 2;
pub const SLOT_EMPTY: u32 = 0;
pub const SLOT_CLAIMED: u32 = 1;
pub const SLOT_READY: u32 = 2;
pub const BADGE_SAMPLE_READY: u64 = 1;
pub const BADGE_CREDIT_RETURNED: u64 = 2;
pub const BADGE_PRODUCER_ENDED: u64 = 4;
pub const KNOWN_BADGE_BITS: u64 = 7;
pub const FLAG_LAST: u32 = 1;
pub const KNOWN_SLOT_FLAGS: u32 = 1;

pub const OFF_HEADER_MAGIC: usize = 0;
pub const OFF_HEADER_VERSION: usize = 4;
pub const OFF_HEADER_SLOT_COUNT: usize = 8;
pub const OFF_HEADER_SLOT_LEN: usize = 12;
pub const OFF_HEADER_HEAD: usize = 16;
pub const OFF_HEADER_TAIL: usize = 24;
pub const OFF_HEADER_TYPE_IDENTITY: usize = 32;
pub const OFF_HEADER_PRODUCER_STATE: usize = 40;
pub const OFF_HEADER_LOST: usize = 44;
pub const OFF_HEADER_RESERVED: usize = 48;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireRingHeader {
    pub magic: u32,
    pub version: u32,
    pub slot_count: u32,
    pub slot_len: u32,
    pub head: u64,
    pub tail: u64,
    pub type_identity: u64,
    pub producer_state: u32,
    pub lost: u32,
    pub reserved: [u8; 16],
}

impl WireRingHeader {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < RING_HEADER_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_HEADER_MAGIC..OFF_HEADER_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_HEADER_VERSION..OFF_HEADER_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            slot_count: u32::from_le_bytes(
                buf[OFF_HEADER_SLOT_COUNT..OFF_HEADER_SLOT_COUNT + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            slot_len: u32::from_le_bytes(
                buf[OFF_HEADER_SLOT_LEN..OFF_HEADER_SLOT_LEN + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            head: u64::from_le_bytes(
                buf[OFF_HEADER_HEAD..OFF_HEADER_HEAD + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            tail: u64::from_le_bytes(
                buf[OFF_HEADER_TAIL..OFF_HEADER_TAIL + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_HEADER_TYPE_IDENTITY..OFF_HEADER_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            producer_state: u32::from_le_bytes(
                buf[OFF_HEADER_PRODUCER_STATE..OFF_HEADER_PRODUCER_STATE + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            lost: u32::from_le_bytes(
                buf[OFF_HEADER_LOST..OFF_HEADER_LOST + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            reserved: buf[OFF_HEADER_RESERVED..OFF_HEADER_RESERVED + 16]
                .try_into()
                .expect("generated fabric-stream layout"),
        })
    }

    pub fn encode(self) -> [u8; RING_HEADER_LEN] {
        let mut buf = [0u8; RING_HEADER_LEN];
        buf[OFF_HEADER_MAGIC..OFF_HEADER_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_HEADER_VERSION..OFF_HEADER_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_HEADER_SLOT_COUNT..OFF_HEADER_SLOT_COUNT + 4]
            .copy_from_slice(&self.slot_count.to_le_bytes());
        buf[OFF_HEADER_SLOT_LEN..OFF_HEADER_SLOT_LEN + 4]
            .copy_from_slice(&self.slot_len.to_le_bytes());
        buf[OFF_HEADER_HEAD..OFF_HEADER_HEAD + 8].copy_from_slice(&self.head.to_le_bytes());
        buf[OFF_HEADER_TAIL..OFF_HEADER_TAIL + 8].copy_from_slice(&self.tail.to_le_bytes());
        buf[OFF_HEADER_TYPE_IDENTITY..OFF_HEADER_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_HEADER_PRODUCER_STATE..OFF_HEADER_PRODUCER_STATE + 4]
            .copy_from_slice(&self.producer_state.to_le_bytes());
        buf[OFF_HEADER_LOST..OFF_HEADER_LOST + 4].copy_from_slice(&self.lost.to_le_bytes());
        buf[OFF_HEADER_RESERVED..OFF_HEADER_RESERVED + 16].copy_from_slice(&self.reserved);
        buf
    }
}

pub const OFF_SLOT_MAGIC: usize = 0;
pub const OFF_SLOT_STATE: usize = 4;
pub const OFF_SLOT_FLAGS: usize = 8;
pub const OFF_SLOT_PAYLOAD_LEN: usize = 12;
pub const OFF_SLOT_SEQUENCE: usize = 16;
pub const OFF_SLOT_TYPE_IDENTITY: usize = 24;
pub const OFF_SLOT_PAYLOAD: usize = 32;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireRingSlot {
    pub magic: u32,
    pub state: u32,
    pub flags: u32,
    pub payload_len: u32,
    pub sequence: u64,
    pub type_identity: u64,
    pub payload: [u8; 32],
}

impl WireRingSlot {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < RING_SLOT_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_SLOT_MAGIC..OFF_SLOT_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            state: u32::from_le_bytes(
                buf[OFF_SLOT_STATE..OFF_SLOT_STATE + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_SLOT_FLAGS..OFF_SLOT_FLAGS + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            payload_len: u32::from_le_bytes(
                buf[OFF_SLOT_PAYLOAD_LEN..OFF_SLOT_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            sequence: u64::from_le_bytes(
                buf[OFF_SLOT_SEQUENCE..OFF_SLOT_SEQUENCE + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_SLOT_TYPE_IDENTITY..OFF_SLOT_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            payload: buf[OFF_SLOT_PAYLOAD..OFF_SLOT_PAYLOAD + 32]
                .try_into()
                .expect("generated fabric-stream layout"),
        })
    }

    pub fn encode(self) -> [u8; RING_SLOT_LEN] {
        let mut buf = [0u8; RING_SLOT_LEN];
        buf[OFF_SLOT_MAGIC..OFF_SLOT_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_SLOT_STATE..OFF_SLOT_STATE + 4].copy_from_slice(&self.state.to_le_bytes());
        buf[OFF_SLOT_FLAGS..OFF_SLOT_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_SLOT_PAYLOAD_LEN..OFF_SLOT_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_SLOT_SEQUENCE..OFF_SLOT_SEQUENCE + 8].copy_from_slice(&self.sequence.to_le_bytes());
        buf[OFF_SLOT_TYPE_IDENTITY..OFF_SLOT_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_SLOT_PAYLOAD..OFF_SLOT_PAYLOAD + 32].copy_from_slice(&self.payload);
        buf
    }
}
