// @generated by contracts/fabric-stream/v1/gen_rust.zt; do not edit.
// Source contract: contracts/fabric-stream/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const STREAM_SAMPLE_MAGIC: u32 = 1381258067;
pub const STREAM_ACK_MAGIC: u32 = 1262698835;
pub const STREAM_EVENT_MAGIC: u32 = 1414939987;
pub const SAMPLE_LEN: usize = 64;
pub const ACK_LEN: usize = 64;
pub const EVENT_LEN: usize = 64;
pub const MAX_INLINE_BYTES: usize = 32;
pub const FLAG_LAST: u32 = 1;
pub const KNOWN_SAMPLE_FLAGS: u32 = 1;
pub const KNOWN_ACK_FLAGS: u32 = 0;
pub const KNOWN_EVENT_FLAGS: u32 = 0;
pub const EVENT_SAMPLE_LOST: u32 = 1;
pub const EVENT_STREAM_END: u32 = 2;
pub const EVENT_SAMPLE_TAKEN: u32 = 3;

pub const OFF_SAMPLE_MAGIC: usize = 0;
pub const OFF_SAMPLE_VERSION: usize = 4;
pub const OFF_SAMPLE_FLAGS: usize = 8;
pub const OFF_SAMPLE_PAYLOAD_LEN: usize = 12;
pub const OFF_SAMPLE_SEQUENCE: usize = 16;
pub const OFF_SAMPLE_TYPE_IDENTITY: usize = 24;
pub const OFF_SAMPLE_PAYLOAD: usize = 32;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireStreamSample {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub payload_len: u32,
    pub sequence: u64,
    pub type_identity: u64,
    pub payload: [u8; 32],
}

impl WireStreamSample {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < SAMPLE_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_SAMPLE_MAGIC..OFF_SAMPLE_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_SAMPLE_VERSION..OFF_SAMPLE_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_SAMPLE_FLAGS..OFF_SAMPLE_FLAGS + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            payload_len: u32::from_le_bytes(
                buf[OFF_SAMPLE_PAYLOAD_LEN..OFF_SAMPLE_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            sequence: u64::from_le_bytes(
                buf[OFF_SAMPLE_SEQUENCE..OFF_SAMPLE_SEQUENCE + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_SAMPLE_TYPE_IDENTITY..OFF_SAMPLE_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            payload: buf[OFF_SAMPLE_PAYLOAD..OFF_SAMPLE_PAYLOAD + 32]
                .try_into()
                .expect("generated fabric-stream layout"),
        })
    }

    pub fn encode(self) -> [u8; SAMPLE_LEN] {
        let mut buf = [0u8; SAMPLE_LEN];
        buf[OFF_SAMPLE_MAGIC..OFF_SAMPLE_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_SAMPLE_VERSION..OFF_SAMPLE_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_SAMPLE_FLAGS..OFF_SAMPLE_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_SAMPLE_PAYLOAD_LEN..OFF_SAMPLE_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_SAMPLE_SEQUENCE..OFF_SAMPLE_SEQUENCE + 8]
            .copy_from_slice(&self.sequence.to_le_bytes());
        buf[OFF_SAMPLE_TYPE_IDENTITY..OFF_SAMPLE_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_SAMPLE_PAYLOAD..OFF_SAMPLE_PAYLOAD + 32].copy_from_slice(&self.payload);
        buf
    }
}

pub const OFF_ACK_MAGIC: usize = 0;
pub const OFF_ACK_VERSION: usize = 4;
pub const OFF_ACK_FLAGS: usize = 8;
pub const OFF_ACK_RESERVED0: usize = 12;
pub const OFF_ACK_SEQUENCE: usize = 16;
pub const OFF_ACK_TYPE_IDENTITY: usize = 24;
pub const OFF_ACK_RESERVED: usize = 32;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireStreamAck {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub reserved0: u32,
    pub sequence: u64,
    pub type_identity: u64,
    pub reserved: [u8; 32],
}

impl WireStreamAck {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < ACK_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_ACK_MAGIC..OFF_ACK_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_ACK_VERSION..OFF_ACK_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_ACK_FLAGS..OFF_ACK_FLAGS + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            reserved0: u32::from_le_bytes(
                buf[OFF_ACK_RESERVED0..OFF_ACK_RESERVED0 + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            sequence: u64::from_le_bytes(
                buf[OFF_ACK_SEQUENCE..OFF_ACK_SEQUENCE + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_ACK_TYPE_IDENTITY..OFF_ACK_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            reserved: buf[OFF_ACK_RESERVED..OFF_ACK_RESERVED + 32]
                .try_into()
                .expect("generated fabric-stream layout"),
        })
    }

    pub fn encode(self) -> [u8; ACK_LEN] {
        let mut buf = [0u8; ACK_LEN];
        buf[OFF_ACK_MAGIC..OFF_ACK_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_ACK_VERSION..OFF_ACK_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_ACK_FLAGS..OFF_ACK_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_ACK_RESERVED0..OFF_ACK_RESERVED0 + 4]
            .copy_from_slice(&self.reserved0.to_le_bytes());
        buf[OFF_ACK_SEQUENCE..OFF_ACK_SEQUENCE + 8].copy_from_slice(&self.sequence.to_le_bytes());
        buf[OFF_ACK_TYPE_IDENTITY..OFF_ACK_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_ACK_RESERVED..OFF_ACK_RESERVED + 32].copy_from_slice(&self.reserved);
        buf
    }
}

pub const OFF_EVENT_MAGIC: usize = 0;
pub const OFF_EVENT_VERSION: usize = 4;
pub const OFF_EVENT_EVENT: usize = 8;
pub const OFF_EVENT_FLAGS: usize = 12;
pub const OFF_EVENT_LOST: usize = 16;
pub const OFF_EVENT_SEQUENCE: usize = 24;
pub const OFF_EVENT_TYPE_IDENTITY: usize = 32;
pub const OFF_EVENT_RESERVED: usize = 40;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireStreamEvent {
    pub magic: u32,
    pub version: u32,
    pub event: u32,
    pub flags: u32,
    pub lost: u64,
    pub sequence: u64,
    pub type_identity: u64,
    pub reserved: [u8; 24],
}

impl WireStreamEvent {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < EVENT_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_EVENT_MAGIC..OFF_EVENT_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_EVENT_VERSION..OFF_EVENT_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            event: u32::from_le_bytes(
                buf[OFF_EVENT_EVENT..OFF_EVENT_EVENT + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_EVENT_FLAGS..OFF_EVENT_FLAGS + 4]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            lost: u64::from_le_bytes(
                buf[OFF_EVENT_LOST..OFF_EVENT_LOST + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            sequence: u64::from_le_bytes(
                buf[OFF_EVENT_SEQUENCE..OFF_EVENT_SEQUENCE + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_EVENT_TYPE_IDENTITY..OFF_EVENT_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated fabric-stream layout"),
            ),
            reserved: buf[OFF_EVENT_RESERVED..OFF_EVENT_RESERVED + 24]
                .try_into()
                .expect("generated fabric-stream layout"),
        })
    }

    pub fn encode(self) -> [u8; EVENT_LEN] {
        let mut buf = [0u8; EVENT_LEN];
        buf[OFF_EVENT_MAGIC..OFF_EVENT_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_EVENT_VERSION..OFF_EVENT_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_EVENT_EVENT..OFF_EVENT_EVENT + 4].copy_from_slice(&self.event.to_le_bytes());
        buf[OFF_EVENT_FLAGS..OFF_EVENT_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_EVENT_LOST..OFF_EVENT_LOST + 8].copy_from_slice(&self.lost.to_le_bytes());
        buf[OFF_EVENT_SEQUENCE..OFF_EVENT_SEQUENCE + 8]
            .copy_from_slice(&self.sequence.to_le_bytes());
        buf[OFF_EVENT_TYPE_IDENTITY..OFF_EVENT_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_EVENT_RESERVED..OFF_EVENT_RESERVED + 24].copy_from_slice(&self.reserved);
        buf
    }
}
