// @generated by contracts/fabric-operation/v1/gen_rust.zt; do not edit.
// Source contract: contracts/fabric-operation/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const OPERATION_MAGIC: u32 = 1381323091;
pub const OPERATION_LEN: usize = 64;
pub const INLINE_BYTES: usize = 16;
pub const KIND_GOAL: u32 = 1;
pub const KIND_ACCEPTED: u32 = 2;
pub const KIND_FEEDBACK: u32 = 3;
pub const KIND_RESULT: u32 = 4;
pub const KIND_RESULT_REQUEST: u32 = 5;
pub const KIND_CANCEL: u32 = 6;
pub const KIND_TERMINAL: u32 = 7;
pub const STATUS_SUCCESS: i32 = 0;
pub const STATUS_REJECTED: i32 = 1;
pub const STATUS_CANCELLED: i32 = 2;
pub const STATUS_EXPIRED: i32 = 3;
pub const STATUS_TIMEOUT: i32 = 4;
pub const STATUS_PEER_DEAD: i32 = 5;
pub const STATUS_DUPLICATE: i32 = 6;
pub const STATUS_STALE: i32 = 7;
pub const STATUS_MALFORMED: i32 = 8;
pub const STATUS_RETRY_EXHAUSTED: i32 = 9;
pub const STATUS_ACTIVE: i32 = 10;
pub const STATUS_CANCEL_REQUESTED: i32 = 11;

pub const OFF_OPERATION_MAGIC: usize = 0;
pub const OFF_OPERATION_VERSION: usize = 4;
pub const OFF_OPERATION_KIND: usize = 8;
pub const OFF_OPERATION_STATUS: usize = 12;
pub const OFF_OPERATION_SESSION: usize = 16;
pub const OFF_OPERATION_OPERATION_ID: usize = 24;
pub const OFF_OPERATION_TYPE_IDENTITY: usize = 32;
pub const OFF_OPERATION_SEQUENCE: usize = 40;
pub const OFF_OPERATION_PAYLOAD_LEN: usize = 44;
pub const OFF_OPERATION_PAYLOAD: usize = 48;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireOperationEnvelope {
    pub magic: u32,
    pub version: u32,
    pub kind: u32,
    pub status: i32,
    pub session: u64,
    pub operation_id: u64,
    pub type_identity: u64,
    pub sequence: u32,
    pub payload_len: u32,
    pub payload: [u8; 16],
}

impl WireOperationEnvelope {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < OPERATION_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_OPERATION_MAGIC..OFF_OPERATION_MAGIC + 4]
                    .try_into()
                    .expect("generated fabric-operation layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_OPERATION_VERSION..OFF_OPERATION_VERSION + 4]
                    .try_into()
                    .expect("generated fabric-operation layout"),
            ),
            kind: u32::from_le_bytes(
                buf[OFF_OPERATION_KIND..OFF_OPERATION_KIND + 4]
                    .try_into()
                    .expect("generated fabric-operation layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_OPERATION_STATUS..OFF_OPERATION_STATUS + 4]
                    .try_into()
                    .expect("generated fabric-operation layout"),
            ),
            session: u64::from_le_bytes(
                buf[OFF_OPERATION_SESSION..OFF_OPERATION_SESSION + 8]
                    .try_into()
                    .expect("generated fabric-operation layout"),
            ),
            operation_id: u64::from_le_bytes(
                buf[OFF_OPERATION_OPERATION_ID..OFF_OPERATION_OPERATION_ID + 8]
                    .try_into()
                    .expect("generated fabric-operation layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_OPERATION_TYPE_IDENTITY..OFF_OPERATION_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated fabric-operation layout"),
            ),
            sequence: u32::from_le_bytes(
                buf[OFF_OPERATION_SEQUENCE..OFF_OPERATION_SEQUENCE + 4]
                    .try_into()
                    .expect("generated fabric-operation layout"),
            ),
            payload_len: u32::from_le_bytes(
                buf[OFF_OPERATION_PAYLOAD_LEN..OFF_OPERATION_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated fabric-operation layout"),
            ),
            payload: buf[OFF_OPERATION_PAYLOAD..OFF_OPERATION_PAYLOAD + 16]
                .try_into()
                .expect("generated fabric-operation layout"),
        })
    }

    pub fn encode(self) -> [u8; OPERATION_LEN] {
        let mut buf = [0u8; OPERATION_LEN];
        buf[OFF_OPERATION_MAGIC..OFF_OPERATION_MAGIC + 4]
            .copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_OPERATION_VERSION..OFF_OPERATION_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_OPERATION_KIND..OFF_OPERATION_KIND + 4].copy_from_slice(&self.kind.to_le_bytes());
        buf[OFF_OPERATION_STATUS..OFF_OPERATION_STATUS + 4]
            .copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_OPERATION_SESSION..OFF_OPERATION_SESSION + 8]
            .copy_from_slice(&self.session.to_le_bytes());
        buf[OFF_OPERATION_OPERATION_ID..OFF_OPERATION_OPERATION_ID + 8]
            .copy_from_slice(&self.operation_id.to_le_bytes());
        buf[OFF_OPERATION_TYPE_IDENTITY..OFF_OPERATION_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_OPERATION_SEQUENCE..OFF_OPERATION_SEQUENCE + 4]
            .copy_from_slice(&self.sequence.to_le_bytes());
        buf[OFF_OPERATION_PAYLOAD_LEN..OFF_OPERATION_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_OPERATION_PAYLOAD..OFF_OPERATION_PAYLOAD + 16].copy_from_slice(&self.payload);
        buf
    }
}
