// @generated by contracts/fabric-visibility/v1/gen_rust.zt; do not edit.
// Source contract: contracts/fabric-visibility/v1/schema.zt

pub const FORMAT_VERSION: u8 = 1;
pub const RECORD_LEN: usize = 64;
pub const ROUTE_NAME_BYTES: usize = 16;
pub const VISIBILITY_REQUEST_MAGIC: u32 = 1381062214;
pub const VISIBILITY_ROUTE_MAGIC: u32 = 1414682182;
pub const VISIBILITY_QOS_MAGIC: u32 = 1330730566;
pub const INTERPOSITION_TRACE_MAGIC: u32 = 1381258822;
pub const STATUS_RECORD: u8 = 0;
pub const STATUS_END: u8 = 1;
pub const KNOWN_REQUEST_FLAGS: u16 = 0;
pub const KNOWN_ROUTE_FLAGS: u32 = 0;
pub const KNOWN_QOS_FLAGS: u8 = 0;
pub const KNOWN_TRACE_FLAGS: u16 = 0;
pub const TRACE_RELAYED: u8 = 1;
pub const TRACE_PROXY_LOST: u8 = 2;
pub const EVENT_PROXY_LOST: u32 = 1;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireVisibilityRequest {
    pub magic: u32,
    pub version: u8,
    pub cursor: u8,
    pub flags: u16,
    pub reserved: [u8; 56],
}

impl WireVisibilityRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < RECORD_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[0..4]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            version: buf[4],
            cursor: buf[5],
            flags: u16::from_le_bytes(
                buf[6..8]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            reserved: buf[8..64]
                .try_into()
                .expect("generated fabric-visibility layout"),
        })
    }

    pub fn encode(self) -> [u8; RECORD_LEN] {
        let mut buf = [0u8; RECORD_LEN];
        buf[0..4].copy_from_slice(&self.magic.to_le_bytes());
        buf[4] = self.version;
        buf[5] = self.cursor;
        buf[6..8].copy_from_slice(&self.flags.to_le_bytes());
        buf[8..64].copy_from_slice(&self.reserved);
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireVisibilityRouteRecord {
    pub magic: u32,
    pub version: u8,
    pub status: u8,
    pub cursor: u8,
    pub contract_kind: u8,
    pub route_name_len: u8,
    pub reserved0: [u8; 3],
    pub route_name: [u8; 16],
    pub schema_identity: [u8; 32],
    pub flags: u32,
}

impl WireVisibilityRouteRecord {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < RECORD_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[0..4]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            version: buf[4],
            status: buf[5],
            cursor: buf[6],
            contract_kind: buf[7],
            route_name_len: buf[8],
            reserved0: buf[9..12]
                .try_into()
                .expect("generated fabric-visibility layout"),
            route_name: buf[12..28]
                .try_into()
                .expect("generated fabric-visibility layout"),
            schema_identity: buf[28..60]
                .try_into()
                .expect("generated fabric-visibility layout"),
            flags: u32::from_le_bytes(
                buf[60..64]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; RECORD_LEN] {
        let mut buf = [0u8; RECORD_LEN];
        buf[0..4].copy_from_slice(&self.magic.to_le_bytes());
        buf[4] = self.version;
        buf[5] = self.status;
        buf[6] = self.cursor;
        buf[7] = self.contract_kind;
        buf[8] = self.route_name_len;
        buf[9..12].copy_from_slice(&self.reserved0);
        buf[12..28].copy_from_slice(&self.route_name);
        buf[28..60].copy_from_slice(&self.schema_identity);
        buf[60..64].copy_from_slice(&self.flags.to_le_bytes());
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireVisibilityQosRecord {
    pub magic: u32,
    pub version: u8,
    pub status: u8,
    pub cursor: u8,
    pub flags: u8,
    pub route_name: [u8; 16],
    pub reliability: u8,
    pub durability: u8,
    pub liveliness: u8,
    pub matched: u8,
    pub history_depth: u32,
    pub retained_depth: u32,
    pub deadline_ns: u64,
    pub lifespan_ns: u64,
    pub lease_ns: u64,
    pub event_mask: u32,
}

impl WireVisibilityQosRecord {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < RECORD_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[0..4]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            version: buf[4],
            status: buf[5],
            cursor: buf[6],
            flags: buf[7],
            route_name: buf[8..24]
                .try_into()
                .expect("generated fabric-visibility layout"),
            reliability: buf[24],
            durability: buf[25],
            liveliness: buf[26],
            matched: buf[27],
            history_depth: u32::from_le_bytes(
                buf[28..32]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            retained_depth: u32::from_le_bytes(
                buf[32..36]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            deadline_ns: u64::from_le_bytes(
                buf[36..44]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            lifespan_ns: u64::from_le_bytes(
                buf[44..52]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            lease_ns: u64::from_le_bytes(
                buf[52..60]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            event_mask: u32::from_le_bytes(
                buf[60..64]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; RECORD_LEN] {
        let mut buf = [0u8; RECORD_LEN];
        buf[0..4].copy_from_slice(&self.magic.to_le_bytes());
        buf[4] = self.version;
        buf[5] = self.status;
        buf[6] = self.cursor;
        buf[7] = self.flags;
        buf[8..24].copy_from_slice(&self.route_name);
        buf[24] = self.reliability;
        buf[25] = self.durability;
        buf[26] = self.liveliness;
        buf[27] = self.matched;
        buf[28..32].copy_from_slice(&self.history_depth.to_le_bytes());
        buf[32..36].copy_from_slice(&self.retained_depth.to_le_bytes());
        buf[36..44].copy_from_slice(&self.deadline_ns.to_le_bytes());
        buf[44..52].copy_from_slice(&self.lifespan_ns.to_le_bytes());
        buf[52..60].copy_from_slice(&self.lease_ns.to_le_bytes());
        buf[60..64].copy_from_slice(&self.event_mask.to_le_bytes());
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireInterpositionTrace {
    pub magic: u32,
    pub version: u8,
    pub event: u8,
    pub flags: u16,
    pub route_identity: [u8; 32],
    pub sequence: u64,
    pub reserved: [u8; 16],
}

impl WireInterpositionTrace {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < RECORD_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[0..4]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            version: buf[4],
            event: buf[5],
            flags: u16::from_le_bytes(
                buf[6..8]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            route_identity: buf[8..40]
                .try_into()
                .expect("generated fabric-visibility layout"),
            sequence: u64::from_le_bytes(
                buf[40..48]
                    .try_into()
                    .expect("generated fabric-visibility layout"),
            ),
            reserved: buf[48..64]
                .try_into()
                .expect("generated fabric-visibility layout"),
        })
    }

    pub fn encode(self) -> [u8; RECORD_LEN] {
        let mut buf = [0u8; RECORD_LEN];
        buf[0..4].copy_from_slice(&self.magic.to_le_bytes());
        buf[4] = self.version;
        buf[5] = self.event;
        buf[6..8].copy_from_slice(&self.flags.to_le_bytes());
        buf[8..40].copy_from_slice(&self.route_identity);
        buf[40..48].copy_from_slice(&self.sequence.to_le_bytes());
        buf[48..64].copy_from_slice(&self.reserved);
        buf
    }
}
