// @generated by contracts/fs/v1/gen_rust.zt; do not edit.
// Source contract: contracts/fs/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const FS_MAGIC: u32 = 1397117766;
pub const REQUEST_LEN: usize = 64;
pub const REPLY_LEN: usize = 64;
pub const MAX_NAME_BYTES: usize = 16;
pub const MAX_ENTRIES: usize = 16;
pub const MAX_DEPTH: usize = 4;
pub const MAX_PATH_BYTES: usize = 48;
pub const OP_LIST: u8 = 1;
pub const OP_READ: u8 = 2;
pub const OP_WRITE: u8 = 3;
pub const OP_DERIVE: u8 = 4;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OP: usize = 8;
pub const OFF_REQUEST_FLAGS: usize = 9;
pub const OFF_REQUEST_NAME_LEN: usize = 10;
pub const OFF_REQUEST_RESERVED0: usize = 11;
pub const OFF_REQUEST_NAME: usize = 12;
pub const OFF_REQUEST_PAYLOAD_LEN: usize = 28;
pub const OFF_REQUEST_HASH0: usize = 32;
pub const OFF_REQUEST_HASH1: usize = 40;
pub const OFF_REQUEST_HASH2: usize = 48;
pub const OFF_REQUEST_HASH3: usize = 56;

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_ENTRY_COUNT: usize = 12;
pub const OFF_REPLY_OBJECT_TYPE: usize = 16;
pub const OFF_REPLY_PAYLOAD_LEN: usize = 20;
pub const OFF_REPLY_HASH0: usize = 24;
pub const OFF_REPLY_HASH1: usize = 32;
pub const OFF_REPLY_HASH2: usize = 40;
pub const OFF_REPLY_HASH3: usize = 48;
pub const OFF_REPLY_RESERVED: usize = 56;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireFsRequest {
    pub magic: u32,
    pub version: u32,
    pub op: u8,
    pub flags: u8,
    pub name_len: u8,
    pub reserved0: u8,
    pub name: [u8; 16],
    pub payload_len: u32,
    pub hash0: u64,
    pub hash1: u64,
    pub hash2: u64,
    pub hash3: u64,
}

impl WireFsRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            op: buf[OFF_REQUEST_OP],
            flags: buf[OFF_REQUEST_FLAGS],
            name_len: buf[OFF_REQUEST_NAME_LEN],
            reserved0: buf[OFF_REQUEST_RESERVED0],
            name: buf[OFF_REQUEST_NAME..OFF_REQUEST_NAME + 16]
                .try_into()
                .expect("generated fs layout"),
            payload_len: u32::from_le_bytes(
                buf[OFF_REQUEST_PAYLOAD_LEN..OFF_REQUEST_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            hash0: u64::from_le_bytes(
                buf[OFF_REQUEST_HASH0..OFF_REQUEST_HASH0 + 8]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            hash1: u64::from_le_bytes(
                buf[OFF_REQUEST_HASH1..OFF_REQUEST_HASH1 + 8]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            hash2: u64::from_le_bytes(
                buf[OFF_REQUEST_HASH2..OFF_REQUEST_HASH2 + 8]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            hash3: u64::from_le_bytes(
                buf[OFF_REQUEST_HASH3..OFF_REQUEST_HASH3 + 8]
                    .try_into()
                    .expect("generated fs layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OP] = self.op;
        buf[OFF_REQUEST_FLAGS] = self.flags;
        buf[OFF_REQUEST_NAME_LEN] = self.name_len;
        buf[OFF_REQUEST_RESERVED0] = self.reserved0;
        buf[OFF_REQUEST_NAME..OFF_REQUEST_NAME + 16].copy_from_slice(&self.name);
        buf[OFF_REQUEST_PAYLOAD_LEN..OFF_REQUEST_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_REQUEST_HASH0..OFF_REQUEST_HASH0 + 8].copy_from_slice(&self.hash0.to_le_bytes());
        buf[OFF_REQUEST_HASH1..OFF_REQUEST_HASH1 + 8].copy_from_slice(&self.hash1.to_le_bytes());
        buf[OFF_REQUEST_HASH2..OFF_REQUEST_HASH2 + 8].copy_from_slice(&self.hash2.to_le_bytes());
        buf[OFF_REQUEST_HASH3..OFF_REQUEST_HASH3 + 8].copy_from_slice(&self.hash3.to_le_bytes());
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireFsReply {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub entry_count: u32,
    pub object_type: u32,
    pub payload_len: u32,
    pub hash0: u64,
    pub hash1: u64,
    pub hash2: u64,
    pub hash3: u64,
    pub reserved: u32,
}

impl WireFsReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            entry_count: u32::from_le_bytes(
                buf[OFF_REPLY_ENTRY_COUNT..OFF_REPLY_ENTRY_COUNT + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            object_type: u32::from_le_bytes(
                buf[OFF_REPLY_OBJECT_TYPE..OFF_REPLY_OBJECT_TYPE + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            payload_len: u32::from_le_bytes(
                buf[OFF_REPLY_PAYLOAD_LEN..OFF_REPLY_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            hash0: u64::from_le_bytes(
                buf[OFF_REPLY_HASH0..OFF_REPLY_HASH0 + 8]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            hash1: u64::from_le_bytes(
                buf[OFF_REPLY_HASH1..OFF_REPLY_HASH1 + 8]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            hash2: u64::from_le_bytes(
                buf[OFF_REPLY_HASH2..OFF_REPLY_HASH2 + 8]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            hash3: u64::from_le_bytes(
                buf[OFF_REPLY_HASH3..OFF_REPLY_HASH3 + 8]
                    .try_into()
                    .expect("generated fs layout"),
            ),
            reserved: u32::from_le_bytes(
                buf[OFF_REPLY_RESERVED..OFF_REPLY_RESERVED + 4]
                    .try_into()
                    .expect("generated fs layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_ENTRY_COUNT..OFF_REPLY_ENTRY_COUNT + 4]
            .copy_from_slice(&self.entry_count.to_le_bytes());
        buf[OFF_REPLY_OBJECT_TYPE..OFF_REPLY_OBJECT_TYPE + 4]
            .copy_from_slice(&self.object_type.to_le_bytes());
        buf[OFF_REPLY_PAYLOAD_LEN..OFF_REPLY_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_REPLY_HASH0..OFF_REPLY_HASH0 + 8].copy_from_slice(&self.hash0.to_le_bytes());
        buf[OFF_REPLY_HASH1..OFF_REPLY_HASH1 + 8].copy_from_slice(&self.hash1.to_le_bytes());
        buf[OFF_REPLY_HASH2..OFF_REPLY_HASH2 + 8].copy_from_slice(&self.hash2.to_le_bytes());
        buf[OFF_REPLY_HASH3..OFF_REPLY_HASH3 + 8].copy_from_slice(&self.hash3.to_le_bytes());
        buf[OFF_REPLY_RESERVED..OFF_REPLY_RESERVED + 4]
            .copy_from_slice(&self.reserved.to_le_bytes());
        buf
    }
}
