// @generated by contracts/generation-management/v1/gen_rust.zt; do not edit.
// Source contract: contracts/generation-management/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const GENERATION_MAGIC: u32 = 1313295955;
pub const REQUEST_LEN: usize = 64;
pub const REPLY_LEN: usize = 64;
pub const MAX_ENTRIES: usize = 64;
pub const OP_LIST: u8 = 1;
pub const OP_INSPECT: u8 = 2;
pub const OP_STAGE: u8 = 3;
pub const OP_SELECT: u8 = 4;
pub const OP_ROLLBACK: u8 = 5;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OP: usize = 8;
pub const OFF_REQUEST_FLAGS: usize = 9;
pub const OFF_REQUEST_RESERVED: usize = 10;
pub const OFF_REQUEST_GENERATION0: usize = 16;
pub const OFF_REQUEST_GENERATION1: usize = 24;
pub const OFF_REQUEST_GENERATION2: usize = 32;
pub const OFF_REQUEST_GENERATION3: usize = 40;

pub const REPLY_FLAG_KNOWN_GOOD: u32 = 1;
pub const REPLY_FLAG_PENDING: u32 = 2;
pub const REPLY_FLAG_RUNNING: u32 = 4;
pub const REPLY_FLAG_STAGED: u32 = 8;
pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_FLAGS: usize = 12;
pub const OFF_REPLY_COUNT: usize = 16;
pub const OFF_REPLY_GENERATION_NUMBER: usize = 20;
pub const OFF_REPLY_RELEASE_SEQUENCE: usize = 24;
pub const OFF_REPLY_REMAINING_ATTEMPTS: usize = 28;
pub const OFF_REPLY_GENERATION0: usize = 32;
pub const OFF_REPLY_GENERATION1: usize = 40;
pub const OFF_REPLY_GENERATION2: usize = 48;
pub const OFF_REPLY_GENERATION3: usize = 56;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireGenerationRequest {
    pub magic: u32,
    pub version: u32,
    pub op: u8,
    pub flags: u8,
    pub reserved: [u8; 6],
    pub generation0: u64,
    pub generation1: u64,
    pub generation2: u64,
    pub generation3: u64,
}

impl WireGenerationRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            op: buf[OFF_REQUEST_OP],
            flags: buf[OFF_REQUEST_FLAGS],
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 6]
                .try_into()
                .expect("generated generation-management layout"),
            generation0: u64::from_le_bytes(
                buf[OFF_REQUEST_GENERATION0..OFF_REQUEST_GENERATION0 + 8]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            generation1: u64::from_le_bytes(
                buf[OFF_REQUEST_GENERATION1..OFF_REQUEST_GENERATION1 + 8]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            generation2: u64::from_le_bytes(
                buf[OFF_REQUEST_GENERATION2..OFF_REQUEST_GENERATION2 + 8]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            generation3: u64::from_le_bytes(
                buf[OFF_REQUEST_GENERATION3..OFF_REQUEST_GENERATION3 + 8]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OP] = self.op;
        buf[OFF_REQUEST_FLAGS] = self.flags;
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 6].copy_from_slice(&self.reserved);
        buf[OFF_REQUEST_GENERATION0..OFF_REQUEST_GENERATION0 + 8]
            .copy_from_slice(&self.generation0.to_le_bytes());
        buf[OFF_REQUEST_GENERATION1..OFF_REQUEST_GENERATION1 + 8]
            .copy_from_slice(&self.generation1.to_le_bytes());
        buf[OFF_REQUEST_GENERATION2..OFF_REQUEST_GENERATION2 + 8]
            .copy_from_slice(&self.generation2.to_le_bytes());
        buf[OFF_REQUEST_GENERATION3..OFF_REQUEST_GENERATION3 + 8]
            .copy_from_slice(&self.generation3.to_le_bytes());
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireGenerationReply {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub flags: u32,
    pub count: u32,
    pub generation_number: u32,
    pub release_sequence: u32,
    pub remaining_attempts: u32,
    pub generation0: u64,
    pub generation1: u64,
    pub generation2: u64,
    pub generation3: u64,
}

impl WireGenerationReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_REPLY_FLAGS..OFF_REPLY_FLAGS + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            count: u32::from_le_bytes(
                buf[OFF_REPLY_COUNT..OFF_REPLY_COUNT + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            generation_number: u32::from_le_bytes(
                buf[OFF_REPLY_GENERATION_NUMBER..OFF_REPLY_GENERATION_NUMBER + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            release_sequence: u32::from_le_bytes(
                buf[OFF_REPLY_RELEASE_SEQUENCE..OFF_REPLY_RELEASE_SEQUENCE + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            remaining_attempts: u32::from_le_bytes(
                buf[OFF_REPLY_REMAINING_ATTEMPTS..OFF_REPLY_REMAINING_ATTEMPTS + 4]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            generation0: u64::from_le_bytes(
                buf[OFF_REPLY_GENERATION0..OFF_REPLY_GENERATION0 + 8]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            generation1: u64::from_le_bytes(
                buf[OFF_REPLY_GENERATION1..OFF_REPLY_GENERATION1 + 8]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            generation2: u64::from_le_bytes(
                buf[OFF_REPLY_GENERATION2..OFF_REPLY_GENERATION2 + 8]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
            generation3: u64::from_le_bytes(
                buf[OFF_REPLY_GENERATION3..OFF_REPLY_GENERATION3 + 8]
                    .try_into()
                    .expect("generated generation-management layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_FLAGS..OFF_REPLY_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_REPLY_COUNT..OFF_REPLY_COUNT + 4].copy_from_slice(&self.count.to_le_bytes());
        buf[OFF_REPLY_GENERATION_NUMBER..OFF_REPLY_GENERATION_NUMBER + 4]
            .copy_from_slice(&self.generation_number.to_le_bytes());
        buf[OFF_REPLY_RELEASE_SEQUENCE..OFF_REPLY_RELEASE_SEQUENCE + 4]
            .copy_from_slice(&self.release_sequence.to_le_bytes());
        buf[OFF_REPLY_REMAINING_ATTEMPTS..OFF_REPLY_REMAINING_ATTEMPTS + 4]
            .copy_from_slice(&self.remaining_attempts.to_le_bytes());
        buf[OFF_REPLY_GENERATION0..OFF_REPLY_GENERATION0 + 8]
            .copy_from_slice(&self.generation0.to_le_bytes());
        buf[OFF_REPLY_GENERATION1..OFF_REPLY_GENERATION1 + 8]
            .copy_from_slice(&self.generation1.to_le_bytes());
        buf[OFF_REPLY_GENERATION2..OFF_REPLY_GENERATION2 + 8]
            .copy_from_slice(&self.generation2.to_le_bytes());
        buf[OFF_REPLY_GENERATION3..OFF_REPLY_GENERATION3 + 8]
            .copy_from_slice(&self.generation3.to_le_bytes());
        buf
    }
}
