// @generated by scripts/generate/generate-interface-schema-bindings.py; do not edit.
// Source contracts: contracts/interface-schema/v1/interfaces/*.zti

use core::marker::PhantomData;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Stream<T>(PhantomData<fn() -> T>);

impl<T> Stream<T> {
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}

impl<T> Default for Stream<T> {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Call<Request, Reply>(PhantomData<fn(Request) -> Reply>);

impl<Request, Reply> Call<Request, Reply> {
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}

impl<Request, Reply> Default for Call<Request, Reply> {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Operation<Goal, Feedback, Result>(PhantomData<fn(Goal, Feedback) -> Result>);

impl<Goal, Feedback, Result> Operation<Goal, Feedback, Result> {
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}

impl<Goal, Feedback, Result> Default for Operation<Goal, Feedback, Result> {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BoundedSequence<T, const N: usize> {
    length: u32,
    values: [T; N],
}

impl<T, const N: usize> BoundedSequence<T, N> {
    pub fn new(length: usize, values: [T; N]) -> Option<Self> {
        if length > N || length > u32::MAX as usize {
            return None;
        }
        Some(Self {
            length: length as u32,
            values,
        })
    }

    pub const fn len(&self) -> usize {
        self.length as usize
    }

    pub const fn is_empty(&self) -> bool {
        self.length == 0
    }

    pub fn as_slice(&self) -> &[T] {
        &self.values[..self.len()]
    }
}

pub mod navigation_operation {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct NavigationFeedback {
        pub remaining_mm: u64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct NavigationGoal {
        pub x_mm: i64,
        pub y_mm: i64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct NavigationResult {
        pub status: i32,
    }

    pub type NavigationOperation =
        super::Operation<NavigationGoal, NavigationFeedback, NavigationResult>;

    pub const INTERFACE_IDENTITY: [u8; 32] = [
        0x9b, 0x49, 0xef, 0x20, 0x96, 0xb0, 0x25, 0xe9, 0xa0, 0x7b, 0xd5, 0xc2, 0x69, 0x37, 0x93,
        0xc8, 0x33, 0xc9, 0x53, 0xe3, 0x70, 0x07, 0x55, 0x56, 0xa5, 0x75, 0x50, 0x1f, 0x84, 0x6c,
        0xb9, 0xbd,
    ];
    pub const TYPE_TAG: u64 = 0x645b4bb431761df9;
    pub const MAX_ENCODED_BYTES: usize = 16;
}
pub mod parameter_call {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct ParameterReply {
        pub accepted: u8,
        pub revision: u64,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct ParameterRequest {
        pub parameter: [u8; 32],
        pub value: i64,
    }

    pub type ParameterCall = super::Call<ParameterRequest, ParameterReply>;

    pub const INTERFACE_IDENTITY: [u8; 32] = [
        0x8f, 0x23, 0xbd, 0x8c, 0xdf, 0x77, 0xd1, 0xff, 0x3c, 0x62, 0x40, 0x95, 0x14, 0xdb, 0xb9,
        0xc2, 0xe0, 0xb6, 0x6e, 0xf4, 0x70, 0x7d, 0x81, 0xdb, 0xef, 0x0c, 0xb0, 0x01, 0x30, 0x1f,
        0xb8, 0x3f,
    ];
    pub const TYPE_TAG: u64 = 0xd7eabf1a3dd69200;
    pub const MAX_ENCODED_BYTES: usize = 40;
}
pub mod telemetry_stream {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct FrameId {
        pub value: u32,
    }

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct TelemetrySample {
        pub sequence: u64,
        pub frame: FrameId,
        pub readings: super::BoundedSequence<i32, 8>,
        pub label: [u8; 16],
    }

    pub type TelemetryStream = super::Stream<TelemetrySample>;

    pub const INTERFACE_IDENTITY: [u8; 32] = [
        0xf6, 0xe9, 0x51, 0xeb, 0x0e, 0x36, 0x53, 0x90, 0x02, 0xa3, 0x2a, 0xff, 0x3f, 0x33, 0xdf,
        0x10, 0x82, 0xea, 0x2e, 0xcc, 0x24, 0x13, 0x43, 0x0f, 0x2d, 0x68, 0x6f, 0x92, 0xe1, 0x41,
        0xba, 0x25,
    ];
    pub const TYPE_TAG: u64 = 0x1164153908db137b;
    pub const MAX_ENCODED_BYTES: usize = 64;
}
