// @generated by contracts/io-queue/v1/gen_rust.zt; do not edit.
// Source contract: contracts/io-queue/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const QUEUE_HEADER_LEN: usize = 128;
pub const REQUEST_SLOT_LEN: usize = 128;
pub const COMPLETION_SLOT_LEN: usize = 64;
pub const REQUEST_PAYLOAD_BYTES: usize = 56;
pub const COMPLETION_PAYLOAD_BYTES: usize = 24;
pub const MIN_QUEUE_SLOTS: usize = 2;
pub const MAX_QUEUE_SLOTS: usize = 256;
pub const MAX_OUTSTANDING: usize = 256;
pub const QUEUE_MAGIC: u32 = 1213486921;
pub const REQUEST_MAGIC: u32 = 1381259081;
pub const COMPLETION_MAGIC: u32 = 1129270601;
pub const DRIVER_ACTIVE: u32 = 0;
pub const DRIVER_RESETTING: u32 = 1;
pub const DRIVER_DEAD: u32 = 2;
pub const SLOT_EMPTY: u32 = 0;
pub const SLOT_CLAIMED: u32 = 1;
pub const SLOT_READY: u32 = 2;
pub const STATE_QUEUED: u32 = 1;
pub const STATE_IN_FLIGHT: u32 = 2;
pub const STATE_COMPLETE: u32 = 3;
pub const STATE_CANCELLED: u32 = 4;
pub const STATE_RESET: u32 = 5;
pub const STATE_PEER_DEAD: u32 = 6;
pub const STATUS_OK: u32 = 0;
pub const STATUS_CANCELLED: u32 = 1;
pub const STATUS_RESET: u32 = 2;
pub const STATUS_PEER_DEAD: u32 = 3;
pub const STATUS_MALFORMED: u32 = 4;
pub const STATUS_BAD_SLICE: u32 = 5;
pub const STATUS_BAD_EPOCH: u32 = 6;
pub const STATUS_BAD_RIGHTS: u32 = 7;
pub const STATUS_EXHAUSTED: u32 = 8;
pub const STATUS_DEVICE_ERROR: u32 = 9;
pub const STATUS_UNSUPPORTED: u32 = 10;
pub const DIRECTION_NONE: u32 = 0;
pub const DIRECTION_DEVICE_READ: u32 = 1;
pub const DIRECTION_DEVICE_WRITE: u32 = 2;
pub const KNOWN_DIRECTIONS: u32 = 3;
pub const FLAG_FENCED: u32 = 1;
pub const KNOWN_REQUEST_FLAGS: u32 = 1;
pub const FLAG_EPOCH_ENDED: u32 = 1;
pub const KNOWN_COMPLETION_FLAGS: u32 = 1;
pub const BADGE_REQUEST_READY: u64 = 1;
pub const BADGE_COMPLETION_READY: u64 = 2;
pub const BADGE_DRIVER_STATE_CHANGED: u64 = 4;
pub const KNOWN_BADGE_BITS: u64 = 7;

pub const OFF_HEADER_MAGIC: usize = 0;
pub const OFF_HEADER_VERSION: usize = 4;
pub const OFF_HEADER_SLOT_COUNT: usize = 8;
pub const OFF_HEADER_REQUEST_SLOT_LEN: usize = 12;
pub const OFF_HEADER_COMPLETION_SLOT_LEN: usize = 16;
pub const OFF_HEADER_CLIENT_RESERVED: usize = 20;
pub const OFF_HEADER_SUBMIT_HEAD: usize = 24;
pub const OFF_HEADER_COMPLETE_TAIL: usize = 32;
pub const OFF_HEADER_CLIENT_PADDING: usize = 40;
pub const OFF_HEADER_DRIVER_STATE: usize = 64;
pub const OFF_HEADER_DRIVER_RESERVED: usize = 68;
pub const OFF_HEADER_EPOCH: usize = 72;
pub const OFF_HEADER_COMPLETE_HEAD: usize = 80;
pub const OFF_HEADER_SUBMIT_TAIL: usize = 88;
pub const OFF_HEADER_DRIVER_PADDING: usize = 96;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireQueueHeader {
    pub magic: u32,
    pub version: u32,
    pub slot_count: u32,
    pub request_slot_len: u32,
    pub completion_slot_len: u32,
    pub client_reserved: [u8; 4],
    pub submit_head: u64,
    pub complete_tail: u64,
    pub client_padding: [u8; 24],
    pub driver_state: u32,
    pub driver_reserved: [u8; 4],
    pub epoch: u64,
    pub complete_head: u64,
    pub submit_tail: u64,
    pub driver_padding: [u8; 32],
}

impl WireQueueHeader {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < QUEUE_HEADER_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_HEADER_MAGIC..OFF_HEADER_MAGIC + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_HEADER_VERSION..OFF_HEADER_VERSION + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            slot_count: u32::from_le_bytes(
                buf[OFF_HEADER_SLOT_COUNT..OFF_HEADER_SLOT_COUNT + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            request_slot_len: u32::from_le_bytes(
                buf[OFF_HEADER_REQUEST_SLOT_LEN..OFF_HEADER_REQUEST_SLOT_LEN + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            completion_slot_len: u32::from_le_bytes(
                buf[OFF_HEADER_COMPLETION_SLOT_LEN..OFF_HEADER_COMPLETION_SLOT_LEN + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            client_reserved: buf[OFF_HEADER_CLIENT_RESERVED..OFF_HEADER_CLIENT_RESERVED + 4]
                .try_into()
                .expect("generated io-queue layout"),
            submit_head: u64::from_le_bytes(
                buf[OFF_HEADER_SUBMIT_HEAD..OFF_HEADER_SUBMIT_HEAD + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            complete_tail: u64::from_le_bytes(
                buf[OFF_HEADER_COMPLETE_TAIL..OFF_HEADER_COMPLETE_TAIL + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            client_padding: buf[OFF_HEADER_CLIENT_PADDING..OFF_HEADER_CLIENT_PADDING + 24]
                .try_into()
                .expect("generated io-queue layout"),
            driver_state: u32::from_le_bytes(
                buf[OFF_HEADER_DRIVER_STATE..OFF_HEADER_DRIVER_STATE + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            driver_reserved: buf[OFF_HEADER_DRIVER_RESERVED..OFF_HEADER_DRIVER_RESERVED + 4]
                .try_into()
                .expect("generated io-queue layout"),
            epoch: u64::from_le_bytes(
                buf[OFF_HEADER_EPOCH..OFF_HEADER_EPOCH + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            complete_head: u64::from_le_bytes(
                buf[OFF_HEADER_COMPLETE_HEAD..OFF_HEADER_COMPLETE_HEAD + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            submit_tail: u64::from_le_bytes(
                buf[OFF_HEADER_SUBMIT_TAIL..OFF_HEADER_SUBMIT_TAIL + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            driver_padding: buf[OFF_HEADER_DRIVER_PADDING..OFF_HEADER_DRIVER_PADDING + 32]
                .try_into()
                .expect("generated io-queue layout"),
        })
    }

    pub fn encode(self) -> [u8; QUEUE_HEADER_LEN] {
        let mut buf = [0u8; QUEUE_HEADER_LEN];
        buf[OFF_HEADER_MAGIC..OFF_HEADER_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_HEADER_VERSION..OFF_HEADER_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_HEADER_SLOT_COUNT..OFF_HEADER_SLOT_COUNT + 4]
            .copy_from_slice(&self.slot_count.to_le_bytes());
        buf[OFF_HEADER_REQUEST_SLOT_LEN..OFF_HEADER_REQUEST_SLOT_LEN + 4]
            .copy_from_slice(&self.request_slot_len.to_le_bytes());
        buf[OFF_HEADER_COMPLETION_SLOT_LEN..OFF_HEADER_COMPLETION_SLOT_LEN + 4]
            .copy_from_slice(&self.completion_slot_len.to_le_bytes());
        buf[OFF_HEADER_CLIENT_RESERVED..OFF_HEADER_CLIENT_RESERVED + 4]
            .copy_from_slice(&self.client_reserved);
        buf[OFF_HEADER_SUBMIT_HEAD..OFF_HEADER_SUBMIT_HEAD + 8]
            .copy_from_slice(&self.submit_head.to_le_bytes());
        buf[OFF_HEADER_COMPLETE_TAIL..OFF_HEADER_COMPLETE_TAIL + 8]
            .copy_from_slice(&self.complete_tail.to_le_bytes());
        buf[OFF_HEADER_CLIENT_PADDING..OFF_HEADER_CLIENT_PADDING + 24]
            .copy_from_slice(&self.client_padding);
        buf[OFF_HEADER_DRIVER_STATE..OFF_HEADER_DRIVER_STATE + 4]
            .copy_from_slice(&self.driver_state.to_le_bytes());
        buf[OFF_HEADER_DRIVER_RESERVED..OFF_HEADER_DRIVER_RESERVED + 4]
            .copy_from_slice(&self.driver_reserved);
        buf[OFF_HEADER_EPOCH..OFF_HEADER_EPOCH + 8].copy_from_slice(&self.epoch.to_le_bytes());
        buf[OFF_HEADER_COMPLETE_HEAD..OFF_HEADER_COMPLETE_HEAD + 8]
            .copy_from_slice(&self.complete_head.to_le_bytes());
        buf[OFF_HEADER_SUBMIT_TAIL..OFF_HEADER_SUBMIT_TAIL + 8]
            .copy_from_slice(&self.submit_tail.to_le_bytes());
        buf[OFF_HEADER_DRIVER_PADDING..OFF_HEADER_DRIVER_PADDING + 32]
            .copy_from_slice(&self.driver_padding);
        buf
    }
}

pub const SLICE_LEN: usize = 40;
pub const OFF_SLICE_BUFFER: usize = 0;
pub const OFF_SLICE_LEASE: usize = 8;
pub const OFF_SLICE_OFFSET: usize = 16;
pub const OFF_SLICE_LENGTH: usize = 24;
pub const OFF_SLICE_DIRECTION: usize = 32;
pub const OFF_SLICE_RESERVED: usize = 36;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireBufferSlice {
    pub buffer: u64,
    pub lease: u64,
    pub offset: u64,
    pub length: u64,
    pub direction: u32,
    pub reserved: [u8; 4],
}

impl WireBufferSlice {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < SLICE_LEN {
            return None;
        }
        Some(Self {
            buffer: u64::from_le_bytes(
                buf[OFF_SLICE_BUFFER..OFF_SLICE_BUFFER + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            lease: u64::from_le_bytes(
                buf[OFF_SLICE_LEASE..OFF_SLICE_LEASE + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            offset: u64::from_le_bytes(
                buf[OFF_SLICE_OFFSET..OFF_SLICE_OFFSET + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            length: u64::from_le_bytes(
                buf[OFF_SLICE_LENGTH..OFF_SLICE_LENGTH + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            direction: u32::from_le_bytes(
                buf[OFF_SLICE_DIRECTION..OFF_SLICE_DIRECTION + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            reserved: buf[OFF_SLICE_RESERVED..OFF_SLICE_RESERVED + 4]
                .try_into()
                .expect("generated io-queue layout"),
        })
    }

    pub fn encode(self) -> [u8; SLICE_LEN] {
        let mut buf = [0u8; SLICE_LEN];
        buf[OFF_SLICE_BUFFER..OFF_SLICE_BUFFER + 8].copy_from_slice(&self.buffer.to_le_bytes());
        buf[OFF_SLICE_LEASE..OFF_SLICE_LEASE + 8].copy_from_slice(&self.lease.to_le_bytes());
        buf[OFF_SLICE_OFFSET..OFF_SLICE_OFFSET + 8].copy_from_slice(&self.offset.to_le_bytes());
        buf[OFF_SLICE_LENGTH..OFF_SLICE_LENGTH + 8].copy_from_slice(&self.length.to_le_bytes());
        buf[OFF_SLICE_DIRECTION..OFF_SLICE_DIRECTION + 4]
            .copy_from_slice(&self.direction.to_le_bytes());
        buf[OFF_SLICE_RESERVED..OFF_SLICE_RESERVED + 4].copy_from_slice(&self.reserved);
        buf
    }
}

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_STATE: usize = 4;
pub const OFF_REQUEST_FLAGS: usize = 8;
pub const OFF_REQUEST_PAYLOAD_LEN: usize = 12;
pub const OFF_REQUEST_REQUEST_ID: usize = 16;
pub const OFF_REQUEST_EPOCH: usize = 24;
pub const OFF_REQUEST_SLICE_BUFFER: usize = 32;
pub const OFF_REQUEST_SLICE_LEASE: usize = 40;
pub const OFF_REQUEST_SLICE_OFFSET: usize = 48;
pub const OFF_REQUEST_SLICE_LENGTH: usize = 56;
pub const OFF_REQUEST_SLICE_DIRECTION: usize = 64;
pub const OFF_REQUEST_SLICE_RESERVED: usize = 68;
pub const OFF_REQUEST_PAYLOAD: usize = 72;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireRequestSlot {
    pub magic: u32,
    pub state: u32,
    pub flags: u32,
    pub payload_len: u32,
    pub request_id: u64,
    pub epoch: u64,
    pub slice_buffer: u64,
    pub slice_lease: u64,
    pub slice_offset: u64,
    pub slice_length: u64,
    pub slice_direction: u32,
    pub slice_reserved: [u8; 4],
    pub payload: [u8; 56],
}

impl WireRequestSlot {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_SLOT_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            state: u32::from_le_bytes(
                buf[OFF_REQUEST_STATE..OFF_REQUEST_STATE + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            payload_len: u32::from_le_bytes(
                buf[OFF_REQUEST_PAYLOAD_LEN..OFF_REQUEST_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            request_id: u64::from_le_bytes(
                buf[OFF_REQUEST_REQUEST_ID..OFF_REQUEST_REQUEST_ID + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            epoch: u64::from_le_bytes(
                buf[OFF_REQUEST_EPOCH..OFF_REQUEST_EPOCH + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            slice_buffer: u64::from_le_bytes(
                buf[OFF_REQUEST_SLICE_BUFFER..OFF_REQUEST_SLICE_BUFFER + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            slice_lease: u64::from_le_bytes(
                buf[OFF_REQUEST_SLICE_LEASE..OFF_REQUEST_SLICE_LEASE + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            slice_offset: u64::from_le_bytes(
                buf[OFF_REQUEST_SLICE_OFFSET..OFF_REQUEST_SLICE_OFFSET + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            slice_length: u64::from_le_bytes(
                buf[OFF_REQUEST_SLICE_LENGTH..OFF_REQUEST_SLICE_LENGTH + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            slice_direction: u32::from_le_bytes(
                buf[OFF_REQUEST_SLICE_DIRECTION..OFF_REQUEST_SLICE_DIRECTION + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            slice_reserved: buf[OFF_REQUEST_SLICE_RESERVED..OFF_REQUEST_SLICE_RESERVED + 4]
                .try_into()
                .expect("generated io-queue layout"),
            payload: buf[OFF_REQUEST_PAYLOAD..OFF_REQUEST_PAYLOAD + 56]
                .try_into()
                .expect("generated io-queue layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_SLOT_LEN] {
        let mut buf = [0u8; REQUEST_SLOT_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_STATE..OFF_REQUEST_STATE + 4].copy_from_slice(&self.state.to_le_bytes());
        buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_REQUEST_PAYLOAD_LEN..OFF_REQUEST_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_REQUEST_REQUEST_ID..OFF_REQUEST_REQUEST_ID + 8]
            .copy_from_slice(&self.request_id.to_le_bytes());
        buf[OFF_REQUEST_EPOCH..OFF_REQUEST_EPOCH + 8].copy_from_slice(&self.epoch.to_le_bytes());
        buf[OFF_REQUEST_SLICE_BUFFER..OFF_REQUEST_SLICE_BUFFER + 8]
            .copy_from_slice(&self.slice_buffer.to_le_bytes());
        buf[OFF_REQUEST_SLICE_LEASE..OFF_REQUEST_SLICE_LEASE + 8]
            .copy_from_slice(&self.slice_lease.to_le_bytes());
        buf[OFF_REQUEST_SLICE_OFFSET..OFF_REQUEST_SLICE_OFFSET + 8]
            .copy_from_slice(&self.slice_offset.to_le_bytes());
        buf[OFF_REQUEST_SLICE_LENGTH..OFF_REQUEST_SLICE_LENGTH + 8]
            .copy_from_slice(&self.slice_length.to_le_bytes());
        buf[OFF_REQUEST_SLICE_DIRECTION..OFF_REQUEST_SLICE_DIRECTION + 4]
            .copy_from_slice(&self.slice_direction.to_le_bytes());
        buf[OFF_REQUEST_SLICE_RESERVED..OFF_REQUEST_SLICE_RESERVED + 4]
            .copy_from_slice(&self.slice_reserved);
        buf[OFF_REQUEST_PAYLOAD..OFF_REQUEST_PAYLOAD + 56].copy_from_slice(&self.payload);
        buf
    }
}

pub const OFF_COMPLETION_MAGIC: usize = 0;
pub const OFF_COMPLETION_STATUS: usize = 4;
pub const OFF_COMPLETION_FLAGS: usize = 8;
pub const OFF_COMPLETION_PAYLOAD_LEN: usize = 12;
pub const OFF_COMPLETION_REQUEST_ID: usize = 16;
pub const OFF_COMPLETION_EPOCH: usize = 24;
pub const OFF_COMPLETION_TRANSFERRED: usize = 32;
pub const OFF_COMPLETION_PAYLOAD: usize = 40;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireCompletionSlot {
    pub magic: u32,
    pub status: u32,
    pub flags: u32,
    pub payload_len: u32,
    pub request_id: u64,
    pub epoch: u64,
    pub transferred: u64,
    pub payload: [u8; 24],
}

impl WireCompletionSlot {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < COMPLETION_SLOT_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_COMPLETION_MAGIC..OFF_COMPLETION_MAGIC + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            status: u32::from_le_bytes(
                buf[OFF_COMPLETION_STATUS..OFF_COMPLETION_STATUS + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_COMPLETION_FLAGS..OFF_COMPLETION_FLAGS + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            payload_len: u32::from_le_bytes(
                buf[OFF_COMPLETION_PAYLOAD_LEN..OFF_COMPLETION_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            request_id: u64::from_le_bytes(
                buf[OFF_COMPLETION_REQUEST_ID..OFF_COMPLETION_REQUEST_ID + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            epoch: u64::from_le_bytes(
                buf[OFF_COMPLETION_EPOCH..OFF_COMPLETION_EPOCH + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            transferred: u64::from_le_bytes(
                buf[OFF_COMPLETION_TRANSFERRED..OFF_COMPLETION_TRANSFERRED + 8]
                    .try_into()
                    .expect("generated io-queue layout"),
            ),
            payload: buf[OFF_COMPLETION_PAYLOAD..OFF_COMPLETION_PAYLOAD + 24]
                .try_into()
                .expect("generated io-queue layout"),
        })
    }

    pub fn encode(self) -> [u8; COMPLETION_SLOT_LEN] {
        let mut buf = [0u8; COMPLETION_SLOT_LEN];
        buf[OFF_COMPLETION_MAGIC..OFF_COMPLETION_MAGIC + 4]
            .copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_COMPLETION_STATUS..OFF_COMPLETION_STATUS + 4]
            .copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_COMPLETION_FLAGS..OFF_COMPLETION_FLAGS + 4]
            .copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_COMPLETION_PAYLOAD_LEN..OFF_COMPLETION_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_COMPLETION_REQUEST_ID..OFF_COMPLETION_REQUEST_ID + 8]
            .copy_from_slice(&self.request_id.to_le_bytes());
        buf[OFF_COMPLETION_EPOCH..OFF_COMPLETION_EPOCH + 8]
            .copy_from_slice(&self.epoch.to_le_bytes());
        buf[OFF_COMPLETION_TRANSFERRED..OFF_COMPLETION_TRANSFERRED + 8]
            .copy_from_slice(&self.transferred.to_le_bytes());
        buf[OFF_COMPLETION_PAYLOAD..OFF_COMPLETION_PAYLOAD + 24].copy_from_slice(&self.payload);
        buf
    }
}
