#![no_std]

// block.rs and store.rs are generated by scripts/generate-block-bindings.py
// and scripts/generate-store-bindings.py from contracts/{block,store}/v1;
// run `just block_gen` / `just store_gen` to regenerate.
pub mod block;
pub mod store;
