// @generated by contracts/link-device/v1/gen_rust.zt; do not edit.
// Source contract: contracts/link-device/v1/schema.zt

pub const FORMAT_VERSION: u16 = 1;
pub const REQUEST_LEN: usize = 56;
pub const REPLY_LEN: usize = 24;
pub const LINK_MAGIC: u32 = 1145785932;
pub const MIN_FRAME_BYTES: usize = 60;
pub const MAX_FRAME_BYTES: usize = 1518;
pub const QUEUE_TX: u32 = 1;
pub const QUEUE_RX: u32 = 2;
pub const MIN_QUEUE_SLOTS: usize = 2;
pub const MAX_QUEUE_SLOTS: usize = 256;
pub const OP_TRANSMIT: u8 = 1;
pub const OP_PROVIDE_RECEIVE: u8 = 2;
pub const OP_QUERY_LINK: u8 = 3;
pub const OP_STATISTICS: u8 = 4;
pub const OP_RESET: u8 = 5;
pub const OP_CLOSE: u8 = 6;
pub const LINK_UNKNOWN: u8 = 0;
pub const LINK_DOWN: u8 = 1;
pub const LINK_UP: u8 = 2;
pub const KNOWN_REQUEST_FLAGS: u8 = 0;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OP: usize = 6;
pub const OFF_REQUEST_FLAGS: usize = 7;
pub const OFF_REQUEST_FRAME_LEN: usize = 8;
pub const OFF_REQUEST_RESERVED: usize = 10;
pub const OFF_REQUEST_PADDING: usize = 12;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireLinkRequest {
    pub magic: u32,
    pub version: u16,
    pub op: u8,
    pub flags: u8,
    pub frame_len: u16,
    pub reserved: [u8; 2],
    pub padding: [u8; 44],
}

impl WireLinkRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated link-device layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 2]
                    .try_into()
                    .expect("generated link-device layout"),
            ),
            op: buf[OFF_REQUEST_OP],
            flags: buf[OFF_REQUEST_FLAGS],
            frame_len: u16::from_le_bytes(
                buf[OFF_REQUEST_FRAME_LEN..OFF_REQUEST_FRAME_LEN + 2]
                    .try_into()
                    .expect("generated link-device layout"),
            ),
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 2]
                .try_into()
                .expect("generated link-device layout"),
            padding: buf[OFF_REQUEST_PADDING..OFF_REQUEST_PADDING + 44]
                .try_into()
                .expect("generated link-device layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 2]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OP] = self.op;
        buf[OFF_REQUEST_FLAGS] = self.flags;
        buf[OFF_REQUEST_FRAME_LEN..OFF_REQUEST_FRAME_LEN + 2]
            .copy_from_slice(&self.frame_len.to_le_bytes());
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 2].copy_from_slice(&self.reserved);
        buf[OFF_REQUEST_PADDING..OFF_REQUEST_PADDING + 44].copy_from_slice(&self.padding);
        buf
    }
}

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_OP: usize = 6;
pub const OFF_REPLY_LINK_STATE: usize = 7;
pub const OFF_REPLY_FRAME_LEN: usize = 8;
pub const OFF_REPLY_RESERVED: usize = 10;
pub const OFF_REPLY_TX_FRAMES: usize = 12;
pub const OFF_REPLY_RX_FRAMES: usize = 16;
pub const OFF_REPLY_DETAIL: usize = 20;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireLinkReply {
    pub magic: u32,
    pub version: u16,
    pub op: u8,
    pub link_state: u8,
    pub frame_len: u16,
    pub reserved: [u8; 2],
    pub tx_frames: u32,
    pub rx_frames: u32,
    pub detail: u32,
}

impl WireLinkReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated link-device layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 2]
                    .try_into()
                    .expect("generated link-device layout"),
            ),
            op: buf[OFF_REPLY_OP],
            link_state: buf[OFF_REPLY_LINK_STATE],
            frame_len: u16::from_le_bytes(
                buf[OFF_REPLY_FRAME_LEN..OFF_REPLY_FRAME_LEN + 2]
                    .try_into()
                    .expect("generated link-device layout"),
            ),
            reserved: buf[OFF_REPLY_RESERVED..OFF_REPLY_RESERVED + 2]
                .try_into()
                .expect("generated link-device layout"),
            tx_frames: u32::from_le_bytes(
                buf[OFF_REPLY_TX_FRAMES..OFF_REPLY_TX_FRAMES + 4]
                    .try_into()
                    .expect("generated link-device layout"),
            ),
            rx_frames: u32::from_le_bytes(
                buf[OFF_REPLY_RX_FRAMES..OFF_REPLY_RX_FRAMES + 4]
                    .try_into()
                    .expect("generated link-device layout"),
            ),
            detail: u32::from_le_bytes(
                buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 4]
                    .try_into()
                    .expect("generated link-device layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 2].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_OP] = self.op;
        buf[OFF_REPLY_LINK_STATE] = self.link_state;
        buf[OFF_REPLY_FRAME_LEN..OFF_REPLY_FRAME_LEN + 2]
            .copy_from_slice(&self.frame_len.to_le_bytes());
        buf[OFF_REPLY_RESERVED..OFF_REPLY_RESERVED + 2].copy_from_slice(&self.reserved);
        buf[OFF_REPLY_TX_FRAMES..OFF_REPLY_TX_FRAMES + 4]
            .copy_from_slice(&self.tx_frames.to_le_bytes());
        buf[OFF_REPLY_RX_FRAMES..OFF_REPLY_RX_FRAMES + 4]
            .copy_from_slice(&self.rx_frames.to_le_bytes());
        buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 4].copy_from_slice(&self.detail.to_le_bytes());
        buf
    }
}
