// @generated by contracts/mavlink-heartbeat/v1/gen_rust.zt; do not edit.
// Source contract: contracts/mavlink-heartbeat/v1/schema.zt

pub const STX: u8 = 253;
pub const HEADER_LEN: usize = 10;
pub const CHECKSUM_LEN: usize = 2;
pub const PAYLOAD_LEN: usize = 9;
pub const FRAME_LEN: usize = 21;
pub const MSG_ID: u32 = 0;
pub const CRC_EXTRA: u8 = 50;
pub const CRC_INIT: u16 = 65535;
pub const CRC_POLY: u16 = 33800;

pub const SYS_ID: u8 = 1;
pub const COMP_ID: u8 = 191;
pub const MAV_TYPE: u8 = 18;
pub const AUTOPILOT: u8 = 8;
pub const BASE_MODE: u8 = 0;
pub const CUSTOM_MODE: u32 = 0;
pub const SYSTEM_STATUS: u8 = 4;
pub const MAVLINK_VERSION: u8 = 3;

pub const VECTOR_SEQ_0: [u8; FRAME_LEN] = [
    253, 9, 0, 0, 0, 1, 191, 0, 0, 0, 0, 0, 0, 0, 18, 8, 0, 4, 3, 174, 198,
];
pub const VECTOR_SEQ_1: [u8; FRAME_LEN] = [
    253, 9, 0, 0, 1, 1, 191, 0, 0, 0, 0, 0, 0, 0, 18, 8, 0, 4, 3, 190, 72,
];
pub const VECTOR_SEQ_255: [u8; FRAME_LEN] = [
    253, 9, 0, 0, 255, 1, 191, 0, 0, 0, 0, 0, 0, 0, 18, 8, 0, 4, 3, 183, 124,
];

pub const OFF_FRAME_STX: usize = 0;
pub const OFF_FRAME_PAYLOAD_LEN: usize = 1;
pub const OFF_FRAME_INCOMPAT_FLAGS: usize = 2;
pub const OFF_FRAME_COMPAT_FLAGS: usize = 3;
pub const OFF_FRAME_SEQ: usize = 4;
pub const OFF_FRAME_SYSID: usize = 5;
pub const OFF_FRAME_COMPID: usize = 6;
pub const OFF_FRAME_MSGID: usize = 7;
pub const OFF_FRAME_CUSTOM_MODE: usize = 10;
pub const OFF_FRAME_MAV_TYPE: usize = 14;
pub const OFF_FRAME_AUTOPILOT: usize = 15;
pub const OFF_FRAME_BASE_MODE: usize = 16;
pub const OFF_FRAME_SYSTEM_STATUS: usize = 17;
pub const OFF_FRAME_MAVLINK_VERSION: usize = 18;
pub const OFF_FRAME_CHECKSUM: usize = 19;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireHeartbeat {
    pub stx: u8,
    pub payload_len: u8,
    pub incompat_flags: u8,
    pub compat_flags: u8,
    pub seq: u8,
    pub sysid: u8,
    pub compid: u8,
    pub msgid: [u8; 3],
    pub custom_mode: u32,
    pub mav_type: u8,
    pub autopilot: u8,
    pub base_mode: u8,
    pub system_status: u8,
    pub mavlink_version: u8,
    pub checksum: u16,
}

impl WireHeartbeat {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < FRAME_LEN {
            return None;
        }
        Some(Self {
            stx: buf[OFF_FRAME_STX],
            payload_len: buf[OFF_FRAME_PAYLOAD_LEN],
            incompat_flags: buf[OFF_FRAME_INCOMPAT_FLAGS],
            compat_flags: buf[OFF_FRAME_COMPAT_FLAGS],
            seq: buf[OFF_FRAME_SEQ],
            sysid: buf[OFF_FRAME_SYSID],
            compid: buf[OFF_FRAME_COMPID],
            msgid: buf[OFF_FRAME_MSGID..OFF_FRAME_MSGID + 3]
                .try_into()
                .expect("generated mavlink-heartbeat layout"),
            custom_mode: u32::from_le_bytes(
                buf[OFF_FRAME_CUSTOM_MODE..OFF_FRAME_CUSTOM_MODE + 4]
                    .try_into()
                    .expect("generated mavlink-heartbeat layout"),
            ),
            mav_type: buf[OFF_FRAME_MAV_TYPE],
            autopilot: buf[OFF_FRAME_AUTOPILOT],
            base_mode: buf[OFF_FRAME_BASE_MODE],
            system_status: buf[OFF_FRAME_SYSTEM_STATUS],
            mavlink_version: buf[OFF_FRAME_MAVLINK_VERSION],
            checksum: u16::from_le_bytes(
                buf[OFF_FRAME_CHECKSUM..OFF_FRAME_CHECKSUM + 2]
                    .try_into()
                    .expect("generated mavlink-heartbeat layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; FRAME_LEN] {
        let mut buf = [0u8; FRAME_LEN];
        buf[OFF_FRAME_STX] = self.stx;
        buf[OFF_FRAME_PAYLOAD_LEN] = self.payload_len;
        buf[OFF_FRAME_INCOMPAT_FLAGS] = self.incompat_flags;
        buf[OFF_FRAME_COMPAT_FLAGS] = self.compat_flags;
        buf[OFF_FRAME_SEQ] = self.seq;
        buf[OFF_FRAME_SYSID] = self.sysid;
        buf[OFF_FRAME_COMPID] = self.compid;
        buf[OFF_FRAME_MSGID..OFF_FRAME_MSGID + 3].copy_from_slice(&self.msgid);
        buf[OFF_FRAME_CUSTOM_MODE..OFF_FRAME_CUSTOM_MODE + 4]
            .copy_from_slice(&self.custom_mode.to_le_bytes());
        buf[OFF_FRAME_MAV_TYPE] = self.mav_type;
        buf[OFF_FRAME_AUTOPILOT] = self.autopilot;
        buf[OFF_FRAME_BASE_MODE] = self.base_mode;
        buf[OFF_FRAME_SYSTEM_STATUS] = self.system_status;
        buf[OFF_FRAME_MAVLINK_VERSION] = self.mavlink_version;
        buf[OFF_FRAME_CHECKSUM..OFF_FRAME_CHECKSUM + 2]
            .copy_from_slice(&self.checksum.to_le_bytes());
        buf
    }
}
