// @generated by contracts/network-service/v1/gen_rust.zt; do not edit.
// Source contract: contracts/network-service/v1/schema.zt

pub const FORMAT_VERSION: u16 = 1;
pub const REQUEST_BYTES: usize = 56;
pub const COMPLETION_BYTES: usize = 24;
pub const MAX_NAME_BYTES: usize = 24;
pub const NETWORK_MAGIC: u32 = 1414745678;
pub const OP_CONNECT: u8 = 1;
pub const OP_SEND: u8 = 2;
pub const OP_RECV: u8 = 3;
pub const OP_CLOSE: u8 = 4;
pub const OP_LISTEN: u8 = 5;
pub const OP_ACCEPT: u8 = 6;
pub const OP_RESOLVE: u8 = 7;
pub const TRANSPORT_NONE: u8 = 0;
pub const TRANSPORT_TCP: u8 = 1;
pub const TRANSPORT_UDP: u8 = 2;
pub const ADDRESS_NONE: u8 = 0;
pub const ADDRESS_IPV4: u8 = 1;
pub const ADDRESS_IPV6: u8 = 2;
pub const ADDRESS_DNS: u8 = 3;
pub const CAPABILITY_NONE: u8 = 0;
pub const CAPABILITY_TCP_CONNECTION: u8 = 1;
pub const CAPABILITY_UDP_ENDPOINT: u8 = 2;
pub const CAPABILITY_TCP_LISTENER: u8 = 3;
pub const CAPABILITY_DNS_RECORD: u8 = 4;
pub const FLAG_NONBLOCKING: u32 = 1;
pub const KNOWN_REQUEST_FLAGS: u32 = 1;
pub const FLAG_END_OF_STREAM: u32 = 1;
pub const KNOWN_COMPLETION_FLAGS: u32 = 1;

pub const LOAN_BYTES: usize = 64;
pub const LOAN_ROLE_RING: u8 = 1;
pub const LOAN_ROLE_DATA: u8 = 2;
pub const QUEUE_SLOTS: usize = 4;
pub const RING_PAGES: usize = 1;
pub const DATA_PAGES: usize = 1;
pub const RING_BYTES: usize = 4096;
pub const DATA_BYTES: usize = 4096;
pub const OP_ATTACH: u8 = 8;
pub const OP_ABORT: u8 = 9;
pub const STATUS_SUCCESS: i32 = 0;
pub const STATUS_DENIED: i32 = -1;
pub const STATUS_MALFORMED: i32 = -2;
pub const STATUS_UNSUPPORTED: i32 = -3;
pub const STATUS_WOULD_BLOCK: i32 = -4;
pub const STATUS_EXHAUSTED: i32 = -5;
pub const STATUS_REFUSED: i32 = -6;
pub const STATUS_TIMEOUT: i32 = -7;
pub const STATUS_RESET: i32 = -8;
pub const LAUNCH_BYTES: usize = 64;
pub const LAUNCH_PAYLOAD_BYTES: usize = 48;
pub const LAUNCH_URL_BYTES: usize = 2048;
pub const LAUNCH_SEED: u8 = 1;
pub const LAUNCH_URL: u8 = 2;
pub const OFF_LAUNCH_MAGIC: usize = 0;
pub const OFF_LAUNCH_VERSION: usize = 4;
pub const OFF_LAUNCH_KIND: usize = 6;
pub const OFF_LAUNCH_RESERVED: usize = 7;
pub const OFF_LAUNCH_TOTAL_LEN: usize = 8;
pub const OFF_LAUNCH_OFFSET: usize = 10;
pub const OFF_LAUNCH_LENGTH: usize = 12;
pub const OFF_LAUNCH_RESERVED2: usize = 14;
pub const OFF_LAUNCH_PAYLOAD: usize = 16;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireNetworkLaunch {
    pub magic: u32,
    pub version: u16,
    pub kind: u8,
    pub reserved: u8,
    pub total_len: u16,
    pub offset: u16,
    pub length: u16,
    pub reserved2: [u8; 2],
    pub payload: [u8; 48],
}

impl WireNetworkLaunch {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < LAUNCH_BYTES {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_LAUNCH_MAGIC..OFF_LAUNCH_MAGIC + 4]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_LAUNCH_VERSION..OFF_LAUNCH_VERSION + 2]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            kind: buf[OFF_LAUNCH_KIND],
            reserved: buf[OFF_LAUNCH_RESERVED],
            total_len: u16::from_le_bytes(
                buf[OFF_LAUNCH_TOTAL_LEN..OFF_LAUNCH_TOTAL_LEN + 2]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            offset: u16::from_le_bytes(
                buf[OFF_LAUNCH_OFFSET..OFF_LAUNCH_OFFSET + 2]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            length: u16::from_le_bytes(
                buf[OFF_LAUNCH_LENGTH..OFF_LAUNCH_LENGTH + 2]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            reserved2: buf[OFF_LAUNCH_RESERVED2..OFF_LAUNCH_RESERVED2 + 2]
                .try_into()
                .expect("generated network-service layout"),
            payload: buf[OFF_LAUNCH_PAYLOAD..OFF_LAUNCH_PAYLOAD + 48]
                .try_into()
                .expect("generated network-service layout"),
        })
    }

    pub fn encode(self) -> [u8; LAUNCH_BYTES] {
        let mut buf = [0u8; LAUNCH_BYTES];
        buf[OFF_LAUNCH_MAGIC..OFF_LAUNCH_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_LAUNCH_VERSION..OFF_LAUNCH_VERSION + 2]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_LAUNCH_KIND] = self.kind;
        buf[OFF_LAUNCH_RESERVED] = self.reserved;
        buf[OFF_LAUNCH_TOTAL_LEN..OFF_LAUNCH_TOTAL_LEN + 2]
            .copy_from_slice(&self.total_len.to_le_bytes());
        buf[OFF_LAUNCH_OFFSET..OFF_LAUNCH_OFFSET + 2].copy_from_slice(&self.offset.to_le_bytes());
        buf[OFF_LAUNCH_LENGTH..OFF_LAUNCH_LENGTH + 2].copy_from_slice(&self.length.to_le_bytes());
        buf[OFF_LAUNCH_RESERVED2..OFF_LAUNCH_RESERVED2 + 2].copy_from_slice(&self.reserved2);
        buf[OFF_LAUNCH_PAYLOAD..OFF_LAUNCH_PAYLOAD + 48].copy_from_slice(&self.payload);
        buf
    }
}

pub const OFF_LOAN_MAGIC: usize = 0;
pub const OFF_LOAN_VERSION: usize = 4;
pub const OFF_LOAN_ROLE: usize = 6;
pub const OFF_LOAN_RESERVED0: usize = 7;
pub const OFF_LOAN_BUFFER: usize = 8;
pub const OFF_LOAN_LEASE: usize = 16;
pub const OFF_LOAN_LENGTH: usize = 24;
pub const OFF_LOAN_RESERVED: usize = 32;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireNetworkLoan {
    pub magic: u32,
    pub version: u16,
    pub role: u8,
    pub reserved0: [u8; 1],
    pub buffer: u64,
    pub lease: u64,
    pub length: u64,
    pub reserved: [u8; 32],
}

impl WireNetworkLoan {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < LOAN_BYTES {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_LOAN_MAGIC..OFF_LOAN_MAGIC + 4]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_LOAN_VERSION..OFF_LOAN_VERSION + 2]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            role: buf[OFF_LOAN_ROLE],
            reserved0: buf[OFF_LOAN_RESERVED0..OFF_LOAN_RESERVED0 + 1]
                .try_into()
                .expect("generated network-service layout"),
            buffer: u64::from_le_bytes(
                buf[OFF_LOAN_BUFFER..OFF_LOAN_BUFFER + 8]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            lease: u64::from_le_bytes(
                buf[OFF_LOAN_LEASE..OFF_LOAN_LEASE + 8]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            length: u64::from_le_bytes(
                buf[OFF_LOAN_LENGTH..OFF_LOAN_LENGTH + 8]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            reserved: buf[OFF_LOAN_RESERVED..OFF_LOAN_RESERVED + 32]
                .try_into()
                .expect("generated network-service layout"),
        })
    }

    pub fn encode(self) -> [u8; LOAN_BYTES] {
        let mut buf = [0u8; LOAN_BYTES];
        buf[OFF_LOAN_MAGIC..OFF_LOAN_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_LOAN_VERSION..OFF_LOAN_VERSION + 2].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_LOAN_ROLE] = self.role;
        buf[OFF_LOAN_RESERVED0..OFF_LOAN_RESERVED0 + 1].copy_from_slice(&self.reserved0);
        buf[OFF_LOAN_BUFFER..OFF_LOAN_BUFFER + 8].copy_from_slice(&self.buffer.to_le_bytes());
        buf[OFF_LOAN_LEASE..OFF_LOAN_LEASE + 8].copy_from_slice(&self.lease.to_le_bytes());
        buf[OFF_LOAN_LENGTH..OFF_LOAN_LENGTH + 8].copy_from_slice(&self.length.to_le_bytes());
        buf[OFF_LOAN_RESERVED..OFF_LOAN_RESERVED + 32].copy_from_slice(&self.reserved);
        buf
    }
}

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OP: usize = 6;
pub const OFF_REQUEST_TRANSPORT: usize = 7;
pub const OFF_REQUEST_FLAGS: usize = 8;
pub const OFF_REQUEST_PORT: usize = 12;
pub const OFF_REQUEST_NAME_LEN: usize = 14;
pub const OFF_REQUEST_CAPABILITY: usize = 16;
pub const OFF_REQUEST_ADDRESS_KIND: usize = 24;
pub const OFF_REQUEST_RESERVED: usize = 25;
pub const OFF_REQUEST_ENDPOINT: usize = 32;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireNetworkRequest {
    pub magic: u32,
    pub version: u16,
    pub op: u8,
    pub transport: u8,
    pub flags: u32,
    pub port: u16,
    pub name_len: u16,
    pub capability: u64,
    pub address_kind: u8,
    pub reserved: [u8; 7],
    pub endpoint: [u8; 24],
}

impl WireNetworkRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_BYTES {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 2]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            op: buf[OFF_REQUEST_OP],
            transport: buf[OFF_REQUEST_TRANSPORT],
            flags: u32::from_le_bytes(
                buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            port: u16::from_le_bytes(
                buf[OFF_REQUEST_PORT..OFF_REQUEST_PORT + 2]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            name_len: u16::from_le_bytes(
                buf[OFF_REQUEST_NAME_LEN..OFF_REQUEST_NAME_LEN + 2]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            capability: u64::from_le_bytes(
                buf[OFF_REQUEST_CAPABILITY..OFF_REQUEST_CAPABILITY + 8]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            address_kind: buf[OFF_REQUEST_ADDRESS_KIND],
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 7]
                .try_into()
                .expect("generated network-service layout"),
            endpoint: buf[OFF_REQUEST_ENDPOINT..OFF_REQUEST_ENDPOINT + 24]
                .try_into()
                .expect("generated network-service layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_BYTES] {
        let mut buf = [0u8; REQUEST_BYTES];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 2]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OP] = self.op;
        buf[OFF_REQUEST_TRANSPORT] = self.transport;
        buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_REQUEST_PORT..OFF_REQUEST_PORT + 2].copy_from_slice(&self.port.to_le_bytes());
        buf[OFF_REQUEST_NAME_LEN..OFF_REQUEST_NAME_LEN + 2]
            .copy_from_slice(&self.name_len.to_le_bytes());
        buf[OFF_REQUEST_CAPABILITY..OFF_REQUEST_CAPABILITY + 8]
            .copy_from_slice(&self.capability.to_le_bytes());
        buf[OFF_REQUEST_ADDRESS_KIND] = self.address_kind;
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 7].copy_from_slice(&self.reserved);
        buf[OFF_REQUEST_ENDPOINT..OFF_REQUEST_ENDPOINT + 24].copy_from_slice(&self.endpoint);
        buf
    }
}

pub const OFF_COMPLETION_MAGIC: usize = 0;
pub const OFF_COMPLETION_VERSION: usize = 4;
pub const OFF_COMPLETION_OP: usize = 6;
pub const OFF_COMPLETION_CAPABILITY_KIND: usize = 7;
pub const OFF_COMPLETION_STATUS_DETAIL: usize = 8;
pub const OFF_COMPLETION_FLAGS: usize = 12;
pub const OFF_COMPLETION_CAPABILITY: usize = 16;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireNetworkCompletion {
    pub magic: u32,
    pub version: u16,
    pub op: u8,
    pub capability_kind: u8,
    pub status_detail: i32,
    pub flags: u32,
    pub capability: u64,
}

impl WireNetworkCompletion {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < COMPLETION_BYTES {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_COMPLETION_MAGIC..OFF_COMPLETION_MAGIC + 4]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_COMPLETION_VERSION..OFF_COMPLETION_VERSION + 2]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            op: buf[OFF_COMPLETION_OP],
            capability_kind: buf[OFF_COMPLETION_CAPABILITY_KIND],
            status_detail: i32::from_le_bytes(
                buf[OFF_COMPLETION_STATUS_DETAIL..OFF_COMPLETION_STATUS_DETAIL + 4]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_COMPLETION_FLAGS..OFF_COMPLETION_FLAGS + 4]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
            capability: u64::from_le_bytes(
                buf[OFF_COMPLETION_CAPABILITY..OFF_COMPLETION_CAPABILITY + 8]
                    .try_into()
                    .expect("generated network-service layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; COMPLETION_BYTES] {
        let mut buf = [0u8; COMPLETION_BYTES];
        buf[OFF_COMPLETION_MAGIC..OFF_COMPLETION_MAGIC + 4]
            .copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_COMPLETION_VERSION..OFF_COMPLETION_VERSION + 2]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_COMPLETION_OP] = self.op;
        buf[OFF_COMPLETION_CAPABILITY_KIND] = self.capability_kind;
        buf[OFF_COMPLETION_STATUS_DETAIL..OFF_COMPLETION_STATUS_DETAIL + 4]
            .copy_from_slice(&self.status_detail.to_le_bytes());
        buf[OFF_COMPLETION_FLAGS..OFF_COMPLETION_FLAGS + 4]
            .copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_COMPLETION_CAPABILITY..OFF_COMPLETION_CAPABILITY + 8]
            .copy_from_slice(&self.capability.to_le_bytes());
        buf
    }
}
