// @generated by contracts/powerbox/v1/gen_rust.zt; do not edit.
// Source contract: contracts/powerbox/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const POWERBOX_MAGIC: u32 = 1346522187;
pub const REQUEST_LEN: usize = 64;
pub const REPLY_LEN: usize = 64;
pub const MAX_PURPOSE_BYTES: usize = 40;
pub const OBJECT_KIND_FILE: u8 = 1;
pub const REPLY_FLAG_SELECTED: u8 = 1;
pub const REPLY_FLAG_CANCELLED: u8 = 2;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OBJECT_KIND: usize = 8;
pub const OFF_REQUEST_RESERVED0: usize = 9;
pub const OFF_REQUEST_PURPOSE_LEN: usize = 10;
pub const OFF_REQUEST_REQUESTED_RIGHTS: usize = 12;
pub const OFF_REQUEST_PURPOSE: usize = 16;
pub const OFF_REQUEST_RESERVED: usize = 56;

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_FLAGS: usize = 12;
pub const OFF_REPLY_OBJECT_KIND: usize = 13;
pub const OFF_REPLY_PURPOSE_LEN: usize = 14;
pub const OFF_REPLY_RESERVED0: usize = 16;
pub const OFF_REPLY_GRANTED_RIGHTS: usize = 20;
pub const OFF_REPLY_EVENT_ID: usize = 24;
pub const OFF_REPLY_SELECTED_PATH: usize = 32;
pub const OFF_REPLY_PURPOSE: usize = 48;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WirePowerboxRequest {
    pub magic: u32,
    pub version: u32,
    pub object_kind: u8,
    pub reserved0: u8,
    pub purpose_len: u16,
    pub requested_rights: u32,
    pub purpose: [u8; 40],
    pub reserved: [u8; 8],
}

impl WirePowerboxRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            object_kind: buf[OFF_REQUEST_OBJECT_KIND],
            reserved0: buf[OFF_REQUEST_RESERVED0],
            purpose_len: u16::from_le_bytes(
                buf[OFF_REQUEST_PURPOSE_LEN..OFF_REQUEST_PURPOSE_LEN + 2]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            requested_rights: u32::from_le_bytes(
                buf[OFF_REQUEST_REQUESTED_RIGHTS..OFF_REQUEST_REQUESTED_RIGHTS + 4]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            purpose: buf[OFF_REQUEST_PURPOSE..OFF_REQUEST_PURPOSE + 40]
                .try_into()
                .expect("generated powerbox layout"),
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 8]
                .try_into()
                .expect("generated powerbox layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OBJECT_KIND] = self.object_kind;
        buf[OFF_REQUEST_RESERVED0] = self.reserved0;
        buf[OFF_REQUEST_PURPOSE_LEN..OFF_REQUEST_PURPOSE_LEN + 2]
            .copy_from_slice(&self.purpose_len.to_le_bytes());
        buf[OFF_REQUEST_REQUESTED_RIGHTS..OFF_REQUEST_REQUESTED_RIGHTS + 4]
            .copy_from_slice(&self.requested_rights.to_le_bytes());
        buf[OFF_REQUEST_PURPOSE..OFF_REQUEST_PURPOSE + 40].copy_from_slice(&self.purpose);
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 8].copy_from_slice(&self.reserved);
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WirePowerboxReply {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub flags: u8,
    pub object_kind: u8,
    pub purpose_len: u16,
    pub reserved0: u32,
    pub granted_rights: u32,
    pub event_id: u64,
    pub selected_path: [u8; 16],
    pub purpose: [u8; 16],
}

impl WirePowerboxReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            flags: buf[OFF_REPLY_FLAGS],
            object_kind: buf[OFF_REPLY_OBJECT_KIND],
            purpose_len: u16::from_le_bytes(
                buf[OFF_REPLY_PURPOSE_LEN..OFF_REPLY_PURPOSE_LEN + 2]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            reserved0: u32::from_le_bytes(
                buf[OFF_REPLY_RESERVED0..OFF_REPLY_RESERVED0 + 4]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            granted_rights: u32::from_le_bytes(
                buf[OFF_REPLY_GRANTED_RIGHTS..OFF_REPLY_GRANTED_RIGHTS + 4]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            event_id: u64::from_le_bytes(
                buf[OFF_REPLY_EVENT_ID..OFF_REPLY_EVENT_ID + 8]
                    .try_into()
                    .expect("generated powerbox layout"),
            ),
            selected_path: buf[OFF_REPLY_SELECTED_PATH..OFF_REPLY_SELECTED_PATH + 16]
                .try_into()
                .expect("generated powerbox layout"),
            purpose: buf[OFF_REPLY_PURPOSE..OFF_REPLY_PURPOSE + 16]
                .try_into()
                .expect("generated powerbox layout"),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_FLAGS] = self.flags;
        buf[OFF_REPLY_OBJECT_KIND] = self.object_kind;
        buf[OFF_REPLY_PURPOSE_LEN..OFF_REPLY_PURPOSE_LEN + 2]
            .copy_from_slice(&self.purpose_len.to_le_bytes());
        buf[OFF_REPLY_RESERVED0..OFF_REPLY_RESERVED0 + 4]
            .copy_from_slice(&self.reserved0.to_le_bytes());
        buf[OFF_REPLY_GRANTED_RIGHTS..OFF_REPLY_GRANTED_RIGHTS + 4]
            .copy_from_slice(&self.granted_rights.to_le_bytes());
        buf[OFF_REPLY_EVENT_ID..OFF_REPLY_EVENT_ID + 8]
            .copy_from_slice(&self.event_id.to_le_bytes());
        buf[OFF_REPLY_SELECTED_PATH..OFF_REPLY_SELECTED_PATH + 16]
            .copy_from_slice(&self.selected_path);
        buf[OFF_REPLY_PURPOSE..OFF_REPLY_PURPOSE + 16].copy_from_slice(&self.purpose);
        buf
    }
}
