// @generated by contracts/private-memory-probe/v1/gen_rust.zt; do not edit.
pub const FORMAT_VERSION: u32 = 1;
pub const MESSAGE_LEN: usize = 64;
pub const GROW: u32 = 1;
pub const VERIFY: u32 = 2;
pub const FAULT: u32 = 3;
pub const FINISH: u32 = 4;
pub const ACKNOWLEDGE: u32 = 5;
pub const READ_FOREIGN: u32 = 6;
pub const WRITE_FOREIGN: u32 = 7;
pub const EXECUTE_PRIVATE: u32 = 8;
pub const LOAN_READY: u32 = 9;
pub const LOAN_OFFER: u32 = 10;
pub const LOAN_SETTLED: u32 = 11;
pub const STRESS_GROW: u32 = 12;
pub const STRESS_REFUSE: u32 = 13;
pub const STRESS_VERIFY: u32 = 14;
pub const OFF_MESSAGE_VERSION: usize = 0;
pub const OFF_MESSAGE_OPERATION: usize = 4;
pub const OFF_MESSAGE_HOLDER: usize = 8;
pub const OFF_MESSAGE_INCARNATION: usize = 12;
pub const OFF_MESSAGE_ADDRESS: usize = 16;
pub const OFF_MESSAGE_RESERVED: usize = 24;
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireMessage {
    pub version: u32,
    pub operation: u32,
    pub holder: u32,
    pub incarnation: u32,
    pub address: u64,
    pub reserved: [u8; 40],
}

impl WireMessage {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < MESSAGE_LEN {
            return None;
        }
        Some(Self {
            version: u32::from_le_bytes(
                buf[OFF_MESSAGE_VERSION..OFF_MESSAGE_VERSION + 4]
                    .try_into()
                    .expect("generated private-memory-probe layout"),
            ),
            operation: u32::from_le_bytes(
                buf[OFF_MESSAGE_OPERATION..OFF_MESSAGE_OPERATION + 4]
                    .try_into()
                    .expect("generated private-memory-probe layout"),
            ),
            holder: u32::from_le_bytes(
                buf[OFF_MESSAGE_HOLDER..OFF_MESSAGE_HOLDER + 4]
                    .try_into()
                    .expect("generated private-memory-probe layout"),
            ),
            incarnation: u32::from_le_bytes(
                buf[OFF_MESSAGE_INCARNATION..OFF_MESSAGE_INCARNATION + 4]
                    .try_into()
                    .expect("generated private-memory-probe layout"),
            ),
            address: u64::from_le_bytes(
                buf[OFF_MESSAGE_ADDRESS..OFF_MESSAGE_ADDRESS + 8]
                    .try_into()
                    .expect("generated private-memory-probe layout"),
            ),
            reserved: buf[OFF_MESSAGE_RESERVED..OFF_MESSAGE_RESERVED + 40]
                .try_into()
                .expect("generated private-memory-probe layout"),
        })
    }

    pub fn encode(self) -> [u8; MESSAGE_LEN] {
        let mut buf = [0u8; MESSAGE_LEN];
        buf[OFF_MESSAGE_VERSION..OFF_MESSAGE_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_MESSAGE_OPERATION..OFF_MESSAGE_OPERATION + 4]
            .copy_from_slice(&self.operation.to_le_bytes());
        buf[OFF_MESSAGE_HOLDER..OFF_MESSAGE_HOLDER + 4].copy_from_slice(&self.holder.to_le_bytes());
        buf[OFF_MESSAGE_INCARNATION..OFF_MESSAGE_INCARNATION + 4]
            .copy_from_slice(&self.incarnation.to_le_bytes());
        buf[OFF_MESSAGE_ADDRESS..OFF_MESSAGE_ADDRESS + 8]
            .copy_from_slice(&self.address.to_le_bytes());
        buf[OFF_MESSAGE_RESERVED..OFF_MESSAGE_RESERVED + 40].copy_from_slice(&self.reserved);
        buf
    }
}
