// @generated by contracts/pwm-servo/v1/gen_rust.zt; do not edit.
// Source contract: contracts/pwm-servo/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const PWM_SERVO_MAGIC: u32 = 1397577552;
pub const REQUEST_LEN: usize = 32;
pub const REPLY_LEN: usize = 16;
pub const MAX_CHANNEL: u32 = 5;
pub const MIN_PERIOD_US: u32 = 2000;
pub const MAX_PERIOD_US: u32 = 20000;
pub const MIN_PULSE_US: u32 = 1000;
pub const MAX_PULSE_US: u32 = 2000;
pub const PULSE_DISABLE: u32 = 0;
pub const CLOCK_HZ: u32 = 1000000;
pub const FAILSAFE_NS: u64 = 10000000000;

pub const STATUS_OK: i32 = 0;
pub const STATUS_BAD_CHANNEL: i32 = -1;
pub const STATUS_BAD_PERIOD: i32 = -2;
pub const STATUS_BAD_PULSE: i32 = -3;
pub const STATUS_NO_DEVICE: i32 = -4;
pub const STATUS_DEVICE_ERROR: i32 = -5;
pub const STATUS_MALFORMED: i32 = -6;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_CHANNEL: usize = 8;
pub const OFF_REQUEST_PERIOD_US: usize = 12;
pub const OFF_REQUEST_PULSE_US: usize = 16;
pub const OFF_REQUEST_FLAGS: usize = 20;
pub const OFF_REQUEST_RESERVED: usize = 24;

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_DETAIL: usize = 12;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WirePwmServoRequest {
    pub magic: u32,
    pub version: u32,
    pub channel: u32,
    pub period_us: u32,
    pub pulse_us: u32,
    pub flags: u32,
    pub reserved: [u8; 8],
}

impl WirePwmServoRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
            channel: u32::from_le_bytes(
                buf[OFF_REQUEST_CHANNEL..OFF_REQUEST_CHANNEL + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
            period_us: u32::from_le_bytes(
                buf[OFF_REQUEST_PERIOD_US..OFF_REQUEST_PERIOD_US + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
            pulse_us: u32::from_le_bytes(
                buf[OFF_REQUEST_PULSE_US..OFF_REQUEST_PULSE_US + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 8]
                .try_into()
                .expect("generated pwm_servo layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_CHANNEL..OFF_REQUEST_CHANNEL + 4]
            .copy_from_slice(&self.channel.to_le_bytes());
        buf[OFF_REQUEST_PERIOD_US..OFF_REQUEST_PERIOD_US + 4]
            .copy_from_slice(&self.period_us.to_le_bytes());
        buf[OFF_REQUEST_PULSE_US..OFF_REQUEST_PULSE_US + 4]
            .copy_from_slice(&self.pulse_us.to_le_bytes());
        buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 8].copy_from_slice(&self.reserved);
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WirePwmServoReply {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub detail: u32,
}

impl WirePwmServoReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
            detail: u32::from_le_bytes(
                buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 4]
                    .try_into()
                    .expect("generated pwm_servo layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 4].copy_from_slice(&self.detail.to_le_bytes());
        buf
    }
}
