// @generated by contracts/sample-descriptor/v1/gen_rust.zt; do not edit.
// Source contract: contracts/sample-descriptor/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const SAMPLE_DESCRIPTOR_MAGIC: u32 = 1146113363;
pub const DESCRIPTOR_LEN: usize = 64;
pub const MAX_SAMPLE_BYTES: usize = 1048576;
pub const CAPABILITY_KIND_LOAN: u32 = 1;
pub const FLAG_LAST: u32 = 1;
pub const KNOWN_FLAGS: u32 = 1;

pub const OFF_DESCRIPTOR_MAGIC: usize = 0;
pub const OFF_DESCRIPTOR_VERSION: usize = 4;
pub const OFF_DESCRIPTOR_FLAGS: usize = 8;
pub const OFF_DESCRIPTOR_CAPABILITY_KIND: usize = 12;
pub const OFF_DESCRIPTOR_LOAN_ID: usize = 16;
pub const OFF_DESCRIPTOR_OFFSET: usize = 24;
pub const OFF_DESCRIPTOR_LENGTH: usize = 32;
pub const OFF_DESCRIPTOR_TYPE_IDENTITY: usize = 40;
pub const OFF_DESCRIPTOR_SEQUENCE: usize = 48;
pub const OFF_DESCRIPTOR_RESERVED: usize = 56;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireSampleDescriptor {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub capability_kind: u32,
    pub loan_id: u64,
    pub offset: u64,
    pub length: u64,
    pub type_identity: u64,
    pub sequence: u64,
    pub reserved: [u8; 8],
}

impl WireSampleDescriptor {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < DESCRIPTOR_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_DESCRIPTOR_MAGIC..OFF_DESCRIPTOR_MAGIC + 4]
                    .try_into()
                    .expect("generated sample-descriptor layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_DESCRIPTOR_VERSION..OFF_DESCRIPTOR_VERSION + 4]
                    .try_into()
                    .expect("generated sample-descriptor layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_DESCRIPTOR_FLAGS..OFF_DESCRIPTOR_FLAGS + 4]
                    .try_into()
                    .expect("generated sample-descriptor layout"),
            ),
            capability_kind: u32::from_le_bytes(
                buf[OFF_DESCRIPTOR_CAPABILITY_KIND..OFF_DESCRIPTOR_CAPABILITY_KIND + 4]
                    .try_into()
                    .expect("generated sample-descriptor layout"),
            ),
            loan_id: u64::from_le_bytes(
                buf[OFF_DESCRIPTOR_LOAN_ID..OFF_DESCRIPTOR_LOAN_ID + 8]
                    .try_into()
                    .expect("generated sample-descriptor layout"),
            ),
            offset: u64::from_le_bytes(
                buf[OFF_DESCRIPTOR_OFFSET..OFF_DESCRIPTOR_OFFSET + 8]
                    .try_into()
                    .expect("generated sample-descriptor layout"),
            ),
            length: u64::from_le_bytes(
                buf[OFF_DESCRIPTOR_LENGTH..OFF_DESCRIPTOR_LENGTH + 8]
                    .try_into()
                    .expect("generated sample-descriptor layout"),
            ),
            type_identity: u64::from_le_bytes(
                buf[OFF_DESCRIPTOR_TYPE_IDENTITY..OFF_DESCRIPTOR_TYPE_IDENTITY + 8]
                    .try_into()
                    .expect("generated sample-descriptor layout"),
            ),
            sequence: u64::from_le_bytes(
                buf[OFF_DESCRIPTOR_SEQUENCE..OFF_DESCRIPTOR_SEQUENCE + 8]
                    .try_into()
                    .expect("generated sample-descriptor layout"),
            ),
            reserved: buf[OFF_DESCRIPTOR_RESERVED..OFF_DESCRIPTOR_RESERVED + 8]
                .try_into()
                .expect("generated sample-descriptor layout"),
        })
    }

    pub fn encode(self) -> [u8; DESCRIPTOR_LEN] {
        let mut buf = [0u8; DESCRIPTOR_LEN];
        buf[OFF_DESCRIPTOR_MAGIC..OFF_DESCRIPTOR_MAGIC + 4]
            .copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_DESCRIPTOR_VERSION..OFF_DESCRIPTOR_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_DESCRIPTOR_FLAGS..OFF_DESCRIPTOR_FLAGS + 4]
            .copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_DESCRIPTOR_CAPABILITY_KIND..OFF_DESCRIPTOR_CAPABILITY_KIND + 4]
            .copy_from_slice(&self.capability_kind.to_le_bytes());
        buf[OFF_DESCRIPTOR_LOAN_ID..OFF_DESCRIPTOR_LOAN_ID + 8]
            .copy_from_slice(&self.loan_id.to_le_bytes());
        buf[OFF_DESCRIPTOR_OFFSET..OFF_DESCRIPTOR_OFFSET + 8]
            .copy_from_slice(&self.offset.to_le_bytes());
        buf[OFF_DESCRIPTOR_LENGTH..OFF_DESCRIPTOR_LENGTH + 8]
            .copy_from_slice(&self.length.to_le_bytes());
        buf[OFF_DESCRIPTOR_TYPE_IDENTITY..OFF_DESCRIPTOR_TYPE_IDENTITY + 8]
            .copy_from_slice(&self.type_identity.to_le_bytes());
        buf[OFF_DESCRIPTOR_SEQUENCE..OFF_DESCRIPTOR_SEQUENCE + 8]
            .copy_from_slice(&self.sequence.to_le_bytes());
        buf[OFF_DESCRIPTOR_RESERVED..OFF_DESCRIPTOR_RESERVED + 8].copy_from_slice(&self.reserved);
        buf
    }
}
