// @generated by contracts/serial-device/v1/gen_rust.zt; do not edit.
// Source contract: contracts/serial-device/v1/schema.zt

pub const FORMAT_VERSION: u16 = 1;
pub const SERIAL_MAGIC: u32 = 1447318099;
pub const REQUEST_LEN: usize = 64;
pub const REPLY_LEN: usize = 16;
pub const MAX_PAYLOAD: usize = 52;
pub const OP_WRITE: u8 = 1;
pub const KNOWN_REQUEST_FLAGS: u8 = 0;

pub const STATUS_OK: i32 = 0;
pub const STATUS_BAD_LENGTH: i32 = -1;
pub const STATUS_BAD_OP: i32 = -2;
pub const STATUS_NO_DEVICE: i32 = -3;
pub const STATUS_DEVICE_ERROR: i32 = -4;
pub const STATUS_TIMEOUT: i32 = -5;
pub const STATUS_MALFORMED: i32 = -6;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OP: usize = 6;
pub const OFF_REQUEST_FLAGS: usize = 7;
pub const OFF_REQUEST_LENGTH: usize = 8;
pub const OFF_REQUEST_RESERVED: usize = 10;
pub const OFF_REQUEST_PAYLOAD: usize = 12;

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_BYTES_WRITTEN: usize = 6;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_DETAIL: usize = 12;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireSerialRequest {
    pub magic: u32,
    pub version: u16,
    pub op: u8,
    pub flags: u8,
    pub length: u16,
    pub reserved: [u8; 2],
    pub payload: [u8; 52],
}

impl WireSerialRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated serial-device layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 2]
                    .try_into()
                    .expect("generated serial-device layout"),
            ),
            op: buf[OFF_REQUEST_OP],
            flags: buf[OFF_REQUEST_FLAGS],
            length: u16::from_le_bytes(
                buf[OFF_REQUEST_LENGTH..OFF_REQUEST_LENGTH + 2]
                    .try_into()
                    .expect("generated serial-device layout"),
            ),
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 2]
                .try_into()
                .expect("generated serial-device layout"),
            payload: buf[OFF_REQUEST_PAYLOAD..OFF_REQUEST_PAYLOAD + 52]
                .try_into()
                .expect("generated serial-device layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 2]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OP] = self.op;
        buf[OFF_REQUEST_FLAGS] = self.flags;
        buf[OFF_REQUEST_LENGTH..OFF_REQUEST_LENGTH + 2].copy_from_slice(&self.length.to_le_bytes());
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 2].copy_from_slice(&self.reserved);
        buf[OFF_REQUEST_PAYLOAD..OFF_REQUEST_PAYLOAD + 52].copy_from_slice(&self.payload);
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireSerialReply {
    pub magic: u32,
    pub version: u16,
    pub bytes_written: u16,
    pub status: i32,
    pub detail: u32,
}

impl WireSerialReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated serial-device layout"),
            ),
            version: u16::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 2]
                    .try_into()
                    .expect("generated serial-device layout"),
            ),
            bytes_written: u16::from_le_bytes(
                buf[OFF_REPLY_BYTES_WRITTEN..OFF_REPLY_BYTES_WRITTEN + 2]
                    .try_into()
                    .expect("generated serial-device layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated serial-device layout"),
            ),
            detail: u32::from_le_bytes(
                buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 4]
                    .try_into()
                    .expect("generated serial-device layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 2].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_BYTES_WRITTEN..OFF_REPLY_BYTES_WRITTEN + 2]
            .copy_from_slice(&self.bytes_written.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 4].copy_from_slice(&self.detail.to_le_bytes());
        buf
    }
}
