// @generated by contracts/spawn/v1/gen_rust.zt; do not edit.
// Source contract: contracts/spawn/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const SPAWN_MAGIC: u32 = 1313559123;
pub const REQUEST_LEN: usize = 64;
pub const REPLY_LEN: usize = 64;
pub const MAX_ARGUMENTS: usize = 8;
pub const MAX_ARGUMENT_BYTES: usize = 8;
pub const MAX_ENVIRONMENT: usize = 8;
pub const MAX_ENVIRONMENT_BYTES: usize = 8;
pub const MAX_GRANTS: usize = 1;
pub const MAX_COMMAND_BYTES: usize = 16;

pub const CAPABILITY_ROLE_WORKING_DIRECTORY: u8 = 1;
pub const CAPABILITY_ROLE_STDIN: u8 = 2;
pub const CAPABILITY_ROLE_STDOUT: u8 = 4;
pub const CAPABILITY_ROLE_STDERR: u8 = 8;
pub const CAPABILITY_ROLE_GRANT: u8 = 16;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_FLAGS: usize = 8;
pub const OFF_REQUEST_COMMAND_LEN: usize = 12;
pub const OFF_REQUEST_ARGUMENT_COUNT: usize = 14;
pub const OFF_REQUEST_ENVIRONMENT_COUNT: usize = 15;
pub const OFF_REQUEST_CAPABILITY_ROLES: usize = 16;
pub const OFF_REQUEST_CLIENT_BUDGET: usize = 17;
pub const OFF_REQUEST_COMMAND: usize = 18;
pub const OFF_REQUEST_ARGUMENTS: usize = 34;
pub const OFF_REQUEST_ENVIRONMENT: usize = 42;
pub const OFF_REQUEST_GRANT_RIGHTS: usize = 50;
pub const OFF_REQUEST_RESERVED: usize = 54;

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_TERMINATION_KIND: usize = 12;
pub const OFF_REPLY_TASK_ID: usize = 16;
pub const OFF_REPLY_SUPERVISION_SLOT: usize = 24;
pub const OFF_REPLY_DETAIL: usize = 28;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireSpawnRequest {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub command_len: u16,
    pub argument_count: u8,
    pub environment_count: u8,
    pub capability_roles: u8,
    pub client_budget: u8,
    pub command: [u8; 16],
    pub arguments: [u8; 8],
    pub environment: [u8; 8],
    pub grant_rights: u32,
    pub reserved: [u8; 6],
}

impl WireSpawnRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            command_len: u16::from_le_bytes(
                buf[OFF_REQUEST_COMMAND_LEN..OFF_REQUEST_COMMAND_LEN + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            argument_count: buf[OFF_REQUEST_ARGUMENT_COUNT],
            environment_count: buf[OFF_REQUEST_ENVIRONMENT_COUNT],
            capability_roles: buf[OFF_REQUEST_CAPABILITY_ROLES],
            client_budget: buf[OFF_REQUEST_CLIENT_BUDGET],
            command: buf[OFF_REQUEST_COMMAND..OFF_REQUEST_COMMAND + 16]
                .try_into()
                .expect("generated spawn layout"),
            arguments: buf[OFF_REQUEST_ARGUMENTS..OFF_REQUEST_ARGUMENTS + 8]
                .try_into()
                .expect("generated spawn layout"),
            environment: buf[OFF_REQUEST_ENVIRONMENT..OFF_REQUEST_ENVIRONMENT + 8]
                .try_into()
                .expect("generated spawn layout"),
            grant_rights: u32::from_le_bytes(
                buf[OFF_REQUEST_GRANT_RIGHTS..OFF_REQUEST_GRANT_RIGHTS + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 6]
                .try_into()
                .expect("generated spawn layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_REQUEST_COMMAND_LEN..OFF_REQUEST_COMMAND_LEN + 2]
            .copy_from_slice(&self.command_len.to_le_bytes());
        buf[OFF_REQUEST_ARGUMENT_COUNT] = self.argument_count;
        buf[OFF_REQUEST_ENVIRONMENT_COUNT] = self.environment_count;
        buf[OFF_REQUEST_CAPABILITY_ROLES] = self.capability_roles;
        buf[OFF_REQUEST_CLIENT_BUDGET] = self.client_budget;
        buf[OFF_REQUEST_COMMAND..OFF_REQUEST_COMMAND + 16].copy_from_slice(&self.command);
        buf[OFF_REQUEST_ARGUMENTS..OFF_REQUEST_ARGUMENTS + 8].copy_from_slice(&self.arguments);
        buf[OFF_REQUEST_ENVIRONMENT..OFF_REQUEST_ENVIRONMENT + 8]
            .copy_from_slice(&self.environment);
        buf[OFF_REQUEST_GRANT_RIGHTS..OFF_REQUEST_GRANT_RIGHTS + 4]
            .copy_from_slice(&self.grant_rights.to_le_bytes());
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 6].copy_from_slice(&self.reserved);
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireSpawnReply {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub termination_kind: u32,
    pub task_id: u64,
    pub supervision_slot: u32,
    pub detail: u64,
}

impl WireSpawnReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            termination_kind: u32::from_le_bytes(
                buf[OFF_REPLY_TERMINATION_KIND..OFF_REPLY_TERMINATION_KIND + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            task_id: u64::from_le_bytes(
                buf[OFF_REPLY_TASK_ID..OFF_REPLY_TASK_ID + 8]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            supervision_slot: u32::from_le_bytes(
                buf[OFF_REPLY_SUPERVISION_SLOT..OFF_REPLY_SUPERVISION_SLOT + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            detail: u64::from_le_bytes(
                buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 8]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_TERMINATION_KIND..OFF_REPLY_TERMINATION_KIND + 4]
            .copy_from_slice(&self.termination_kind.to_le_bytes());
        buf[OFF_REPLY_TASK_ID..OFF_REPLY_TASK_ID + 8].copy_from_slice(&self.task_id.to_le_bytes());
        buf[OFF_REPLY_SUPERVISION_SLOT..OFF_REPLY_SUPERVISION_SLOT + 4]
            .copy_from_slice(&self.supervision_slot.to_le_bytes());
        buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 8].copy_from_slice(&self.detail.to_le_bytes());
        buf
    }
}
