// @generated by contracts/spawn/v2/gen_rust.zt; do not edit.
// Source contract: contracts/spawn/v2/schema.zt

pub const FORMAT_VERSION: u32 = 2;
pub const SPAWN_MAGIC: u32 = 1313559123;
pub const FRAME_MAGIC: u32 = 1179668563;
pub const FRAME_LEN: usize = 64;
pub const FRAME_PAYLOAD_BYTES: usize = 48;
pub const FRAME_FLAG_FINAL: u16 = 1;
pub const REQUEST_LEN: usize = 64;
pub const REPLY_LEN: usize = 64;
pub const MAX_ARGUMENTS: usize = 4;
pub const MAX_ARGUMENT_BYTES: usize = 256;
pub const MAX_ENVIRONMENT: usize = 1;
pub const MAX_ENVIRONMENT_BYTES: usize = 7;
pub const MAX_GRANTS: usize = 1;
pub const MAX_COMMAND_BYTES: usize = 16;

pub const REQUEST_FLAG_WAIT: u32 = 1;
pub const REQUEST_FLAG_SHUTDOWN: u32 = 2;
pub const REQUEST_FLAG_DETACHED: u32 = 4;
pub const CAPABILITY_ROLE_WORKING_DIRECTORY: u8 = 1;
pub const CAPABILITY_ROLE_STDIN: u8 = 2;
pub const CAPABILITY_ROLE_STDOUT: u8 = 4;
pub const CAPABILITY_ROLE_STDERR: u8 = 8;
pub const CAPABILITY_ROLE_GRANT: u8 = 16;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_FLAGS: usize = 8;
pub const OFF_REQUEST_COMMAND_LEN: usize = 12;
pub const OFF_REQUEST_ARGUMENT_COUNT: usize = 14;
pub const OFF_REQUEST_ENVIRONMENT_COUNT: usize = 15;
pub const OFF_REQUEST_CAPABILITY_ROLES: usize = 16;
pub const OFF_REQUEST_CLIENT_BUDGET: usize = 17;
pub const OFF_REQUEST_COMMAND: usize = 18;
pub const OFF_REQUEST_ARGUMENT_LEN0: usize = 34;
pub const OFF_REQUEST_ARGUMENT_LEN1: usize = 36;
pub const OFF_REQUEST_ARGUMENT_LEN2: usize = 38;
pub const OFF_REQUEST_ARGUMENT_LEN3: usize = 40;
pub const OFF_REQUEST_ENVIRONMENT: usize = 42;
pub const OFF_REQUEST_GRANT_RIGHTS: usize = 50;
pub const OFF_REQUEST_ARGUMENT_BYTES: usize = 54;
pub const OFF_REQUEST_SUPERVISION_HANDLE: usize = 56;
pub const OFF_REQUEST_RESERVED: usize = 60;

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_TERMINATION_KIND: usize = 12;
pub const OFF_REPLY_SUPERVISION_SLOT: usize = 16;
pub const OFF_REPLY_DETAIL: usize = 20;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireSpawnRequest {
    pub magic: u32,
    pub version: u32,
    pub flags: u32,
    pub command_len: u16,
    pub argument_count: u8,
    pub environment_count: u8,
    pub capability_roles: u8,
    pub client_budget: u8,
    pub command: [u8; 16],
    pub argument_len0: u16,
    pub argument_len1: u16,
    pub argument_len2: u16,
    pub argument_len3: u16,
    pub environment: [u8; 8],
    pub grant_rights: u32,
    pub argument_bytes: u16,
    pub supervision_handle: u32,
    pub reserved: [u8; 4],
}

impl WireSpawnRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            flags: u32::from_le_bytes(
                buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            command_len: u16::from_le_bytes(
                buf[OFF_REQUEST_COMMAND_LEN..OFF_REQUEST_COMMAND_LEN + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            argument_count: buf[OFF_REQUEST_ARGUMENT_COUNT],
            environment_count: buf[OFF_REQUEST_ENVIRONMENT_COUNT],
            capability_roles: buf[OFF_REQUEST_CAPABILITY_ROLES],
            client_budget: buf[OFF_REQUEST_CLIENT_BUDGET],
            command: buf[OFF_REQUEST_COMMAND..OFF_REQUEST_COMMAND + 16]
                .try_into()
                .expect("generated spawn layout"),
            argument_len0: u16::from_le_bytes(
                buf[OFF_REQUEST_ARGUMENT_LEN0..OFF_REQUEST_ARGUMENT_LEN0 + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            argument_len1: u16::from_le_bytes(
                buf[OFF_REQUEST_ARGUMENT_LEN1..OFF_REQUEST_ARGUMENT_LEN1 + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            argument_len2: u16::from_le_bytes(
                buf[OFF_REQUEST_ARGUMENT_LEN2..OFF_REQUEST_ARGUMENT_LEN2 + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            argument_len3: u16::from_le_bytes(
                buf[OFF_REQUEST_ARGUMENT_LEN3..OFF_REQUEST_ARGUMENT_LEN3 + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            environment: buf[OFF_REQUEST_ENVIRONMENT..OFF_REQUEST_ENVIRONMENT + 8]
                .try_into()
                .expect("generated spawn layout"),
            grant_rights: u32::from_le_bytes(
                buf[OFF_REQUEST_GRANT_RIGHTS..OFF_REQUEST_GRANT_RIGHTS + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            argument_bytes: u16::from_le_bytes(
                buf[OFF_REQUEST_ARGUMENT_BYTES..OFF_REQUEST_ARGUMENT_BYTES + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            supervision_handle: u32::from_le_bytes(
                buf[OFF_REQUEST_SUPERVISION_HANDLE..OFF_REQUEST_SUPERVISION_HANDLE + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            reserved: buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 4]
                .try_into()
                .expect("generated spawn layout"),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_FLAGS..OFF_REQUEST_FLAGS + 4].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_REQUEST_COMMAND_LEN..OFF_REQUEST_COMMAND_LEN + 2]
            .copy_from_slice(&self.command_len.to_le_bytes());
        buf[OFF_REQUEST_ARGUMENT_COUNT] = self.argument_count;
        buf[OFF_REQUEST_ENVIRONMENT_COUNT] = self.environment_count;
        buf[OFF_REQUEST_CAPABILITY_ROLES] = self.capability_roles;
        buf[OFF_REQUEST_CLIENT_BUDGET] = self.client_budget;
        buf[OFF_REQUEST_COMMAND..OFF_REQUEST_COMMAND + 16].copy_from_slice(&self.command);
        buf[OFF_REQUEST_ARGUMENT_LEN0..OFF_REQUEST_ARGUMENT_LEN0 + 2]
            .copy_from_slice(&self.argument_len0.to_le_bytes());
        buf[OFF_REQUEST_ARGUMENT_LEN1..OFF_REQUEST_ARGUMENT_LEN1 + 2]
            .copy_from_slice(&self.argument_len1.to_le_bytes());
        buf[OFF_REQUEST_ARGUMENT_LEN2..OFF_REQUEST_ARGUMENT_LEN2 + 2]
            .copy_from_slice(&self.argument_len2.to_le_bytes());
        buf[OFF_REQUEST_ARGUMENT_LEN3..OFF_REQUEST_ARGUMENT_LEN3 + 2]
            .copy_from_slice(&self.argument_len3.to_le_bytes());
        buf[OFF_REQUEST_ENVIRONMENT..OFF_REQUEST_ENVIRONMENT + 8]
            .copy_from_slice(&self.environment);
        buf[OFF_REQUEST_GRANT_RIGHTS..OFF_REQUEST_GRANT_RIGHTS + 4]
            .copy_from_slice(&self.grant_rights.to_le_bytes());
        buf[OFF_REQUEST_ARGUMENT_BYTES..OFF_REQUEST_ARGUMENT_BYTES + 2]
            .copy_from_slice(&self.argument_bytes.to_le_bytes());
        buf[OFF_REQUEST_SUPERVISION_HANDLE..OFF_REQUEST_SUPERVISION_HANDLE + 4]
            .copy_from_slice(&self.supervision_handle.to_le_bytes());
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 4].copy_from_slice(&self.reserved);
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireSpawnReply {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub termination_kind: u32,
    pub supervision_slot: u32,
    pub detail: u64,
}

impl WireSpawnReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            termination_kind: u32::from_le_bytes(
                buf[OFF_REPLY_TERMINATION_KIND..OFF_REPLY_TERMINATION_KIND + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            supervision_slot: u32::from_le_bytes(
                buf[OFF_REPLY_SUPERVISION_SLOT..OFF_REPLY_SUPERVISION_SLOT + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            detail: u64::from_le_bytes(
                buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 8]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_TERMINATION_KIND..OFF_REPLY_TERMINATION_KIND + 4]
            .copy_from_slice(&self.termination_kind.to_le_bytes());
        buf[OFF_REPLY_SUPERVISION_SLOT..OFF_REPLY_SUPERVISION_SLOT + 4]
            .copy_from_slice(&self.supervision_slot.to_le_bytes());
        buf[OFF_REPLY_DETAIL..OFF_REPLY_DETAIL + 8].copy_from_slice(&self.detail.to_le_bytes());
        buf
    }
}

pub const OFF_FRAME_MAGIC: usize = 0;
pub const OFF_FRAME_VERSION: usize = 4;
pub const OFF_FRAME_SEQUENCE: usize = 8;
pub const OFF_FRAME_OFFSET: usize = 10;
pub const OFF_FRAME_LENGTH: usize = 12;
pub const OFF_FRAME_FLAGS: usize = 14;
pub const OFF_FRAME_PAYLOAD: usize = 16;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireSpawnFrame {
    pub magic: u32,
    pub version: u32,
    pub sequence: u16,
    pub offset: u16,
    pub length: u16,
    pub flags: u16,
    pub payload: [u8; 48],
}

impl WireSpawnFrame {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < FRAME_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_FRAME_MAGIC..OFF_FRAME_MAGIC + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_FRAME_VERSION..OFF_FRAME_VERSION + 4]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            sequence: u16::from_le_bytes(
                buf[OFF_FRAME_SEQUENCE..OFF_FRAME_SEQUENCE + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            offset: u16::from_le_bytes(
                buf[OFF_FRAME_OFFSET..OFF_FRAME_OFFSET + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            length: u16::from_le_bytes(
                buf[OFF_FRAME_LENGTH..OFF_FRAME_LENGTH + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            flags: u16::from_le_bytes(
                buf[OFF_FRAME_FLAGS..OFF_FRAME_FLAGS + 2]
                    .try_into()
                    .expect("generated spawn layout"),
            ),
            payload: buf[OFF_FRAME_PAYLOAD..OFF_FRAME_PAYLOAD + 48]
                .try_into()
                .expect("generated spawn layout"),
        })
    }

    pub fn encode(self) -> [u8; FRAME_LEN] {
        let mut buf = [0u8; FRAME_LEN];
        buf[OFF_FRAME_MAGIC..OFF_FRAME_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_FRAME_VERSION..OFF_FRAME_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_FRAME_SEQUENCE..OFF_FRAME_SEQUENCE + 2]
            .copy_from_slice(&self.sequence.to_le_bytes());
        buf[OFF_FRAME_OFFSET..OFF_FRAME_OFFSET + 2].copy_from_slice(&self.offset.to_le_bytes());
        buf[OFF_FRAME_LENGTH..OFF_FRAME_LENGTH + 2].copy_from_slice(&self.length.to_le_bytes());
        buf[OFF_FRAME_FLAGS..OFF_FRAME_FLAGS + 2].copy_from_slice(&self.flags.to_le_bytes());
        buf[OFF_FRAME_PAYLOAD..OFF_FRAME_PAYLOAD + 48].copy_from_slice(&self.payload);
        buf
    }
}
