// @generated by contracts/store/v1/gen_rust.zt; do not edit.
// Source contract: contracts/store/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const STORE_MAGIC: u32 = 1414745171;
pub const STORE_MAGIC_BYTES: [u8; 4] = STORE_MAGIC.to_le_bytes();
pub const OP_STAT: u8 = 1;
pub const OP_GET: u8 = 2;
pub const OP_PUT: u8 = 3;
pub const REQUEST_LEN: usize = 64;
pub const REPLY_LEN: usize = 64;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OP: usize = 8;
pub const OFF_REQUEST_FLAGS: usize = 9;
pub const OFF_REQUEST_RESERVED: usize = 10;
pub const OFF_REQUEST_BUFFER_ADDR: usize = 12;
pub const OFF_REQUEST_OBJ_TYPE: usize = 20;
pub const OFF_REQUEST_PAYLOAD_LEN: usize = 24;
pub const OFF_REQUEST_HASH0: usize = 28;
pub const OFF_REQUEST_HASH1: usize = 36;
pub const OFF_REQUEST_HASH2: usize = 44;
pub const OFF_REQUEST_HASH3: usize = 52;

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_OBJ_TYPE: usize = 12;
pub const OFF_REPLY_PAYLOAD_LEN: usize = 16;
pub const OFF_REPLY_HASH0: usize = 20;
pub const OFF_REPLY_HASH1: usize = 28;
pub const OFF_REPLY_HASH2: usize = 36;
pub const OFF_REPLY_HASH3: usize = 44;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireStoreRequest {
    pub magic: u32,
    pub version: u32,
    pub op: u8,
    pub flags: u8,
    pub reserved: u16,
    pub buffer_addr: u64,
    pub obj_type: u32,
    pub payload_len: u32,
    pub hash0: u64,
    pub hash1: u64,
    pub hash2: u64,
    pub hash3: u64,
}

impl WireStoreRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated store layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated store layout"),
            ),
            op: buf[OFF_REQUEST_OP],
            flags: buf[OFF_REQUEST_FLAGS],
            reserved: u16::from_le_bytes(
                buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 2]
                    .try_into()
                    .expect("generated store layout"),
            ),
            buffer_addr: u64::from_le_bytes(
                buf[OFF_REQUEST_BUFFER_ADDR..OFF_REQUEST_BUFFER_ADDR + 8]
                    .try_into()
                    .expect("generated store layout"),
            ),
            obj_type: u32::from_le_bytes(
                buf[OFF_REQUEST_OBJ_TYPE..OFF_REQUEST_OBJ_TYPE + 4]
                    .try_into()
                    .expect("generated store layout"),
            ),
            payload_len: u32::from_le_bytes(
                buf[OFF_REQUEST_PAYLOAD_LEN..OFF_REQUEST_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated store layout"),
            ),
            hash0: u64::from_le_bytes(
                buf[OFF_REQUEST_HASH0..OFF_REQUEST_HASH0 + 8]
                    .try_into()
                    .expect("generated store layout"),
            ),
            hash1: u64::from_le_bytes(
                buf[OFF_REQUEST_HASH1..OFF_REQUEST_HASH1 + 8]
                    .try_into()
                    .expect("generated store layout"),
            ),
            hash2: u64::from_le_bytes(
                buf[OFF_REQUEST_HASH2..OFF_REQUEST_HASH2 + 8]
                    .try_into()
                    .expect("generated store layout"),
            ),
            hash3: u64::from_le_bytes(
                buf[OFF_REQUEST_HASH3..OFF_REQUEST_HASH3 + 8]
                    .try_into()
                    .expect("generated store layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OP] = self.op;
        buf[OFF_REQUEST_FLAGS] = self.flags;
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 2]
            .copy_from_slice(&self.reserved.to_le_bytes());
        buf[OFF_REQUEST_BUFFER_ADDR..OFF_REQUEST_BUFFER_ADDR + 8]
            .copy_from_slice(&self.buffer_addr.to_le_bytes());
        buf[OFF_REQUEST_OBJ_TYPE..OFF_REQUEST_OBJ_TYPE + 4]
            .copy_from_slice(&self.obj_type.to_le_bytes());
        buf[OFF_REQUEST_PAYLOAD_LEN..OFF_REQUEST_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_REQUEST_HASH0..OFF_REQUEST_HASH0 + 8].copy_from_slice(&self.hash0.to_le_bytes());
        buf[OFF_REQUEST_HASH1..OFF_REQUEST_HASH1 + 8].copy_from_slice(&self.hash1.to_le_bytes());
        buf[OFF_REQUEST_HASH2..OFF_REQUEST_HASH2 + 8].copy_from_slice(&self.hash2.to_le_bytes());
        buf[OFF_REQUEST_HASH3..OFF_REQUEST_HASH3 + 8].copy_from_slice(&self.hash3.to_le_bytes());
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireStoreReply {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub obj_type: u32,
    pub payload_len: u32,
    pub hash0: u64,
    pub hash1: u64,
    pub hash2: u64,
    pub hash3: u64,
}

impl WireStoreReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated store layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4]
                    .try_into()
                    .expect("generated store layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated store layout"),
            ),
            obj_type: u32::from_le_bytes(
                buf[OFF_REPLY_OBJ_TYPE..OFF_REPLY_OBJ_TYPE + 4]
                    .try_into()
                    .expect("generated store layout"),
            ),
            payload_len: u32::from_le_bytes(
                buf[OFF_REPLY_PAYLOAD_LEN..OFF_REPLY_PAYLOAD_LEN + 4]
                    .try_into()
                    .expect("generated store layout"),
            ),
            hash0: u64::from_le_bytes(
                buf[OFF_REPLY_HASH0..OFF_REPLY_HASH0 + 8]
                    .try_into()
                    .expect("generated store layout"),
            ),
            hash1: u64::from_le_bytes(
                buf[OFF_REPLY_HASH1..OFF_REPLY_HASH1 + 8]
                    .try_into()
                    .expect("generated store layout"),
            ),
            hash2: u64::from_le_bytes(
                buf[OFF_REPLY_HASH2..OFF_REPLY_HASH2 + 8]
                    .try_into()
                    .expect("generated store layout"),
            ),
            hash3: u64::from_le_bytes(
                buf[OFF_REPLY_HASH3..OFF_REPLY_HASH3 + 8]
                    .try_into()
                    .expect("generated store layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_OBJ_TYPE..OFF_REPLY_OBJ_TYPE + 4]
            .copy_from_slice(&self.obj_type.to_le_bytes());
        buf[OFF_REPLY_PAYLOAD_LEN..OFF_REPLY_PAYLOAD_LEN + 4]
            .copy_from_slice(&self.payload_len.to_le_bytes());
        buf[OFF_REPLY_HASH0..OFF_REPLY_HASH0 + 8].copy_from_slice(&self.hash0.to_le_bytes());
        buf[OFF_REPLY_HASH1..OFF_REPLY_HASH1 + 8].copy_from_slice(&self.hash1.to_le_bytes());
        buf[OFF_REPLY_HASH2..OFF_REPLY_HASH2 + 8].copy_from_slice(&self.hash2.to_le_bytes());
        buf[OFF_REPLY_HASH3..OFF_REPLY_HASH3 + 8].copy_from_slice(&self.hash3.to_le_bytes());
        buf
    }
}
