// @generated by contracts/syscall-abi/v1/gen_rust.zt; do not edit.
// Source contract: contracts/syscall-abi/v1/schema.zt
//
// Root-service operation labels, status codes, and message bounds,
// consumed by both `slime-root` (dispatch) and `components/runtime` (the
// userspace wrapper), so the two cannot disagree about what a label means.
// Numbers are frozen: a component image built against one generation
// invokes the same label a later root must still answer.

pub const FORMAT_VERSION: u32 = 1;

pub mod fixture_labels {
    pub const DIRECTIVE: u64 = 5;
}

pub mod lifecycle_labels {
    pub const EXIT: u64 = 3;
    pub const UNHEALTHY: u64 = 9;
    pub const PRIVATE_MEMORY_GROW: u64 = 43;
    pub const WAIT_SOURCES: u64 = 49;
    pub const STATE_READ: u64 = 52;
    pub const STATE_ADVANCE: u64 = 53;
    pub const RECORDING_SOURCES: u64 = 57;
}

pub mod spawn_labels {
    pub const SPAWN: u64 = 4;
}

pub mod supervision_labels {
    pub const STATUS: u64 = 12;
    pub const DERIVE: u64 = 32;
    pub const RESTART_ADMIT: u64 = 54;
    pub const PARAMETER_READ: u64 = 55;
    pub const PARAMETER_WRITE: u64 = 56;
}

pub mod capability_table_labels {
    pub const DROP: u64 = 13;
    pub const OCCUPANCY: u64 = 31;
    pub const RESOLVE_BINDING: u64 = 37;
    pub const GRAPH_READ: u64 = 38;
    pub const GRAPH_ROUTE_INDEX: u64 = 39;
    pub const BOOT_ACTION: u64 = 40;
    pub const GRAPH_QUERY: u64 = 41;
    pub const SPAWN_BUDGET: u64 = 42;
    pub const NETWORK_DESTINATIONS_READ: u64 = 64;
}

pub mod directory_labels {
    pub const DERIVE: u64 = 15;
}

pub mod shared_buffer_labels {
    pub const CREATE: u64 = 21;
    pub const RELEASE: u64 = 22;
    pub const MAP: u64 = 23;
    pub const UNMAP: u64 = 24;
    pub const SEAL: u64 = 25;
    pub const LOAN: u64 = 26;
    pub const LOAN_MAP: u64 = 27;
    pub const RETURN: u64 = 28;
    pub const REVOKE: u64 = 29;
    pub const OCCUPANCY: u64 = 30;
}

pub mod capability_transfer_labels {
    pub const EXPORT: u64 = 33;
    pub const IMPORT: u64 = 34;
    pub const EXPORT_CANCEL: u64 = 35;
    pub const EXPORT_FINALIZE: u64 = 36;
}

pub mod clock_labels {
    pub const MONOTONIC_READ: u64 = 44;
    pub const TIMER_ARM: u64 = 45;
    pub const TIMER_CANCEL: u64 = 46;
    pub const SIMULATED_READ: u64 = 47;
    pub const SIMULATED_ADVANCE: u64 = 48;
}

pub mod scheduling_labels {
    pub const CLASS_READ: u64 = 50;
    pub const CLASS_PROMOTE: u64 = 51;
}

pub mod io_resource_labels {
    pub const BIND: u64 = 58;
    pub const MAP_MMIO: u64 = 59;
    pub const DMA_MAP: u64 = 60;
    pub const DMA_RELEASE: u64 = 61;
    pub const IRQ_WAIT_ACK: u64 = 62;
    pub const QUEUE_MAP: u64 = 63;
    pub const REQUEST_BEGIN: u64 = 65;
    pub const REQUEST_SETTLE: u64 = 66;
    pub const MMIO_READ32: u64 = 67;
    pub const MMIO_WRITE32: u64 = 68;
}

pub const ERR_SUCCESS: i64 = 0;
pub const ERR_BAD_CAP: i64 = -1;
pub const ERR_PEER_DEAD: i64 = -2;
pub const ERR_WOULDBLOCK: i64 = -3;
pub const ERR_INVALID_ARG: i64 = -4;
pub const ERR_OUT_OF_MEMORY: i64 = -5;

pub const MAX_MSG: usize = 64;
pub const MAX_CAPS_PER_MSG: usize = 1;

/// Bytes of one spawn-grant record staged in the transfer window: an
/// 8-byte little-endian child slot, then an 8-byte little-endian rights
/// mask. Both sides of the syscall encode and decode through these.
pub const GRANT_RECORD_BYTES: usize = 16;
pub const GRANT_SLOT_OFFSET: usize = 0;
pub const GRANT_RIGHTS_OFFSET: usize = 8;
