// @generated by contracts/syscall-abi/v1/gen_rust.zt; do not edit.
// Source contract: contracts/syscall-abi/v1/schema.zt
//
// Root-service operation labels, status codes, and message bounds,
// consumed by both `slime-root` (dispatch) and `components/runtime` (the
// userspace wrapper), so the two cannot disagree about what a label means.
// Numbers are frozen: a component image built against one generation
// invokes the same label a later root must still answer.

pub const FORMAT_VERSION: u32 = 1;

pub mod fixture_labels {
    pub const DIRECTIVE: u64 = 5;
}

pub mod lifecycle_labels {
    pub const EXIT: u64 = 3;
    pub const UNHEALTHY: u64 = 9;
}

pub mod spawn_labels {
    pub const SPAWN: u64 = 4;
}

pub mod supervision_labels {
    pub const STATUS: u64 = 12;
    pub const DERIVE: u64 = 32;
}

pub mod capability_table_labels {
    pub const DROP: u64 = 13;
    pub const OCCUPANCY: u64 = 31;
    pub const RESOLVE_BINDING: u64 = 37;
    pub const GRAPH_READ: u64 = 38;
}

pub mod directory_labels {
    pub const DERIVE: u64 = 15;
}

pub mod shared_buffer_labels {
    pub const CREATE: u64 = 21;
    pub const RELEASE: u64 = 22;
    pub const MAP: u64 = 23;
    pub const UNMAP: u64 = 24;
    pub const SEAL: u64 = 25;
    pub const LOAN: u64 = 26;
    pub const LOAN_MAP: u64 = 27;
    pub const RETURN: u64 = 28;
    pub const REVOKE: u64 = 29;
    pub const OCCUPANCY: u64 = 30;
}

pub mod capability_transfer_labels {
    pub const EXPORT: u64 = 33;
    pub const IMPORT: u64 = 34;
    pub const EXPORT_CANCEL: u64 = 35;
    pub const EXPORT_FINALIZE: u64 = 36;
}

pub const ERR_SUCCESS: i64 = 0;
pub const ERR_BAD_CAP: i64 = -1;
pub const ERR_PEER_DEAD: i64 = -2;
pub const ERR_WOULDBLOCK: i64 = -3;
pub const ERR_INVALID_ARG: i64 = -4;
pub const ERR_OUT_OF_MEMORY: i64 = -5;

pub const MAX_MSG: usize = 64;
pub const MAX_CAPS_PER_MSG: usize = 1;

/// Bytes of one spawn-grant record staged in the transfer window: an
/// 8-byte little-endian child slot, then an 8-byte little-endian rights
/// mask. Both sides of the syscall encode and decode through these.
pub const GRANT_RECORD_BYTES: usize = 16;
pub const GRANT_SLOT_OFFSET: usize = 0;
pub const GRANT_RIGHTS_OFFSET: usize = 8;
