// @generated by contracts/zenoh-profile/v1/gen_rust.zt; do not edit.
// Source contract: contracts/zenoh-profile/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const PROTOCOL_VERSION: u32 = 9;
pub const WHATAMI_ROUTER: u32 = 0;
pub const WHATAMI_PEER: u32 = 1;
pub const WHATAMI_CLIENT: u32 = 2;
pub const DEFAULT_RESOLUTION: u32 = 10;
pub const STREAM_LENGTH_BYTES: usize = 2;

pub const MAX_BATCH_BYTES: usize = 512;
pub const MAX_KEY_BYTES: usize = 129;
pub const MAX_ATTACHMENT_BYTES: usize = 33;
pub const MAX_PAYLOAD_BYTES: usize = 12;
pub const MAX_COOKIE_BYTES: usize = 64;
pub const MAX_ZID_BYTES: usize = 16;
pub const GID_BYTES: usize = 16;
pub const LEB128_MAX_BITS: u32 = 32;
pub const LEB128_SHORT_BITS: u32 = 16;

pub const ID_INIT: u32 = 1;
pub const ID_OPEN: u32 = 2;
pub const ID_CLOSE: u32 = 3;
pub const ID_FRAME: u32 = 5;
pub const ID_PUSH: u32 = 29;
pub const ID_DECLARE: u32 = 30;
pub const ID_DECLARE_SUBSCRIBER: u32 = 2;
pub const ID_UNDECLARE_SUBSCRIBER: u32 = 3;
pub const ID_PUT: u32 = 1;

pub const FLAG_BIT5: u32 = 32;
pub const FLAG_BIT6: u32 = 64;
pub const FLAG_EXTENSIONS: u32 = 128;
pub const EXT_WIRE_EXPR: u32 = 95;
pub const EXT_ATTACHMENT: u32 = 67;

pub const CLOSE_GENERIC: u32 = 0;
pub const CLOSE_UNSUPPORTED: u32 = 1;
pub const CLOSE_INVALID: u32 = 2;
pub const CLOSE_MAX_SESSIONS: u32 = 3;
pub const CLOSE_MAX_LINKS: u32 = 4;
pub const CLOSE_EXPIRED: u32 = 5;
pub const CLOSE_UNRESPONSIVE: u32 = 6;
pub const CLOSE_CONNECTION_TO_SELF: u32 = 7;

/// Why a decoder refuses input. Zero is reserved for accepted input.
pub const REFUSAL_EMPTY_BATCH: u8 = 1;
pub const REFUSAL_LENGTH_EXCEEDS_BATCH: u8 = 2;
pub const REFUSAL_TRUNCATED: u8 = 3;
pub const REFUSAL_TRAILING_BYTES: u8 = 4;
pub const REFUSAL_UNSUPPORTED_VERSION: u8 = 5;
pub const REFUSAL_UNSUPPORTED_WHATAMI: u8 = 6;
pub const REFUSAL_UNSUPPORTED_RESOLUTION: u8 = 7;
pub const REFUSAL_UNSUPPORTED_EXTENSION: u8 = 8;
pub const REFUSAL_UNSUPPORTED_MESSAGE: u8 = 9;
pub const REFUSAL_MALFORMED_MESSAGE: u8 = 10;
pub const REFUSAL_OVER_BOUND: u8 = 11;
pub const REFUSAL_LEB128_OVERFLOW: u8 = 12;
pub const REFUSAL_LEB128_NONCANONICAL: u8 = 13;
pub const REFUSAL_WILDCARD_KEYEXPR: u8 = 14;
pub const REFUSAL_INVALID_KEYEXPR: u8 = 15;
pub const REFUSAL_CLASS_COUNT: usize = 15;

/// The class's wire name, as a probe reports it.
pub const fn refusal_name(code: u8) -> Option<&'static str> {
    match code {
        REFUSAL_EMPTY_BATCH => Some("empty-batch"),
        REFUSAL_LENGTH_EXCEEDS_BATCH => Some("length-exceeds-batch"),
        REFUSAL_TRUNCATED => Some("truncated"),
        REFUSAL_TRAILING_BYTES => Some("trailing-bytes"),
        REFUSAL_UNSUPPORTED_VERSION => Some("unsupported-version"),
        REFUSAL_UNSUPPORTED_WHATAMI => Some("unsupported-whatami"),
        REFUSAL_UNSUPPORTED_RESOLUTION => Some("unsupported-resolution"),
        REFUSAL_UNSUPPORTED_EXTENSION => Some("unsupported-extension"),
        REFUSAL_UNSUPPORTED_MESSAGE => Some("unsupported-message"),
        REFUSAL_MALFORMED_MESSAGE => Some("malformed-message"),
        REFUSAL_OVER_BOUND => Some("over-bound"),
        REFUSAL_LEB128_OVERFLOW => Some("leb128-overflow"),
        REFUSAL_LEB128_NONCANONICAL => Some("leb128-noncanonical"),
        REFUSAL_WILDCARD_KEYEXPR => Some("wildcard-keyexpr"),
        REFUSAL_INVALID_KEYEXPR => Some("invalid-keyexpr"),
        _ => None,
    }
}
