# @generated from boot contract schemas; do not edit.
from __future__ import annotations

import hashlib
import struct
import typing

GENERATION_MAGIC = b"SLIMEG5\0"
GENERATION_VERSION = 5
GENERATION_HEADER = struct.Struct("<8sIIQ32sQ32sIIIIIIIIIIIIIIIIIIIIIIIIIIQQQQQQQQQQQQQQQQQQQQQQQQQ112x")
GENERATION_HEADER_MAGIC_OFFSET = 0
GENERATION_HEADER_MAGIC_END = 8
GENERATION_HEADER_FORMAT_VERSION_OFFSET = 8
GENERATION_HEADER_FORMAT_VERSION_END = 12
GENERATION_HEADER_HEADER_SIZE_OFFSET = 12
GENERATION_HEADER_HEADER_SIZE_END = 16
GENERATION_HEADER_REQUIRED_FLAGS_OFFSET = 16
GENERATION_HEADER_REQUIRED_FLAGS_END = 24
GENERATION_HEADER_IDENTITY_OFFSET = 24
GENERATION_HEADER_IDENTITY_END = 56
GENERATION_HEADER_GENERATION_NUMBER_OFFSET = 56
GENERATION_HEADER_GENERATION_NUMBER_END = 64
GENERATION_HEADER_PARENT_OFFSET = 64
GENERATION_HEADER_PARENT_END = 96
GENERATION_HEADER_TARGET_OFFSET_OFFSET = 96
GENERATION_HEADER_TARGET_OFFSET_END = 100
GENERATION_HEADER_BOOT_ACTION_OFFSET_OFFSET = 100
GENERATION_HEADER_BOOT_ACTION_OFFSET_END = 104
GENERATION_HEADER_BOOTSTRAP_INSTANCE_OFFSET = 104
GENERATION_HEADER_BOOTSTRAP_INSTANCE_END = 108
GENERATION_HEADER_BOOT_ATTEMPTS_OFFSET = 108
GENERATION_HEADER_BOOT_ATTEMPTS_END = 112
GENERATION_HEADER_OBJECT_COUNT_OFFSET = 112
GENERATION_HEADER_OBJECT_COUNT_END = 116
GENERATION_HEADER_EXECUTABLE_COUNT_OFFSET = 116
GENERATION_HEADER_EXECUTABLE_COUNT_END = 120
GENERATION_HEADER_INSTANCE_COUNT_OFFSET = 120
GENERATION_HEADER_INSTANCE_COUNT_END = 124
GENERATION_HEADER_DEPENDENCY_COUNT_OFFSET = 124
GENERATION_HEADER_DEPENDENCY_COUNT_END = 128
GENERATION_HEADER_BINDING_COUNT_OFFSET = 128
GENERATION_HEADER_BINDING_COUNT_END = 132
GENERATION_HEADER_GRANT_COUNT_OFFSET = 132
GENERATION_HEADER_GRANT_COUNT_END = 136
GENERATION_HEADER_STATE_COUNT_OFFSET = 136
GENERATION_HEADER_STATE_COUNT_END = 140
GENERATION_HEADER_HEALTH_COUNT_OFFSET = 140
GENERATION_HEADER_HEALTH_COUNT_END = 144
GENERATION_HEADER_PROCESS_COUNT_OFFSET = 144
GENERATION_HEADER_PROCESS_COUNT_END = 148
GENERATION_HEADER_THREAD_COUNT_OFFSET = 148
GENERATION_HEADER_THREAD_COUNT_END = 152
GENERATION_HEADER_KERNEL_OBJECT_COUNT_OFFSET = 152
GENERATION_HEADER_KERNEL_OBJECT_COUNT_END = 156
GENERATION_HEADER_MAPPING_COUNT_OFFSET = 156
GENERATION_HEADER_MAPPING_COUNT_END = 160
GENERATION_HEADER_CAP_BINDING_COUNT_OFFSET = 160
GENERATION_HEADER_CAP_BINDING_COUNT_END = 164
GENERATION_HEADER_SERVICE_BINDING_COUNT_OFFSET = 164
GENERATION_HEADER_SERVICE_BINDING_COUNT_END = 168
GENERATION_HEADER_SCHEDULE_COUNT_OFFSET = 168
GENERATION_HEADER_SCHEDULE_COUNT_END = 172
GENERATION_HEADER_FAULT_POLICY_COUNT_OFFSET = 172
GENERATION_HEADER_FAULT_POLICY_COUNT_END = 176
GENERATION_HEADER_SPAWN_TEMPLATE_COUNT_OFFSET = 176
GENERATION_HEADER_SPAWN_TEMPLATE_COUNT_END = 180
GENERATION_HEADER_RESOURCE_QUOTA_COUNT_OFFSET = 180
GENERATION_HEADER_RESOURCE_QUOTA_COUNT_END = 184
GENERATION_HEADER_MINTED_BINDING_COUNT_OFFSET = 184
GENERATION_HEADER_MINTED_BINDING_COUNT_END = 188
GENERATION_HEADER_NOTIFICATION_GRANT_COUNT_OFFSET = 188
GENERATION_HEADER_NOTIFICATION_GRANT_COUNT_END = 192
GENERATION_HEADER_NOTIFICATION_BINDING_COUNT_OFFSET = 192
GENERATION_HEADER_NOTIFICATION_BINDING_COUNT_END = 196
GENERATION_HEADER_HEADER_RESERVED_OFFSET = 196
GENERATION_HEADER_HEADER_RESERVED_END = 200
GENERATION_HEADER_OBJECT_OFFSET_OFFSET = 200
GENERATION_HEADER_OBJECT_OFFSET_END = 208
GENERATION_HEADER_EXECUTABLE_OFFSET_OFFSET = 208
GENERATION_HEADER_EXECUTABLE_OFFSET_END = 216
GENERATION_HEADER_INSTANCE_OFFSET_OFFSET = 216
GENERATION_HEADER_INSTANCE_OFFSET_END = 224
GENERATION_HEADER_DEPENDENCY_OFFSET_OFFSET = 224
GENERATION_HEADER_DEPENDENCY_OFFSET_END = 232
GENERATION_HEADER_BINDING_OFFSET_OFFSET = 232
GENERATION_HEADER_BINDING_OFFSET_END = 240
GENERATION_HEADER_GRANT_OFFSET_OFFSET = 240
GENERATION_HEADER_GRANT_OFFSET_END = 248
GENERATION_HEADER_STATE_OFFSET_OFFSET = 248
GENERATION_HEADER_STATE_OFFSET_END = 256
GENERATION_HEADER_HEALTH_OFFSET_OFFSET = 256
GENERATION_HEADER_HEALTH_OFFSET_END = 264
GENERATION_HEADER_PROCESS_OFFSET_OFFSET = 264
GENERATION_HEADER_PROCESS_OFFSET_END = 272
GENERATION_HEADER_THREAD_OFFSET_OFFSET = 272
GENERATION_HEADER_THREAD_OFFSET_END = 280
GENERATION_HEADER_KERNEL_OBJECT_OFFSET_OFFSET = 280
GENERATION_HEADER_KERNEL_OBJECT_OFFSET_END = 288
GENERATION_HEADER_MAPPING_OFFSET_OFFSET = 288
GENERATION_HEADER_MAPPING_OFFSET_END = 296
GENERATION_HEADER_CAP_BINDING_OFFSET_OFFSET = 296
GENERATION_HEADER_CAP_BINDING_OFFSET_END = 304
GENERATION_HEADER_SERVICE_BINDING_OFFSET_OFFSET = 304
GENERATION_HEADER_SERVICE_BINDING_OFFSET_END = 312
GENERATION_HEADER_SCHEDULE_OFFSET_OFFSET = 312
GENERATION_HEADER_SCHEDULE_OFFSET_END = 320
GENERATION_HEADER_FAULT_POLICY_OFFSET_OFFSET = 320
GENERATION_HEADER_FAULT_POLICY_OFFSET_END = 328
GENERATION_HEADER_SPAWN_TEMPLATE_OFFSET_OFFSET = 328
GENERATION_HEADER_SPAWN_TEMPLATE_OFFSET_END = 336
GENERATION_HEADER_RESOURCE_QUOTA_OFFSET_OFFSET = 336
GENERATION_HEADER_RESOURCE_QUOTA_OFFSET_END = 344
GENERATION_HEADER_MINTED_BINDING_OFFSET_OFFSET = 344
GENERATION_HEADER_MINTED_BINDING_OFFSET_END = 352
GENERATION_HEADER_NOTIFICATION_GRANT_OFFSET_OFFSET = 352
GENERATION_HEADER_NOTIFICATION_GRANT_OFFSET_END = 360
GENERATION_HEADER_NOTIFICATION_BINDING_OFFSET_OFFSET = 360
GENERATION_HEADER_NOTIFICATION_BINDING_OFFSET_END = 368
GENERATION_HEADER_STRING_OFFSET_OFFSET = 368
GENERATION_HEADER_STRING_OFFSET_END = 376
GENERATION_HEADER_STRING_LEN_OFFSET = 376
GENERATION_HEADER_STRING_LEN_END = 384
GENERATION_HEADER_PAYLOAD_OFFSET_OFFSET = 384
GENERATION_HEADER_PAYLOAD_OFFSET_END = 392
GENERATION_HEADER_TOTAL_LEN_OFFSET = 392
GENERATION_HEADER_TOTAL_LEN_END = 400

GENERATION_OBJECT = struct.Struct("<IIQQ32s8x")
GENERATION_OBJECT_ID_OFFSET_OFFSET = 0
GENERATION_OBJECT_ID_OFFSET_END = 4
GENERATION_OBJECT_KIND_OFFSET = 4
GENERATION_OBJECT_KIND_END = 8
GENERATION_OBJECT_PAYLOAD_OFFSET_OFFSET = 8
GENERATION_OBJECT_PAYLOAD_OFFSET_END = 16
GENERATION_OBJECT_PAYLOAD_LEN_OFFSET = 16
GENERATION_OBJECT_PAYLOAD_LEN_END = 24
GENERATION_OBJECT_DIGEST_OFFSET = 24
GENERATION_OBJECT_DIGEST_END = 56

GENERATION_EXECUTABLE = struct.Struct("<IIII16x")
GENERATION_EXECUTABLE_NAME_OFFSET_OFFSET = 0
GENERATION_EXECUTABLE_NAME_OFFSET_END = 4
GENERATION_EXECUTABLE_OBJECT_INDEX_OFFSET = 4
GENERATION_EXECUTABLE_OBJECT_INDEX_END = 8
GENERATION_EXECUTABLE_ROLE_OFFSET = 8
GENERATION_EXECUTABLE_ROLE_END = 12
GENERATION_EXECUTABLE_SPAWN_BUDGET_OFFSET = 12
GENERATION_EXECUTABLE_SPAWN_BUDGET_END = 16

GENERATION_INSTANCE = struct.Struct("<IIIIIIIIII8x")
GENERATION_INSTANCE_NAME_OFFSET_OFFSET = 0
GENERATION_INSTANCE_NAME_OFFSET_END = 4
GENERATION_INSTANCE_EXECUTABLE_INDEX_OFFSET = 4
GENERATION_INSTANCE_EXECUTABLE_INDEX_END = 8
GENERATION_INSTANCE_OWNER_KIND_OFFSET = 8
GENERATION_INSTANCE_OWNER_KIND_END = 12
GENERATION_INSTANCE_OWNER_INDEX_OFFSET = 12
GENERATION_INSTANCE_OWNER_INDEX_END = 16
GENERATION_INSTANCE_AUTOSTART_OFFSET = 16
GENERATION_INSTANCE_AUTOSTART_END = 20
GENERATION_INSTANCE_DEPENDENCY_START_OFFSET = 20
GENERATION_INSTANCE_DEPENDENCY_START_END = 24
GENERATION_INSTANCE_DEPENDENCY_COUNT_OFFSET = 24
GENERATION_INSTANCE_DEPENDENCY_COUNT_END = 28
GENERATION_INSTANCE_BINDING_START_OFFSET = 28
GENERATION_INSTANCE_BINDING_START_END = 32
GENERATION_INSTANCE_BINDING_COUNT_OFFSET = 32
GENERATION_INSTANCE_BINDING_COUNT_END = 36
GENERATION_INSTANCE_HEALTH_OFFSET = 36
GENERATION_INSTANCE_HEALTH_END = 40

GENERATION_DEPENDENCY = struct.Struct("<I")
GENERATION_DEPENDENCY_INSTANCE_OFFSET = 0
GENERATION_DEPENDENCY_INSTANCE_END = 4

GENERATION_BINDING = struct.Struct("<II")
GENERATION_BINDING_GRANT_OFFSET = 0
GENERATION_BINDING_GRANT_END = 4
GENERATION_BINDING_SLOT_OFFSET = 4
GENERATION_BINDING_SLOT_END = 8

GENERATION_GRANT = struct.Struct("<IIIQIII")
GENERATION_GRANT_NAME_OFFSET_OFFSET = 0
GENERATION_GRANT_NAME_OFFSET_END = 4
GENERATION_GRANT_SOURCE_OFFSET = 4
GENERATION_GRANT_SOURCE_END = 8
GENERATION_GRANT_TARGET_OFFSET = 8
GENERATION_GRANT_TARGET_END = 12
GENERATION_GRANT_RIGHTS_OFFSET = 12
GENERATION_GRANT_RIGHTS_END = 20
GENERATION_GRANT_TRANSFERABLE_OFFSET = 20
GENERATION_GRANT_TRANSFERABLE_END = 24
GENERATION_GRANT_FLAGS_OFFSET = 24
GENERATION_GRANT_FLAGS_END = 28
GENERATION_GRANT_CAPABILITY_KIND_OFFSET = 28
GENERATION_GRANT_CAPABILITY_KIND_END = 32

GENERATION_STATE = struct.Struct("<IIII8x")
GENERATION_STATE_NAME_OFFSET_OFFSET = 0
GENERATION_STATE_NAME_OFFSET_END = 4
GENERATION_STATE_OWNER_OFFSET = 4
GENERATION_STATE_OWNER_END = 8
GENERATION_STATE_SCHEMA_VERSION_OFFSET = 8
GENERATION_STATE_SCHEMA_VERSION_END = 12
GENERATION_STATE_POLICY_OFFSET = 12
GENERATION_STATE_POLICY_END = 16

GENERATION_HEALTH = struct.Struct("<I")
GENERATION_HEALTH_INSTANCE_OFFSET = 0
GENERATION_HEALTH_INSTANCE_END = 4

GENERATION_PROCESS = struct.Struct("<IIIIIII4x")
GENERATION_PROCESS_NAME_OFFSET_OFFSET = 0
GENERATION_PROCESS_NAME_OFFSET_END = 4
GENERATION_PROCESS_INSTANCE_OFFSET = 4
GENERATION_PROCESS_INSTANCE_END = 8
GENERATION_PROCESS_CSPACE_OBJECT_OFFSET = 8
GENERATION_PROCESS_CSPACE_OBJECT_END = 12
GENERATION_PROCESS_VSPACE_OBJECT_OFFSET = 12
GENERATION_PROCESS_VSPACE_OBJECT_END = 16
GENERATION_PROCESS_MAIN_THREAD_OFFSET = 16
GENERATION_PROCESS_MAIN_THREAD_END = 20
GENERATION_PROCESS_QUOTA_OFFSET = 20
GENERATION_PROCESS_QUOTA_END = 24
GENERATION_PROCESS_FLAGS_OFFSET = 24
GENERATION_PROCESS_FLAGS_END = 28

GENERATION_THREAD = struct.Struct("<IIIIIIQQI4x")
GENERATION_THREAD_NAME_OFFSET_OFFSET = 0
GENERATION_THREAD_NAME_OFFSET_END = 4
GENERATION_THREAD_PROCESS_OFFSET = 4
GENERATION_THREAD_PROCESS_END = 8
GENERATION_THREAD_TCB_OBJECT_OFFSET = 8
GENERATION_THREAD_TCB_OBJECT_END = 12
GENERATION_THREAD_SCHEDULE_OFFSET = 12
GENERATION_THREAD_SCHEDULE_END = 16
GENERATION_THREAD_FAULT_POLICY_OFFSET = 16
GENERATION_THREAD_FAULT_POLICY_END = 20
GENERATION_THREAD_IPC_BUFFER_OBJECT_OFFSET = 20
GENERATION_THREAD_IPC_BUFFER_OBJECT_END = 24
GENERATION_THREAD_IPC_BUFFER_VADDR_OFFSET = 24
GENERATION_THREAD_IPC_BUFFER_VADDR_END = 32
GENERATION_THREAD_ENTRY_OFFSET = 32
GENERATION_THREAD_ENTRY_END = 40
GENERATION_THREAD_FLAGS_OFFSET = 40
GENERATION_THREAD_FLAGS_END = 44

GENERATION_KERNEL_OBJECT = struct.Struct("<IIIIIII12x")
GENERATION_KERNEL_OBJECT_NAME_OFFSET_OFFSET = 0
GENERATION_KERNEL_OBJECT_NAME_OFFSET_END = 4
GENERATION_KERNEL_OBJECT_KIND_OFFSET = 4
GENERATION_KERNEL_OBJECT_KIND_END = 8
GENERATION_KERNEL_OBJECT_OWNER_PROCESS_OFFSET = 8
GENERATION_KERNEL_OBJECT_OWNER_PROCESS_END = 12
GENERATION_KERNEL_OBJECT_SIZE_BITS_OFFSET = 12
GENERATION_KERNEL_OBJECT_SIZE_BITS_END = 16
GENERATION_KERNEL_OBJECT_COUNT_OFFSET = 16
GENERATION_KERNEL_OBJECT_COUNT_END = 20
GENERATION_KERNEL_OBJECT_SOURCE_OBJECT_OFFSET = 20
GENERATION_KERNEL_OBJECT_SOURCE_OBJECT_END = 24
GENERATION_KERNEL_OBJECT_FLAGS_OFFSET = 24
GENERATION_KERNEL_OBJECT_FLAGS_END = 28

GENERATION_MAPPING = struct.Struct("<IIQIQQII4x")
GENERATION_MAPPING_PROCESS_OFFSET = 0
GENERATION_MAPPING_PROCESS_END = 4
GENERATION_MAPPING_OBJECT_OFFSET = 4
GENERATION_MAPPING_OBJECT_END = 8
GENERATION_MAPPING_VIRTUAL_ADDRESS_OFFSET = 8
GENERATION_MAPPING_VIRTUAL_ADDRESS_END = 16
GENERATION_MAPPING_PAGE_COUNT_OFFSET = 16
GENERATION_MAPPING_PAGE_COUNT_END = 20
GENERATION_MAPPING_RIGHTS_OFFSET = 20
GENERATION_MAPPING_RIGHTS_END = 28
GENERATION_MAPPING_ATTRIBUTES_OFFSET = 28
GENERATION_MAPPING_ATTRIBUTES_END = 36
GENERATION_MAPPING_SOURCE_OBJECT_OFFSET = 36
GENERATION_MAPPING_SOURCE_OBJECT_END = 40
GENERATION_MAPPING_FLAGS_OFFSET = 40
GENERATION_MAPPING_FLAGS_END = 44

GENERATION_CAP_BINDING = struct.Struct("<IIIQQII12x")
GENERATION_CAP_BINDING_PROCESS_OFFSET = 0
GENERATION_CAP_BINDING_PROCESS_END = 4
GENERATION_CAP_BINDING_SLOT_OFFSET = 4
GENERATION_CAP_BINDING_SLOT_END = 8
GENERATION_CAP_BINDING_OBJECT_OFFSET = 8
GENERATION_CAP_BINDING_OBJECT_END = 12
GENERATION_CAP_BINDING_RIGHTS_OFFSET = 12
GENERATION_CAP_BINDING_RIGHTS_END = 20
GENERATION_CAP_BINDING_BADGE_OFFSET = 20
GENERATION_CAP_BINDING_BADGE_END = 28
GENERATION_CAP_BINDING_GRANT_OFFSET = 28
GENERATION_CAP_BINDING_GRANT_END = 32
GENERATION_CAP_BINDING_FLAGS_OFFSET = 32
GENERATION_CAP_BINDING_FLAGS_END = 36

GENERATION_SERVICE_BINDING = struct.Struct("<IIIIQQI12x")
GENERATION_SERVICE_BINDING_PROCESS_OFFSET = 0
GENERATION_SERVICE_BINDING_PROCESS_END = 4
GENERATION_SERVICE_BINDING_SERVICE_OFFSET = 4
GENERATION_SERVICE_BINDING_SERVICE_END = 8
GENERATION_SERVICE_BINDING_SLOT_OFFSET = 8
GENERATION_SERVICE_BINDING_SLOT_END = 12
GENERATION_SERVICE_BINDING_OBJECT_OFFSET = 12
GENERATION_SERVICE_BINDING_OBJECT_END = 16
GENERATION_SERVICE_BINDING_RIGHTS_OFFSET = 16
GENERATION_SERVICE_BINDING_RIGHTS_END = 24
GENERATION_SERVICE_BINDING_BADGE_OFFSET = 24
GENERATION_SERVICE_BINDING_BADGE_END = 32
GENERATION_SERVICE_BINDING_FLAGS_OFFSET = 32
GENERATION_SERVICE_BINDING_FLAGS_END = 36

GENERATION_SCHEDULE = struct.Struct("<IIIIIQQI8x")
GENERATION_SCHEDULE_NAME_OFFSET_OFFSET = 0
GENERATION_SCHEDULE_NAME_OFFSET_END = 4
GENERATION_SCHEDULE_THREAD_OFFSET = 4
GENERATION_SCHEDULE_THREAD_END = 8
GENERATION_SCHEDULE_AUTHORITY_PROCESS_OFFSET = 8
GENERATION_SCHEDULE_AUTHORITY_PROCESS_END = 12
GENERATION_SCHEDULE_PRIORITY_OFFSET = 12
GENERATION_SCHEDULE_PRIORITY_END = 16
GENERATION_SCHEDULE_MAX_CONTROLLED_PRIORITY_OFFSET = 16
GENERATION_SCHEDULE_MAX_CONTROLLED_PRIORITY_END = 20
GENERATION_SCHEDULE_BUDGET_US_OFFSET = 20
GENERATION_SCHEDULE_BUDGET_US_END = 28
GENERATION_SCHEDULE_PERIOD_US_OFFSET = 28
GENERATION_SCHEDULE_PERIOD_US_END = 36
GENERATION_SCHEDULE_FLAGS_OFFSET = 36
GENERATION_SCHEDULE_FLAGS_END = 40

GENERATION_FAULT_POLICY = struct.Struct("<IIIIQI4x")
GENERATION_FAULT_POLICY_NAME_OFFSET_OFFSET = 0
GENERATION_FAULT_POLICY_NAME_OFFSET_END = 4
GENERATION_FAULT_POLICY_THREAD_OFFSET = 4
GENERATION_FAULT_POLICY_THREAD_END = 8
GENERATION_FAULT_POLICY_HANDLER_PROCESS_OFFSET = 8
GENERATION_FAULT_POLICY_HANDLER_PROCESS_END = 12
GENERATION_FAULT_POLICY_ENDPOINT_OBJECT_OFFSET = 12
GENERATION_FAULT_POLICY_ENDPOINT_OBJECT_END = 16
GENERATION_FAULT_POLICY_BADGE_OFFSET = 16
GENERATION_FAULT_POLICY_BADGE_END = 24
GENERATION_FAULT_POLICY_ACTION_OFFSET = 24
GENERATION_FAULT_POLICY_ACTION_END = 28

GENERATION_SPAWN_TEMPLATE = struct.Struct("<IIIIIIII")
GENERATION_SPAWN_TEMPLATE_NAME_OFFSET_OFFSET = 0
GENERATION_SPAWN_TEMPLATE_NAME_OFFSET_END = 4
GENERATION_SPAWN_TEMPLATE_EXECUTABLE_OFFSET = 4
GENERATION_SPAWN_TEMPLATE_EXECUTABLE_END = 8
GENERATION_SPAWN_TEMPLATE_OWNER_PROCESS_OFFSET = 8
GENERATION_SPAWN_TEMPLATE_OWNER_PROCESS_END = 12
GENERATION_SPAWN_TEMPLATE_QUOTA_OFFSET = 12
GENERATION_SPAWN_TEMPLATE_QUOTA_END = 16
GENERATION_SPAWN_TEMPLATE_SCHEDULE_OFFSET = 16
GENERATION_SPAWN_TEMPLATE_SCHEDULE_END = 20
GENERATION_SPAWN_TEMPLATE_FAULT_POLICY_OFFSET = 20
GENERATION_SPAWN_TEMPLATE_FAULT_POLICY_END = 24
GENERATION_SPAWN_TEMPLATE_MAX_INSTANCES_OFFSET = 24
GENERATION_SPAWN_TEMPLATE_MAX_INSTANCES_END = 28
GENERATION_SPAWN_TEMPLATE_FLAGS_OFFSET = 28
GENERATION_SPAWN_TEMPLATE_FLAGS_END = 32

GENERATION_RESOURCE_QUOTA = struct.Struct("<IIIIIIIIIIIQQI")
GENERATION_RESOURCE_QUOTA_NAME_OFFSET_OFFSET = 0
GENERATION_RESOURCE_QUOTA_NAME_OFFSET_END = 4
GENERATION_RESOURCE_QUOTA_OWNER_PROCESS_OFFSET = 4
GENERATION_RESOURCE_QUOTA_OWNER_PROCESS_END = 8
GENERATION_RESOURCE_QUOTA_CNODE_COUNT_OFFSET = 8
GENERATION_RESOURCE_QUOTA_CNODE_COUNT_END = 12
GENERATION_RESOURCE_QUOTA_TCB_COUNT_OFFSET = 12
GENERATION_RESOURCE_QUOTA_TCB_COUNT_END = 16
GENERATION_RESOURCE_QUOTA_ENDPOINT_COUNT_OFFSET = 16
GENERATION_RESOURCE_QUOTA_ENDPOINT_COUNT_END = 20
GENERATION_RESOURCE_QUOTA_NOTIFICATION_COUNT_OFFSET = 20
GENERATION_RESOURCE_QUOTA_NOTIFICATION_COUNT_END = 24
GENERATION_RESOURCE_QUOTA_FRAME_COUNT_OFFSET = 24
GENERATION_RESOURCE_QUOTA_FRAME_COUNT_END = 28
GENERATION_RESOURCE_QUOTA_PAGE_TABLE_COUNT_OFFSET = 28
GENERATION_RESOURCE_QUOTA_PAGE_TABLE_COUNT_END = 32
GENERATION_RESOURCE_QUOTA_MAPPING_COUNT_OFFSET = 32
GENERATION_RESOURCE_QUOTA_MAPPING_COUNT_END = 36
GENERATION_RESOURCE_QUOTA_IRQ_COUNT_OFFSET = 36
GENERATION_RESOURCE_QUOTA_IRQ_COUNT_END = 40
GENERATION_RESOURCE_QUOTA_CSLOT_COUNT_OFFSET = 40
GENERATION_RESOURCE_QUOTA_CSLOT_COUNT_END = 44
GENERATION_RESOURCE_QUOTA_UNTYPED_BYTES_OFFSET = 44
GENERATION_RESOURCE_QUOTA_UNTYPED_BYTES_END = 52
GENERATION_RESOURCE_QUOTA_DYNAMIC_RESERVE_BYTES_OFFSET = 52
GENERATION_RESOURCE_QUOTA_DYNAMIC_RESERVE_BYTES_END = 60
GENERATION_RESOURCE_QUOTA_FLAGS_OFFSET = 60
GENERATION_RESOURCE_QUOTA_FLAGS_END = 64

GENERATION_MINTED_BINDING = struct.Struct("<IIIIQII")
GENERATION_MINTED_BINDING_NAME_OFFSET_OFFSET = 0
GENERATION_MINTED_BINDING_NAME_OFFSET_END = 4
GENERATION_MINTED_BINDING_OWNER_OFFSET = 4
GENERATION_MINTED_BINDING_OWNER_END = 8
GENERATION_MINTED_BINDING_HOLDER_OFFSET = 8
GENERATION_MINTED_BINDING_HOLDER_END = 12
GENERATION_MINTED_BINDING_SLOT_OFFSET = 12
GENERATION_MINTED_BINDING_SLOT_END = 16
GENERATION_MINTED_BINDING_RIGHTS_OFFSET = 16
GENERATION_MINTED_BINDING_RIGHTS_END = 24
GENERATION_MINTED_BINDING_FLAGS_OFFSET = 24
GENERATION_MINTED_BINDING_FLAGS_END = 28
GENERATION_MINTED_BINDING_CAPABILITY_KIND_OFFSET = 28
GENERATION_MINTED_BINDING_CAPABILITY_KIND_END = 32

GENERATION_NOTIFICATION_GRANT = struct.Struct("<IIIII4x")
GENERATION_NOTIFICATION_GRANT_NAME_OFFSET_OFFSET = 0
GENERATION_NOTIFICATION_GRANT_NAME_OFFSET_END = 4
GENERATION_NOTIFICATION_GRANT_SOURCE_OFFSET = 4
GENERATION_NOTIFICATION_GRANT_SOURCE_END = 8
GENERATION_NOTIFICATION_GRANT_TARGET_OFFSET = 8
GENERATION_NOTIFICATION_GRANT_TARGET_END = 12
GENERATION_NOTIFICATION_GRANT_OBJECT_OFFSET = 12
GENERATION_NOTIFICATION_GRANT_OBJECT_END = 16
GENERATION_NOTIFICATION_GRANT_FLAGS_OFFSET = 16
GENERATION_NOTIFICATION_GRANT_FLAGS_END = 20

GENERATION_NOTIFICATION_BINDING = struct.Struct("<IIIII4x")
GENERATION_NOTIFICATION_BINDING_GRANT_OFFSET = 0
GENERATION_NOTIFICATION_BINDING_GRANT_END = 4
GENERATION_NOTIFICATION_BINDING_HOLDER_OFFSET = 4
GENERATION_NOTIFICATION_BINDING_HOLDER_END = 8
GENERATION_NOTIFICATION_BINDING_SLOT_OFFSET = 8
GENERATION_NOTIFICATION_BINDING_SLOT_END = 12
GENERATION_NOTIFICATION_BINDING_ROLE_OFFSET = 12
GENERATION_NOTIFICATION_BINDING_ROLE_END = 16
GENERATION_NOTIFICATION_BINDING_FLAGS_OFFSET = 16
GENERATION_NOTIFICATION_BINDING_FLAGS_END = 20

MAX_GENERATION_BYTES = 16777216
MAX_OBJECTS = 64
MAX_EXECUTABLES = 48
MAX_INSTANCES = 48
MAX_BINDINGS = 128
MAX_GRANTS = 128
MAX_STATES = 32
MAX_DEPENDENCIES = 128
MAX_HEALTH_INSTANCES = 32
MAX_PROCESSES = 48
MAX_THREADS = 48
MAX_KERNEL_OBJECTS = 4096
MAX_MAPPINGS = 4096
MAX_CAP_BINDINGS = 4096
MAX_SERVICE_BINDINGS = 480
MAX_SCHEDULES = 48
MAX_FAULT_POLICIES = 48
MAX_SPAWN_TEMPLATES = 48
MAX_RESOURCE_QUOTAS = 48
MAX_MINTED_BINDINGS = 256
MAX_NOTIFICATION_GRANTS = 256
MAX_NOTIFICATION_BINDINGS = 512
MAX_STRING_BYTES = 255
MAX_STRING_TABLE_BYTES = 65536
MAX_OBJECT_PAYLOAD_BYTES = 8388608
GENERATION_CAPABILITY_ENDPOINT = 1
GENERATION_CAPABILITY_EXECUTABLE = 2
GENERATION_CAPABILITY_SHARED_BUFFER_FACTORY = 3
GENERATION_CAPABILITY_BLOCK = 4
GENERATION_CAPABILITY_DIRECTORY = 5
GENERATION_CAPABILITY_INPUT = 6
GENERATION_CAPABILITY_SUPERVISION = 7
GENERATION_CAPABILITY_SHARED_BUFFER = 8
GENERATION_CAPABILITY_LOAN = 9
GENERATION_SERVICE_LIFECYCLE = 1
GENERATION_SERVICE_SPAWN = 2
GENERATION_SERVICE_SUPERVISION = 3
GENERATION_SERVICE_CAPABILITY_TRANSFER = 4
GENERATION_SERVICE_SHARED_BUFFER = 5
GENERATION_SERVICE_DIRECTORY = 6
GENERATION_SERVICE_INPUT = 7
GENERATION_SERVICE_BLOCK = 8
GENERATION_SERVICE_CONSOLE = 9
GENERATION_SERVICE_CLOCK = 10
GENERATION_RIGHT_SEND = 1
GENERATION_RIGHT_RECV = 2
GENERATION_RIGHT_TRANSFER = 4
GENERATION_RIGHT_EXEC = 8
GENERATION_RIGHT_MAP_MMIO = 16
GENERATION_RIGHT_DMA_PIN = 32
GENERATION_RIGHT_DMA_RELEASE = 64
GENERATION_RIGHT_IRQ_ACK = 128
GENERATION_RIGHT_BUFFER_WRITE = 256
GENERATION_RIGHT_BUFFER_MAP = 512
GENERATION_RIGHT_BLOCK_READ = 1024
GENERATION_RIGHT_BLOCK_WRITE = 2048
GENERATION_RIGHT_STORE_READ = 4096
GENERATION_RIGHT_STORE_WRITE = 8192
GENERATION_RIGHT_HEALTH_CONFIRM = 16384
GENERATION_RIGHT_BOOT_UPDATE = 32768
GENERATION_RIGHT_SPAWN = 65536
GENERATION_RIGHT_SUPERVISE = 262144
GENERATION_RIGHT_DIRECTORY_READ = 524288
GENERATION_RIGHT_DIRECTORY_WRITE = 1048576
GENERATION_RIGHT_DIRECTORY_LIST = 2097152
GENERATION_RIGHT_DIRECTORY_DERIVE = 4194304
GENERATION_RIGHT_INPUT_READ = 8388608
GENERATION_RIGHT_BUFFER_CREATE = 16777216
GENERATION_RIGHT_BUFFER_LOAN = 33554432
GENERATION_RIGHT_CLOCK_MONOTONIC_READ = 67108864
GENERATION_RIGHT_CLOCK_TIMER_USE = 134217728
GENERATION_RIGHT_CLOCK_SIMULATED_READ = 268435456
GENERATION_RIGHT_CLOCK_SIMULATED_ADVANCE = 536870912
GENERATION_RIGHT_SCHEDULING_PROMOTE = 1073741824
GENERATION_RIGHT_LIFECYCLE_RESTART = 2147483648
GENERATION_RIGHT_PARAMETER_READ = 4294967296
GENERATION_RIGHT_PARAMETER_WRITE = 8589934592
GENERATION_RIGHT_ALL = 17179738111
GENERATION_RIGHT_BY_MANIFEST_NAME = {
    "send": 1,
    "recv": 2,
    "exec": 8,
    "mapMmio": 16,
    "dmaPin": 32,
    "dmaRelease": 64,
    "irqAck": 128,
    "bufferWrite": 256,
    "bufferMap": 512,
    "blockRead": 1024,
    "blockWrite": 2048,
    "storeRead": 4096,
    "storeWrite": 8192,
    "healthConfirm": 16384,
    "bootUpdate": 32768,
    "spawn": 65536,
    "supervise": 262144,
    "directoryRead": 524288,
    "directoryWrite": 1048576,
    "directoryList": 2097152,
    "directoryDerive": 4194304,
    "inputRead": 8388608,
    "bufferCreate": 16777216,
    "bufferLoan": 33554432,
    "clockMonotonicRead": 67108864,
    "clockTimerUse": 134217728,
    "clockSimulatedRead": 268435456,
    "clockSimulatedAdvance": 536870912,
    "schedulingPromote": 1073741824,
    "lifecycleRestart": 2147483648,
    "parameterRead": 4294967296,
    "parameterWrite": 8589934592,
}
GENERATION_RIGHT_RECORDED = 469762048
GENERATION_RIGHT_UNRECORDED = 8103247091

KERNEL_MAGIC = b"SLIMEKR2"
KERNEL_LEGACY_MAGIC = b"SLIMEKRN"
KERNEL_VERSION = 2
KERNEL_LEGACY_VERSION = 1
KERNEL_LEGACY_HEADER_LEN = 64
KERNEL_ABI_VERSION = 2
KERNEL_HEADER = struct.Struct("<8sIIIIIIIIQQQIIQQ")
KERNEL_HEADER_MAGIC_OFFSET = 0
KERNEL_HEADER_MAGIC_END = 8
KERNEL_HEADER_FORMAT_VERSION_OFFSET = 8
KERNEL_HEADER_FORMAT_VERSION_END = 12
KERNEL_HEADER_HEADER_SIZE_OFFSET = 12
KERNEL_HEADER_HEADER_SIZE_END = 16
KERNEL_HEADER_KERNEL_ABI_OFFSET = 16
KERNEL_HEADER_KERNEL_ABI_END = 20
KERNEL_HEADER_REQUIRED_FLAGS_OFFSET = 20
KERNEL_HEADER_REQUIRED_FLAGS_END = 24
KERNEL_HEADER_ARCHITECTURE_OFFSET = 24
KERNEL_HEADER_ARCHITECTURE_END = 28
KERNEL_HEADER_ABI_OFFSET = 28
KERNEL_HEADER_ABI_END = 32
KERNEL_HEADER_PAGE_PROFILE_OFFSET = 32
KERNEL_HEADER_PAGE_PROFILE_END = 36
KERNEL_HEADER_TARGET_PROFILE_OFFSET = 36
KERNEL_HEADER_TARGET_PROFILE_END = 40
KERNEL_HEADER_REQUIRED_FEATURES_OFFSET = 40
KERNEL_HEADER_REQUIRED_FEATURES_END = 48
KERNEL_HEADER_PREFERRED_BASE_OFFSET = 48
KERNEL_HEADER_PREFERRED_BASE_END = 56
KERNEL_HEADER_ENTRY_OFFSET_OFFSET = 56
KERNEL_HEADER_ENTRY_OFFSET_END = 64
KERNEL_HEADER_SEGMENT_COUNT_OFFSET = 64
KERNEL_HEADER_SEGMENT_COUNT_END = 68
KERNEL_HEADER_RELOCATION_COUNT_OFFSET = 68
KERNEL_HEADER_RELOCATION_COUNT_END = 72
KERNEL_HEADER_PAYLOAD_OFFSET_OFFSET = 72
KERNEL_HEADER_PAYLOAD_OFFSET_END = 80
KERNEL_HEADER_TOTAL_LEN_OFFSET = 80
KERNEL_HEADER_TOTAL_LEN_END = 88

KERNEL_SEGMENT = struct.Struct("<QQQQII")
KERNEL_SEGMENT_VADDR_OFFSET_OFFSET = 0
KERNEL_SEGMENT_VADDR_OFFSET_END = 8
KERNEL_SEGMENT_MEM_LEN_OFFSET = 8
KERNEL_SEGMENT_MEM_LEN_END = 16
KERNEL_SEGMENT_FILE_OFFSET_OFFSET = 16
KERNEL_SEGMENT_FILE_OFFSET_END = 24
KERNEL_SEGMENT_FILE_LEN_OFFSET = 24
KERNEL_SEGMENT_FILE_LEN_END = 32
KERNEL_SEGMENT_FLAGS_OFFSET = 32
KERNEL_SEGMENT_FLAGS_END = 36
KERNEL_SEGMENT_RESERVED_OFFSET = 36
KERNEL_SEGMENT_RESERVED_END = 40

KERNEL_RELOCATION = struct.Struct("<Qq")
KERNEL_RELOCATION_TARGET_OFFSET_OFFSET = 0
KERNEL_RELOCATION_TARGET_OFFSET_END = 8
KERNEL_RELOCATION_ADDEND_OFFSET = 8
KERNEL_RELOCATION_ADDEND_END = 16

KERNEL_PREFERRED_BASE = 0xFFFF_FFFF_8000_0000
KERNEL_LOAD_BASE = 0xFFFF_FFFF_9000_0000
MAX_KERNEL_IMAGE_BYTES = 8388608
MAX_KERNEL_SEGMENTS = 8
MAX_KERNEL_RELOCATIONS = 16384
SEGMENT_WRITE = 1
SEGMENT_EXEC = 2

TARGET_PROFILE_VERSION = 1
TARGET_PROFILE_MAX_NAME_BYTES = 32
ARCH_X86_64 = 1
ARCH_AARCH64 = 2
ARCH_RISCV64 = 3
ABI_SLIME_X86_64_V1 = 1
ABI_SLIME_AARCH64_V1 = 2
ABI_SLIME_RISCV64_V1 = 3
ABI_SLIME_AARCH64_SEL4_V1 = 4
PAGE_PROFILE_X86_64_4K = 1
PAGE_PROFILE_AARCH64_4K = 2
PAGE_PROFILE_RISCV64_SV39_4K = 3
FEATURE_X86_64_BASELINE = 1
FEATURE_AARCH64_BASELINE = 2
FEATURE_AARCH64_GICV3 = 4
FEATURE_AARCH64_GICV2 = 32
FEATURE_AARCH64_GENERIC_TIMER = 8
FEATURE_RISCV64_BASELINE = 16
FEATURE_AARCH64_SEL4 = 64
PROFILE_X86_64_QEMU_VIRTIO = 1
PROFILE_AARCH64_QEMU_VIRT = 2
PROFILE_AARCH64_RPI5 = 3
PROFILE_AARCH64_SEL4_QEMU_VIRT = 5
PROFILE_RISCV64_QEMU_VIRT = 4

class TargetProfile(typing.NamedTuple):
    id: int
    name: str
    architecture: int
    abi: int
    page_profile: int
    required_features: int
    elf_machine: int
    page_bytes: int
    kernel_preferred_base: int
    kernel_load_base: int
    component_base: int
    cargo_target: str
    qemu_binary: str


TARGET_PROFILES = (
    TargetProfile(
        id=1,
        name="x86_64-qemu-virtio",
        architecture=1,
        abi=1,
        page_profile=1,
        required_features=1,
        elf_machine=62,
        page_bytes=4096,
        kernel_preferred_base=0xFFFF_FFFF_8000_0000,
        kernel_load_base=0xFFFF_FFFF_9000_0000,
        component_base=0x0040_0000,
        cargo_target="x86_64-unknown-none",
        qemu_binary="qemu-system-x86_64",
    ),
    TargetProfile(
        id=2,
        name="aarch64-qemu-virt",
        architecture=2,
        abi=2,
        page_profile=2,
        required_features=14,
        elf_machine=183,
        page_bytes=4096,
        kernel_preferred_base=0xFFFF_FFFF_8000_0000,
        kernel_load_base=0xFFFF_FFFF_9000_0000,
        component_base=0x0040_0000,
        cargo_target="aarch64-unknown-none",
        qemu_binary="qemu-system-aarch64",
    ),
    TargetProfile(
        id=3,
        name="aarch64-rpi5",
        architecture=2,
        abi=2,
        page_profile=2,
        required_features=42,
        elf_machine=183,
        page_bytes=4096,
        kernel_preferred_base=0xFFFF_FFFF_8000_0000,
        kernel_load_base=0xFFFF_FFFF_9000_0000,
        component_base=0x0040_0000,
        cargo_target="aarch64-unknown-none",
        qemu_binary="",
    ),
    TargetProfile(
        id=5,
        name="aarch64-sel4-qemu-virt",
        architecture=2,
        abi=4,
        page_profile=2,
        required_features=66,
        elf_machine=183,
        page_bytes=4096,
        kernel_preferred_base=0xFFFF_FFFF_8000_0000,
        kernel_load_base=0xFFFF_FFFF_9000_0000,
        component_base=0x0040_0000,
        cargo_target="deps/rust-sel4/support/targets/aarch64-sel4-minimal.json",
        qemu_binary="qemu-system-aarch64",
    ),
    TargetProfile(
        id=4,
        name="riscv64-qemu-virt",
        architecture=3,
        abi=3,
        page_profile=3,
        required_features=16,
        elf_machine=243,
        page_bytes=4096,
        kernel_preferred_base=0xFFFF_FFFF_8000_0000,
        kernel_load_base=0xFFFF_FFFF_9000_0000,
        component_base=0x0040_0000,
        cargo_target="riscv64gc-unknown-none-elf",
        qemu_binary="qemu-system-riscv64",
    ),
)
TARGET_PROFILES_BY_NAME = {profile.name: profile for profile in TARGET_PROFILES}
TARGET_PROFILES_BY_ID = {profile.id: profile for profile in TARGET_PROFILES}

COMPONENT_IMAGE_MAGIC = b"SLIMECM2"
COMPONENT_IMAGE_LEGACY_MAGIC = b"SLIMECMP"
COMPONENT_IMAGE_ELF_MAGIC = b"SLIMECME"
COMPONENT_IMAGE_ELF_VERSION = 2
COMPONENT_IMAGE_ELF_HEADER_LEN = 56
COMPONENT_IMAGE_VERSION = 2
COMPONENT_IMAGE_LEGACY_VERSION = 1
COMPONENT_IMAGE_LEGACY_HEADER_LEN = 32
COMPONENT_IMAGE_KERNEL_ABI = 1
COMPONENT_IMAGE_MAX_SEGMENTS = 16
MAX_COMPONENT_IMAGE_BYTES = 16777216
COMPONENT_MAX_STACK_BYTES = 1048576
COMPONENT_DEFAULT_STACK_BYTES = 16384
COMPONENT_SEGMENT_FLAG_WRITE = 1
COMPONENT_SEGMENT_FLAG_EXEC = 2
COMPONENT_IMAGE_HEADER = struct.Struct("<8sIIIIIIIHHIIQ")
COMPONENT_IMAGE_HEADER_MAGIC_OFFSET = 0
COMPONENT_IMAGE_HEADER_MAGIC_END = 8
COMPONENT_IMAGE_HEADER_FORMAT_VERSION_OFFSET = 8
COMPONENT_IMAGE_HEADER_FORMAT_VERSION_END = 12
COMPONENT_IMAGE_HEADER_HEADER_SIZE_OFFSET = 12
COMPONENT_IMAGE_HEADER_HEADER_SIZE_END = 16
COMPONENT_IMAGE_HEADER_KERNEL_ABI_OFFSET = 16
COMPONENT_IMAGE_HEADER_KERNEL_ABI_END = 20
COMPONENT_IMAGE_HEADER_ARCHITECTURE_OFFSET = 20
COMPONENT_IMAGE_HEADER_ARCHITECTURE_END = 24
COMPONENT_IMAGE_HEADER_ABI_OFFSET = 24
COMPONENT_IMAGE_HEADER_ABI_END = 28
COMPONENT_IMAGE_HEADER_PAGE_PROFILE_OFFSET = 28
COMPONENT_IMAGE_HEADER_PAGE_PROFILE_END = 32
COMPONENT_IMAGE_HEADER_ENTRY_OFFSET_OFFSET = 32
COMPONENT_IMAGE_HEADER_ENTRY_OFFSET_END = 36
COMPONENT_IMAGE_HEADER_SEGMENT_COUNT_OFFSET = 36
COMPONENT_IMAGE_HEADER_SEGMENT_COUNT_END = 38
COMPONENT_IMAGE_HEADER_RESERVED_OFFSET = 38
COMPONENT_IMAGE_HEADER_RESERVED_END = 40
COMPONENT_IMAGE_HEADER_STACK_BYTES_OFFSET = 40
COMPONENT_IMAGE_HEADER_STACK_BYTES_END = 44
COMPONENT_IMAGE_HEADER_TARGET_PROFILE_OFFSET = 44
COMPONENT_IMAGE_HEADER_TARGET_PROFILE_END = 48
COMPONENT_IMAGE_HEADER_REQUIRED_FEATURES_OFFSET = 48
COMPONENT_IMAGE_HEADER_REQUIRED_FEATURES_END = 56

COMPONENT_IMAGE_SEGMENT = struct.Struct("<IIIIHH")
COMPONENT_IMAGE_SEGMENT_VADDR_OFFSET_OFFSET = 0
COMPONENT_IMAGE_SEGMENT_VADDR_OFFSET_END = 4
COMPONENT_IMAGE_SEGMENT_MEM_LEN_OFFSET = 4
COMPONENT_IMAGE_SEGMENT_MEM_LEN_END = 8
COMPONENT_IMAGE_SEGMENT_FILE_OFFSET_OFFSET = 8
COMPONENT_IMAGE_SEGMENT_FILE_OFFSET_END = 12
COMPONENT_IMAGE_SEGMENT_FILE_LEN_OFFSET = 12
COMPONENT_IMAGE_SEGMENT_FILE_LEN_END = 16
COMPONENT_IMAGE_SEGMENT_FLAGS_OFFSET = 16
COMPONENT_IMAGE_SEGMENT_FLAGS_END = 18
COMPONENT_IMAGE_SEGMENT_RESERVED_OFFSET = 18
COMPONENT_IMAGE_SEGMENT_RESERVED_END = 20

BOOTSTATE_MAGIC = b"SLIMEBS\0"
BOOTSTATE_VERSION = 2
BOOTSTATE_SLOT_BYTES = 512
BOOTSTATE_SLOT_COUNT = 2
BOOTSTATE_REQUIRED_FLAGS = 0
BOOTSTATE_SLOT = struct.Struct("<8sIIQQ32s32sII32s32sQ32s304x")
BOOTSTATE_MAGIC_OFFSET = 0
BOOTSTATE_MAGIC_END = 8
BOOTSTATE_FORMAT_VERSION_OFFSET = 8
BOOTSTATE_FORMAT_VERSION_END = 12
BOOTSTATE_HEADER_SIZE_OFFSET = 12
BOOTSTATE_HEADER_SIZE_END = 16
BOOTSTATE_REQUIRED_FLAGS_OFFSET = 16
BOOTSTATE_REQUIRED_FLAGS_END = 24
BOOTSTATE_SEQUENCE_OFFSET = 24
BOOTSTATE_SEQUENCE_END = 32
BOOTSTATE_KNOWN_GOOD_OFFSET = 32
BOOTSTATE_KNOWN_GOOD_END = 64
BOOTSTATE_PENDING_OFFSET = 64
BOOTSTATE_PENDING_END = 96
BOOTSTATE_REMAINING_ATTEMPTS_OFFSET = 96
BOOTSTATE_REMAINING_ATTEMPTS_END = 100
BOOTSTATE_RESERVED_OFFSET = 100
BOOTSTATE_RESERVED_END = 104
BOOTSTATE_GENERATION_ROOT_OFFSET = 104
BOOTSTATE_GENERATION_ROOT_END = 136
BOOTSTATE_STATE_ROOT_OFFSET = 136
BOOTSTATE_STATE_ROOT_END = 168
BOOTSTATE_ACCEPTED_RELEASE_SEQUENCE_OFFSET = 168
BOOTSTATE_ACCEPTED_RELEASE_SEQUENCE_END = 176
BOOTSTATE_CHECKSUM_OFFSET = 176
BOOTSTATE_CHECKSUM_END = 208

BOOTSTORE_HEADER = struct.Struct("<8sIIQIIQQ32s16x")
BOOTSTORE_HEADER_MAGIC_OFFSET = 0
BOOTSTORE_HEADER_MAGIC_END = 8
BOOTSTORE_HEADER_FORMAT_VERSION_OFFSET = 8
BOOTSTORE_HEADER_FORMAT_VERSION_END = 12
BOOTSTORE_HEADER_HEADER_SIZE_OFFSET = 12
BOOTSTORE_HEADER_HEADER_SIZE_END = 16
BOOTSTORE_HEADER_REQUIRED_FLAGS_OFFSET = 16
BOOTSTORE_HEADER_REQUIRED_FLAGS_END = 24
BOOTSTORE_HEADER_ENTRY_COUNT_OFFSET = 24
BOOTSTORE_HEADER_ENTRY_COUNT_END = 28
BOOTSTORE_HEADER_RESERVED_OFFSET = 28
BOOTSTORE_HEADER_RESERVED_END = 32
BOOTSTORE_HEADER_DIRECTORY_LEN_OFFSET = 32
BOOTSTORE_HEADER_DIRECTORY_LEN_END = 40
BOOTSTORE_HEADER_CAPACITY_OFFSET = 40
BOOTSTORE_HEADER_CAPACITY_END = 48
BOOTSTORE_HEADER_CHECKSUM_OFFSET = 48
BOOTSTORE_HEADER_CHECKSUM_END = 80

BOOTSTORE_ENTRY = struct.Struct("<32sQQQQ32x")
BOOTSTORE_ENTRY_IDENTITY_OFFSET = 0
BOOTSTORE_ENTRY_IDENTITY_END = 32
BOOTSTORE_ENTRY_GENERATION_OFFSET_OFFSET = 32
BOOTSTORE_ENTRY_GENERATION_OFFSET_END = 40
BOOTSTORE_ENTRY_GENERATION_LEN_OFFSET = 40
BOOTSTORE_ENTRY_GENERATION_LEN_END = 48
BOOTSTORE_ENTRY_RELEASE_OFFSET_OFFSET = 48
BOOTSTORE_ENTRY_RELEASE_OFFSET_END = 56
BOOTSTORE_ENTRY_RELEASE_LEN_OFFSET = 56
BOOTSTORE_ENTRY_RELEASE_LEN_END = 64

BOOTSTATE_RELEASE_SEQUENCE_OFFSET = BOOTSTATE_ACCEPTED_RELEASE_SEQUENCE_OFFSET
BOOTSTORE_MAGIC = b"SLIMEBT\0"
BOOTSTORE_VERSION = 1
BOOTSTORE_CAPACITY = 33554432
BOOTSTORE_DIRECTORY_OFFSET = 4096
BOOTSTORE_RELEASES_OFFSET = 8192
BOOTSTORE_GENERATIONS_OFFSET = 16384

BOOTSTATE_TRACE_VERSION = 1
BOOTSTATE_TRACE_MAX_LINE = 640
BOOTSTATE_TRACE_PREFIX = "[bootstate-trace]"

RELEASE_MAGIC = b"SLIMERL\0"
RELEASE_VERSION = 2
RELEASE_BYTES = 512
RELEASE_HEADER_BYTES = 208
RELEASE_SIGNATURE_BYTES = 96
MAX_RELEASE_SIGNATURES = 3
MAX_TARGET_BYTES = 32
ROTATION_MAGIC = b"SLIMERT\0"
ROTATION_VERSION = 1
ROTATION_BYTES = 1024
ROTATION_HEADER_BYTES = 64
MAX_TRUST_KEYS = 4
SIGN_NAMESPACE = "slime-release"
RELEASE_HEADER = struct.Struct("<8sIIQ32s32sQII32s32s32sI4s")
RELEASE_HEADER_MAGIC_OFFSET = 0
RELEASE_HEADER_MAGIC_END = 8
RELEASE_HEADER_FORMAT_VERSION_OFFSET = 8
RELEASE_HEADER_FORMAT_VERSION_END = 12
RELEASE_HEADER_HEADER_SIZE_OFFSET = 12
RELEASE_HEADER_HEADER_SIZE_END = 16
RELEASE_HEADER_REQUIRED_FLAGS_OFFSET = 16
RELEASE_HEADER_REQUIRED_FLAGS_END = 24
RELEASE_HEADER_GENERATION_IDENTITY_OFFSET = 24
RELEASE_HEADER_GENERATION_IDENTITY_END = 56
RELEASE_HEADER_PARENT_IDENTITY_OFFSET = 56
RELEASE_HEADER_PARENT_IDENTITY_END = 88
RELEASE_HEADER_RELEASE_SEQUENCE_OFFSET = 88
RELEASE_HEADER_RELEASE_SEQUENCE_END = 96
RELEASE_HEADER_TARGET_LEN_OFFSET = 96
RELEASE_HEADER_TARGET_LEN_END = 100
RELEASE_HEADER_TRUST_ROOT_VERSION_OFFSET = 100
RELEASE_HEADER_TRUST_ROOT_VERSION_END = 104
RELEASE_HEADER_TARGET_OFFSET = 104
RELEASE_HEADER_TARGET_END = 136
RELEASE_HEADER_BOOT_BUNDLE_IDENTITY_OFFSET = 136
RELEASE_HEADER_BOOT_BUNDLE_IDENTITY_END = 168
RELEASE_HEADER_AUTHORITY_MANIFEST_OFFSET = 168
RELEASE_HEADER_AUTHORITY_MANIFEST_END = 200
RELEASE_HEADER_SIGNATURE_COUNT_OFFSET = 200
RELEASE_HEADER_SIGNATURE_COUNT_END = 204
RELEASE_HEADER_RESERVED_OFFSET = 204
RELEASE_HEADER_RESERVED_END = 208

RELEASE_SIGNATURE = struct.Struct("<32s64s")
RELEASE_SIGNATURE_KEY_ID_OFFSET = 0
RELEASE_SIGNATURE_KEY_ID_END = 32
RELEASE_SIGNATURE_SIGNATURE_OFFSET = 32
RELEASE_SIGNATURE_SIGNATURE_END = 96

ROTATION_HEADER = struct.Struct("<8sIIQIIIIII16x")
ROTATION_HEADER_MAGIC_OFFSET = 0
ROTATION_HEADER_MAGIC_END = 8
ROTATION_HEADER_FORMAT_VERSION_OFFSET = 8
ROTATION_HEADER_FORMAT_VERSION_END = 12
ROTATION_HEADER_HEADER_SIZE_OFFSET = 12
ROTATION_HEADER_HEADER_SIZE_END = 16
ROTATION_HEADER_REQUIRED_FLAGS_OFFSET = 16
ROTATION_HEADER_REQUIRED_FLAGS_END = 24
ROTATION_HEADER_PREVIOUS_VERSION_OFFSET = 24
ROTATION_HEADER_PREVIOUS_VERSION_END = 28
ROTATION_HEADER_REPLACEMENT_VERSION_OFFSET = 28
ROTATION_HEADER_REPLACEMENT_VERSION_END = 32
ROTATION_HEADER_REPLACEMENT_THRESHOLD_OFFSET = 32
ROTATION_HEADER_REPLACEMENT_THRESHOLD_END = 36
ROTATION_HEADER_REPLACEMENT_KEY_COUNT_OFFSET = 36
ROTATION_HEADER_REPLACEMENT_KEY_COUNT_END = 40
ROTATION_HEADER_PREVIOUS_SIGNATURE_COUNT_OFFSET = 40
ROTATION_HEADER_PREVIOUS_SIGNATURE_COUNT_END = 44
ROTATION_HEADER_REPLACEMENT_SIGNATURE_COUNT_OFFSET = 44
ROTATION_HEADER_REPLACEMENT_SIGNATURE_COUNT_END = 48

RECOVERY_INDEX_MAGIC = b"SLIMERC\0"
RECOVERY_INDEX_VERSION = 1
RECOVERY_INDEX_HEADER_BYTES = 160
RECOVERY_STATE_ENTRY_BYTES = 72
MAX_RECOVERY_STATE_OBJECTS = 32
RECOVERY_INDEX_HEADER = struct.Struct("<8sIIQ32s32s32sQIIIQQ4s")
RECOVERY_INDEX_MAGIC_OFFSET = 0
RECOVERY_INDEX_MAGIC_END = 8
RECOVERY_INDEX_FORMAT_VERSION_OFFSET = 8
RECOVERY_INDEX_FORMAT_VERSION_END = 12
RECOVERY_INDEX_HEADER_SIZE_OFFSET = 12
RECOVERY_INDEX_HEADER_SIZE_END = 16
RECOVERY_INDEX_REQUIRED_FLAGS_OFFSET = 16
RECOVERY_INDEX_REQUIRED_FLAGS_END = 24
RECOVERY_INDEX_TARGET_GENERATION_OFFSET = 24
RECOVERY_INDEX_TARGET_GENERATION_END = 56
RECOVERY_INDEX_GENERATION_ROOT_OFFSET = 56
RECOVERY_INDEX_GENERATION_ROOT_END = 88
RECOVERY_INDEX_STATE_ROOT_OFFSET = 88
RECOVERY_INDEX_STATE_ROOT_END = 120
RECOVERY_INDEX_ACCEPTED_RELEASE_SEQUENCE_OFFSET = 120
RECOVERY_INDEX_ACCEPTED_RELEASE_SEQUENCE_END = 128
RECOVERY_INDEX_TARGET_PCI_BDF_OFFSET = 128
RECOVERY_INDEX_TARGET_PCI_BDF_END = 132
RECOVERY_INDEX_STATE_COUNT_OFFSET = 132
RECOVERY_INDEX_STATE_COUNT_END = 136
RECOVERY_INDEX_TOTAL_LEN_OFFSET = 136
RECOVERY_INDEX_TOTAL_LEN_END = 140
RECOVERY_INDEX_STATE_FIRST_LBA_OFFSET = 140
RECOVERY_INDEX_STATE_FIRST_LBA_END = 148
RECOVERY_INDEX_STATE_LAST_LBA_OFFSET = 148
RECOVERY_INDEX_STATE_LAST_LBA_END = 156
RECOVERY_INDEX_RESERVED_OFFSET = 156
RECOVERY_INDEX_RESERVED_END = 160

RECOVERY_STATE_ENTRY = struct.Struct("<32s32sI4s")
RECOVERY_STATE_BINDING_IDENTITY_OFFSET = 0
RECOVERY_STATE_BINDING_IDENTITY_END = 32
RECOVERY_STATE_OBJECT_IDENTITY_OFFSET = 32
RECOVERY_STATE_OBJECT_IDENTITY_END = 64
RECOVERY_STATE_SCHEMA_VERSION_OFFSET = 64
RECOVERY_STATE_SCHEMA_VERSION_END = 68
RECOVERY_STATE_RESERVED_OFFSET = 68
RECOVERY_STATE_RESERVED_END = 72

TRANSFER_MAGIC = b"SLIMETR\0"
TRANSFER_VERSION = 1
TRANSFER_HEADER_BYTES = 320
TRANSFER_OBJECT_BYTES = 64
TRANSFER_STATE_BYTES = 80
TRANSFER_MAX_BYTES = 33554432
TRANSFER_OBJECT_FLAG_PAYLOAD = 1
TRANSFER_STATE_FLAG_TRAVEL = 1
TRANSFER_STATE_FLAG_READ_ONLY = 2
TRANSFER_HEADER = struct.Struct("<8sIIQ32s32s32s32sQQQIIQQQQQQQQ32s40x")
TRANSFER_HEADER_MAGIC_OFFSET = 0
TRANSFER_HEADER_MAGIC_END = 8
TRANSFER_HEADER_FORMAT_VERSION_OFFSET = 8
TRANSFER_HEADER_FORMAT_VERSION_END = 12
TRANSFER_HEADER_HEADER_SIZE_OFFSET = 12
TRANSFER_HEADER_HEADER_SIZE_END = 16
TRANSFER_HEADER_REQUIRED_FLAGS_OFFSET = 16
TRANSFER_HEADER_REQUIRED_FLAGS_END = 24
TRANSFER_HEADER_GENERATION_OFFSET = 24
TRANSFER_HEADER_GENERATION_END = 56
TRANSFER_HEADER_PARENT_OFFSET = 56
TRANSFER_HEADER_PARENT_END = 88
TRANSFER_HEADER_SOURCE_STATE_ROOT_OFFSET = 88
TRANSFER_HEADER_SOURCE_STATE_ROOT_END = 120
TRANSFER_HEADER_AUTHORITY_MANIFEST_OFFSET = 120
TRANSFER_HEADER_AUTHORITY_MANIFEST_END = 152
TRANSFER_HEADER_RELEASE_SEQUENCE_OFFSET = 152
TRANSFER_HEADER_RELEASE_SEQUENCE_END = 160
TRANSFER_HEADER_GENERATION_LEN_OFFSET = 160
TRANSFER_HEADER_GENERATION_LEN_END = 168
TRANSFER_HEADER_RESERVED_OFFSET = 168
TRANSFER_HEADER_RESERVED_END = 176
TRANSFER_HEADER_OBJECT_COUNT_OFFSET = 176
TRANSFER_HEADER_OBJECT_COUNT_END = 180
TRANSFER_HEADER_STATE_COUNT_OFFSET = 180
TRANSFER_HEADER_STATE_COUNT_END = 184
TRANSFER_HEADER_OBJECT_OFFSET_OFFSET = 184
TRANSFER_HEADER_OBJECT_OFFSET_END = 192
TRANSFER_HEADER_STATE_OFFSET_OFFSET = 192
TRANSFER_HEADER_STATE_OFFSET_END = 200
TRANSFER_HEADER_RELEASE_OFFSET_OFFSET = 200
TRANSFER_HEADER_RELEASE_OFFSET_END = 208
TRANSFER_HEADER_METADATA_OFFSET_OFFSET = 208
TRANSFER_HEADER_METADATA_OFFSET_END = 216
TRANSFER_HEADER_METADATA_LEN_OFFSET = 216
TRANSFER_HEADER_METADATA_LEN_END = 224
TRANSFER_HEADER_PAYLOAD_OFFSET_OFFSET = 224
TRANSFER_HEADER_PAYLOAD_OFFSET_END = 232
TRANSFER_HEADER_TOTAL_LEN_OFFSET = 232
TRANSFER_HEADER_TOTAL_LEN_END = 240
TRANSFER_HEADER_RESERVED_TAIL_OFFSET = 240
TRANSFER_HEADER_RESERVED_TAIL_END = 248
TRANSFER_HEADER_HASH_OFFSET = 248
TRANSFER_HEADER_HASH_END = 280

TRANSFER_OBJECT = struct.Struct("<32sQQII8x")
TRANSFER_OBJECT_DIGEST_OFFSET = 0
TRANSFER_OBJECT_DIGEST_END = 32
TRANSFER_OBJECT_LENGTH_OFFSET = 32
TRANSFER_OBJECT_LENGTH_END = 40
TRANSFER_OBJECT_PAYLOAD_OFFSET_OFFSET = 40
TRANSFER_OBJECT_PAYLOAD_OFFSET_END = 48
TRANSFER_OBJECT_KIND_OFFSET = 48
TRANSFER_OBJECT_KIND_END = 52
TRANSFER_OBJECT_FLAGS_OFFSET = 52
TRANSFER_OBJECT_FLAGS_END = 56

TRANSFER_STATE = struct.Struct("<32s32sIII4x")
TRANSFER_STATE_BINDING_OFFSET = 0
TRANSFER_STATE_BINDING_END = 32
TRANSFER_STATE_STATE_ROOT_OFFSET = 32
TRANSFER_STATE_STATE_ROOT_END = 64
TRANSFER_STATE_SCHEMA_VERSION_OFFSET = 64
TRANSFER_STATE_SCHEMA_VERSION_END = 68
TRANSFER_STATE_POLICY_OFFSET = 68
TRANSFER_STATE_POLICY_END = 72
TRANSFER_STATE_FLAGS_OFFSET = 72
TRANSFER_STATE_FLAGS_END = 76

STORE_SUPERBLOCK_MAGIC = b"SLIMESB\0"
STORE_RECORD_MAGIC = b"SLIMEOR\0"
STORE_FORMAT_VERSION = 1
STORE_RECORD_AREA_START = 2
STORE_SLOT_A_LBA = 0
STORE_SLOT_B_LBA = 1
STORE_MAX_OBJECTS = 64
STORE_MAX_OBJECT_PAYLOAD = 32768
STORE_SECTOR_BYTES = 512
STORE_SUPERBLOCK = struct.Struct("<8sIIQQIIQQII")
STORE_SUPERBLOCK_MAGIC_OFFSET = 0
STORE_SUPERBLOCK_MAGIC_END = 8
STORE_SUPERBLOCK_FORMAT_VERSION_OFFSET = 8
STORE_SUPERBLOCK_FORMAT_VERSION_END = 12
STORE_SUPERBLOCK_HEADER_SIZE_OFFSET = 12
STORE_SUPERBLOCK_HEADER_SIZE_END = 16
STORE_SUPERBLOCK_SEQUENCE_OFFSET = 16
STORE_SUPERBLOCK_SEQUENCE_END = 24
STORE_SUPERBLOCK_APPEND_LBA_OFFSET = 24
STORE_SUPERBLOCK_APPEND_LBA_END = 32
STORE_SUPERBLOCK_OBJECT_COUNT_OFFSET = 32
STORE_SUPERBLOCK_OBJECT_COUNT_END = 36
STORE_SUPERBLOCK_FLAGS_OFFSET = 36
STORE_SUPERBLOCK_FLAGS_END = 40
STORE_SUPERBLOCK_RECORD_AREA_START_OFFSET = 40
STORE_SUPERBLOCK_RECORD_AREA_START_END = 48
STORE_SUPERBLOCK_PARTITION_SECTORS_OFFSET = 48
STORE_SUPERBLOCK_PARTITION_SECTORS_END = 56
STORE_SUPERBLOCK_RESERVED_OFFSET = 56
STORE_SUPERBLOCK_RESERVED_END = 60
STORE_SUPERBLOCK_CRC32_OFFSET = 60
STORE_SUPERBLOCK_CRC32_END = 64

STORE_RECORD = struct.Struct("<8sIIIIQ32s")
STORE_RECORD_MAGIC_OFFSET = 0
STORE_RECORD_MAGIC_END = 8
STORE_RECORD_FORMAT_VERSION_OFFSET = 8
STORE_RECORD_FORMAT_VERSION_END = 12
STORE_RECORD_HEADER_SIZE_OFFSET = 12
STORE_RECORD_HEADER_SIZE_END = 16
STORE_RECORD_OBJ_TYPE_OFFSET = 16
STORE_RECORD_OBJ_TYPE_END = 20
STORE_RECORD_FLAGS_OFFSET = 20
STORE_RECORD_FLAGS_END = 24
STORE_RECORD_PAYLOAD_LEN_OFFSET = 24
STORE_RECORD_PAYLOAD_LEN_END = 32
STORE_RECORD_CONTENT_HASH_OFFSET = 32
STORE_RECORD_CONTENT_HASH_END = 64

SHARED_BUFFER_BUDGET_MAGIC = b"SLIMESB\0"
SHARED_BUFFER_BUDGET_VERSION = 1
SHARED_BUFFER_BUDGET_HEADER_BYTES = 32
SHARED_BUFFER_BUDGET_ENTRY_BYTES = 48
MAX_SHARED_BUFFER_BUDGET_HOLDERS = 32
SHARED_BUFFER_BUDGET_HEADER = struct.Struct("<8sIIQII")
SHARED_BUFFER_BUDGET_MAGIC_OFFSET = 0
SHARED_BUFFER_BUDGET_MAGIC_END = 8
SHARED_BUFFER_BUDGET_FORMAT_VERSION_OFFSET = 8
SHARED_BUFFER_BUDGET_FORMAT_VERSION_END = 12
SHARED_BUFFER_BUDGET_HEADER_SIZE_OFFSET = 12
SHARED_BUFFER_BUDGET_HEADER_SIZE_END = 16
SHARED_BUFFER_BUDGET_REQUIRED_FLAGS_OFFSET = 16
SHARED_BUFFER_BUDGET_REQUIRED_FLAGS_END = 24
SHARED_BUFFER_BUDGET_HOLDER_COUNT_OFFSET = 24
SHARED_BUFFER_BUDGET_HOLDER_COUNT_END = 28
SHARED_BUFFER_BUDGET_TOTAL_LEN_OFFSET = 28
SHARED_BUFFER_BUDGET_TOTAL_LEN_END = 32

SHARED_BUFFER_BUDGET_ENTRY = struct.Struct("<32sIIII")
SHARED_BUFFER_BUDGET_ENTRY_HOLDER_IDENTITY_OFFSET = 0
SHARED_BUFFER_BUDGET_ENTRY_HOLDER_IDENTITY_END = 32
SHARED_BUFFER_BUDGET_ENTRY_BYTE_PAGES_OFFSET = 32
SHARED_BUFFER_BUDGET_ENTRY_BYTE_PAGES_END = 36
SHARED_BUFFER_BUDGET_ENTRY_BUFFER_COUNT_OFFSET = 36
SHARED_BUFFER_BUDGET_ENTRY_BUFFER_COUNT_END = 40
SHARED_BUFFER_BUDGET_ENTRY_MAPPING_COUNT_OFFSET = 40
SHARED_BUFFER_BUDGET_ENTRY_MAPPING_COUNT_END = 44
SHARED_BUFFER_BUDGET_ENTRY_LOAN_COUNT_OFFSET = 44
SHARED_BUFFER_BUDGET_ENTRY_LOAN_COUNT_END = 48

PRIVATE_MEMORY_BUDGET_MAGIC = b"SLIMEPM\0"
PRIVATE_MEMORY_BUDGET_VERSION = 1
PRIVATE_MEMORY_BUDGET_HEADER_BYTES = 32
PRIVATE_MEMORY_BUDGET_ENTRY_BYTES = 36
MAX_PRIVATE_MEMORY_BUDGET_HOLDERS = 32
PRIVATE_MEMORY_ROOT_REGION_PAGES = 512
PRIVATE_MEMORY_ROOT_TOTAL_PAGES = 2048
PRIVATE_MEMORY_BUDGET_HEADER = struct.Struct("<8sIIQII")
PRIVATE_MEMORY_BUDGET_MAGIC_OFFSET = 0
PRIVATE_MEMORY_BUDGET_MAGIC_END = 8
PRIVATE_MEMORY_BUDGET_FORMAT_VERSION_OFFSET = 8
PRIVATE_MEMORY_BUDGET_FORMAT_VERSION_END = 12
PRIVATE_MEMORY_BUDGET_HEADER_SIZE_OFFSET = 12
PRIVATE_MEMORY_BUDGET_HEADER_SIZE_END = 16
PRIVATE_MEMORY_BUDGET_REQUIRED_FLAGS_OFFSET = 16
PRIVATE_MEMORY_BUDGET_REQUIRED_FLAGS_END = 24
PRIVATE_MEMORY_BUDGET_HOLDER_COUNT_OFFSET = 24
PRIVATE_MEMORY_BUDGET_HOLDER_COUNT_END = 28
PRIVATE_MEMORY_BUDGET_TOTAL_LEN_OFFSET = 28
PRIVATE_MEMORY_BUDGET_TOTAL_LEN_END = 32

PRIVATE_MEMORY_BUDGET_ENTRY = struct.Struct("<32sI")
PRIVATE_MEMORY_BUDGET_ENTRY_HOLDER_IDENTITY_OFFSET = 0
PRIVATE_MEMORY_BUDGET_ENTRY_HOLDER_IDENTITY_END = 32
PRIVATE_MEMORY_BUDGET_ENTRY_PAGE_QUOTA_OFFSET = 32
PRIVATE_MEMORY_BUDGET_ENTRY_PAGE_QUOTA_END = 36

CLOCK_AUTHORITY_MAGIC = b"SLIMECA\0"
CLOCK_AUTHORITY_VERSION = 1
CLOCK_AUTHORITY_HEADER_BYTES = 32
CLOCK_AUTHORITY_ENTRY_BYTES = 64
CLOCK_AUTHORITY_MAX_HOLDERS = 48
CLOCK_AUTHORITY_MAX_LIVE_TIMERS_PER_HOLDER = 4
CLOCK_AUTHORITY_MAX_LIVE_TIMERS = 64
CLOCK_AUTHORITY_HEADER = struct.Struct("<8sIIQII")
CLOCK_AUTHORITY_MAGIC_OFFSET = 0
CLOCK_AUTHORITY_MAGIC_END = 8
CLOCK_AUTHORITY_FORMAT_VERSION_OFFSET = 8
CLOCK_AUTHORITY_FORMAT_VERSION_END = 12
CLOCK_AUTHORITY_HEADER_SIZE_OFFSET = 12
CLOCK_AUTHORITY_HEADER_SIZE_END = 16
CLOCK_AUTHORITY_REQUIRED_FLAGS_OFFSET = 16
CLOCK_AUTHORITY_REQUIRED_FLAGS_END = 24
CLOCK_AUTHORITY_HOLDER_COUNT_OFFSET = 24
CLOCK_AUTHORITY_HOLDER_COUNT_END = 28
CLOCK_AUTHORITY_TOTAL_LEN_OFFSET = 28
CLOCK_AUTHORITY_TOTAL_LEN_END = 32

CLOCK_AUTHORITY_ENTRY = struct.Struct("<32sQIIQQ")
CLOCK_AUTHORITY_ENTRY_HOLDER_IDENTITY_OFFSET = 0
CLOCK_AUTHORITY_ENTRY_HOLDER_IDENTITY_END = 32
CLOCK_AUTHORITY_ENTRY_AUTHORITY_FLAGS_OFFSET = 32
CLOCK_AUTHORITY_ENTRY_AUTHORITY_FLAGS_END = 40
CLOCK_AUTHORITY_ENTRY_TIMER_QUOTA_OFFSET = 40
CLOCK_AUTHORITY_ENTRY_TIMER_QUOTA_END = 44
CLOCK_AUTHORITY_ENTRY_RESERVED_OFFSET = 44
CLOCK_AUTHORITY_ENTRY_RESERVED_END = 48
CLOCK_AUTHORITY_ENTRY_NOTIFICATION_GRANT_IDENTITY_OFFSET = 48
CLOCK_AUTHORITY_ENTRY_NOTIFICATION_GRANT_IDENTITY_END = 56
CLOCK_AUTHORITY_ENTRY_NOTIFICATION_BADGE_OFFSET = 56
CLOCK_AUTHORITY_ENTRY_NOTIFICATION_BADGE_END = 64

WAIT_SET_MAGIC = b"SLIMEWS\0"
WAIT_SET_VERSION = 1
WAIT_SET_HEADER_BYTES = 32
WAIT_SET_ENTRY_BYTES = 64
WAIT_SET_MAX_ENTRIES = 48
WAIT_SET_MAX_SOURCES_PER_WAITER = 9
WAIT_SET_MAX_CALLBACKS_PER_WAKE = 9
WAIT_SET_KIND_STREAM = 1
WAIT_SET_KIND_CALL = 2
WAIT_SET_KIND_OPERATION = 3
WAIT_SET_KIND_TIMER = 4
WAIT_SET_KIND_SUPERVISION = 5
WAIT_SET_KIND_QOS_EVENT = 6
WAIT_SET_DRAIN_SLOT_ABSENT = 4294967295
WAIT_SET_HEADER = struct.Struct("<8sIIQII")
WAIT_SET_MAGIC_OFFSET = 0
WAIT_SET_MAGIC_END = 8
WAIT_SET_FORMAT_VERSION_OFFSET = 8
WAIT_SET_FORMAT_VERSION_END = 12
WAIT_SET_HEADER_SIZE_OFFSET = 12
WAIT_SET_HEADER_SIZE_END = 16
WAIT_SET_REQUIRED_FLAGS_OFFSET = 16
WAIT_SET_REQUIRED_FLAGS_END = 24
WAIT_SET_ENTRY_COUNT_OFFSET = 24
WAIT_SET_ENTRY_COUNT_END = 28
WAIT_SET_TOTAL_LEN_OFFSET = 28
WAIT_SET_TOTAL_LEN_END = 32

WAIT_SET_ENTRY = struct.Struct("<32sQQIIQ")
WAIT_SET_ENTRY_WAITER_IDENTITY_OFFSET = 0
WAIT_SET_ENTRY_WAITER_IDENTITY_END = 32
WAIT_SET_ENTRY_BADGE_OFFSET = 32
WAIT_SET_ENTRY_BADGE_END = 40
WAIT_SET_ENTRY_NOTIFICATION_GRANT_IDENTITY_OFFSET = 40
WAIT_SET_ENTRY_NOTIFICATION_GRANT_IDENTITY_END = 48
WAIT_SET_ENTRY_SOURCE_KIND_OFFSET = 48
WAIT_SET_ENTRY_SOURCE_KIND_END = 52
WAIT_SET_ENTRY_DRAIN_SLOT_OFFSET = 52
WAIT_SET_ENTRY_DRAIN_SLOT_END = 56
WAIT_SET_ENTRY_RESERVED_OFFSET = 56
WAIT_SET_ENTRY_RESERVED_END = 64

SCHEDULING_CLASS_MAGIC = b"SLIMESC\0"
SCHEDULING_CLASS_VERSION = 1
SCHEDULING_CLASS_HEADER_BYTES = 32
SCHEDULING_CLASS_BAND_BYTES = 16
SCHEDULING_CLASS_ENTRY_BYTES = 48
SCHEDULING_PROMOTION_ENTRY_BYTES = 72
SCHEDULING_CLASS_MAX_CLASSES = 3
SCHEDULING_CLASS_MAX_INSTANCES = 48
SCHEDULING_CLASS_MAX_PROMOTIONS = 32
SCHEDULING_CLASS_UNDECLARED_ID = 0
SCHEDULING_CLASS_FOREGROUND = 1
SCHEDULING_CLASS_NORMAL = 2
SCHEDULING_CLASS_BEST_EFFORT = 3
SCHEDULING_CLASS_ID_BY_MANIFEST_NAME = {
    "foreground": 1,
    "normal": 2,
    "bestEffort": 3,
}
SCHEDULING_CLASS_HEADER = struct.Struct("<8sIIQHHHH")
SCHEDULING_CLASS_MAGIC_OFFSET = 0
SCHEDULING_CLASS_MAGIC_END = 8
SCHEDULING_CLASS_FORMAT_VERSION_OFFSET = 8
SCHEDULING_CLASS_FORMAT_VERSION_END = 12
SCHEDULING_CLASS_HEADER_SIZE_OFFSET = 12
SCHEDULING_CLASS_HEADER_SIZE_END = 16
SCHEDULING_CLASS_REQUIRED_FLAGS_OFFSET = 16
SCHEDULING_CLASS_REQUIRED_FLAGS_END = 24
SCHEDULING_CLASS_CLASS_COUNT_OFFSET = 24
SCHEDULING_CLASS_CLASS_COUNT_END = 26
SCHEDULING_CLASS_INSTANCE_COUNT_OFFSET = 26
SCHEDULING_CLASS_INSTANCE_COUNT_END = 28
SCHEDULING_CLASS_PROMOTION_COUNT_OFFSET = 28
SCHEDULING_CLASS_PROMOTION_COUNT_END = 30
SCHEDULING_CLASS_TOTAL_LEN_OFFSET = 30
SCHEDULING_CLASS_TOTAL_LEN_END = 32

SCHEDULING_CLASS_BAND = struct.Struct("<IIQ")
SCHEDULING_CLASS_BAND_CLASS_ID_OFFSET = 0
SCHEDULING_CLASS_BAND_CLASS_ID_END = 4
SCHEDULING_CLASS_BAND_PRIORITY_OFFSET = 4
SCHEDULING_CLASS_BAND_PRIORITY_END = 8
SCHEDULING_CLASS_BAND_RESERVED_OFFSET = 8
SCHEDULING_CLASS_BAND_RESERVED_END = 16

SCHEDULING_CLASS_ENTRY = struct.Struct("<32sIIQ")
SCHEDULING_CLASS_ENTRY_SUBJECT_IDENTITY_OFFSET = 0
SCHEDULING_CLASS_ENTRY_SUBJECT_IDENTITY_END = 32
SCHEDULING_CLASS_ENTRY_CLASS_ID_OFFSET = 32
SCHEDULING_CLASS_ENTRY_CLASS_ID_END = 36
SCHEDULING_CLASS_ENTRY_WORKER_CLASS_ID_OFFSET = 36
SCHEDULING_CLASS_ENTRY_WORKER_CLASS_ID_END = 40
SCHEDULING_CLASS_ENTRY_RESERVED_OFFSET = 40
SCHEDULING_CLASS_ENTRY_RESERVED_END = 48

SCHEDULING_PROMOTION_ENTRY = struct.Struct("<32s32sII")
SCHEDULING_PROMOTION_ENTRY_HOLDER_IDENTITY_OFFSET = 0
SCHEDULING_PROMOTION_ENTRY_HOLDER_IDENTITY_END = 32
SCHEDULING_PROMOTION_ENTRY_SUBJECT_IDENTITY_OFFSET = 32
SCHEDULING_PROMOTION_ENTRY_SUBJECT_IDENTITY_END = 64
SCHEDULING_PROMOTION_ENTRY_CEILING_PRIORITY_OFFSET = 64
SCHEDULING_PROMOTION_ENTRY_CEILING_PRIORITY_END = 68
SCHEDULING_PROMOTION_ENTRY_RESERVED_OFFSET = 68
SCHEDULING_PROMOTION_ENTRY_RESERVED_END = 72

LIFECYCLE_POLICY_MAGIC = b"SLIMELC\0"
LIFECYCLE_POLICY_VERSION = 1
LIFECYCLE_POLICY_HEADER_BYTES = 40
LIFECYCLE_TRANSITION_BYTES = 16
LIFECYCLE_RESTART_BYTES = 64
LIFECYCLE_DEPENDENCY_BYTES = 72
LIFECYCLE_PARAMETER_GRANT_BYTES = 72
LIFECYCLE_POLICY_MAX_TRANSITIONS = 48
LIFECYCLE_POLICY_MAX_INSTANCES = 48
LIFECYCLE_POLICY_MAX_DEPENDENCIES = 32
LIFECYCLE_POLICY_MAX_PARAMETER_GRANTS = 48
LIFECYCLE_POLICY_MAX_RESTART_ATTEMPTS = 16
LIFECYCLE_POLICY_MAX_BACKOFF_NS = 60000000000
LIFECYCLE_POLICY_BACKOFF_FACTOR_SCALE = 256
LIFECYCLE_POLICY_MAX_BACKOFF_FACTOR = 4096
LIFECYCLE_POLICY_UNDECLARED_STATE_ID = 0
LIFECYCLE_POLICY_UNDECLARED_CAUSE_ID = 0
LIFECYCLE_PARAMETER_READ = 1
LIFECYCLE_PARAMETER_WRITE = 2
LIFECYCLE_STATE_INITIALIZE = 1
LIFECYCLE_STATE_CONFIGURE = 2
LIFECYCLE_STATE_START = 3
LIFECYCLE_STATE_READY = 4
LIFECYCLE_STATE_RUNNING = 5
LIFECYCLE_STATE_DEGRADED = 6
LIFECYCLE_STATE_STOP = 7
LIFECYCLE_STATE_ERROR = 8
LIFECYCLE_CAUSE_EXIT = 1
LIFECYCLE_CAUSE_FAULT = 2
LIFECYCLE_CAUSE_UNHEALTHY = 3
LIFECYCLE_STATE_ID_BY_MANIFEST_NAME = {
    "Initialize": 1,
    "Configure": 2,
    "Start": 3,
    "Ready": 4,
    "Running": 5,
    "Degraded": 6,
    "Stop": 7,
    "Error": 8,
}
LIFECYCLE_CAUSE_ID_BY_MANIFEST_NAME = {
    "exit": 1,
    "fault": 2,
    "unhealthy": 3,
}
LIFECYCLE_POLICY_HEADER = struct.Struct("<8sIIQHHHHHHI")
LIFECYCLE_POLICY_MAGIC_OFFSET = 0
LIFECYCLE_POLICY_MAGIC_END = 8
LIFECYCLE_POLICY_FORMAT_VERSION_OFFSET = 8
LIFECYCLE_POLICY_FORMAT_VERSION_END = 12
LIFECYCLE_POLICY_HEADER_SIZE_OFFSET = 12
LIFECYCLE_POLICY_HEADER_SIZE_END = 16
LIFECYCLE_POLICY_REQUIRED_FLAGS_OFFSET = 16
LIFECYCLE_POLICY_REQUIRED_FLAGS_END = 24
LIFECYCLE_POLICY_INITIAL_STATE_OFFSET = 24
LIFECYCLE_POLICY_INITIAL_STATE_END = 26
LIFECYCLE_POLICY_TERMINAL_STATE_OFFSET = 26
LIFECYCLE_POLICY_TERMINAL_STATE_END = 28
LIFECYCLE_POLICY_TRANSITION_COUNT_OFFSET = 28
LIFECYCLE_POLICY_TRANSITION_COUNT_END = 30
LIFECYCLE_POLICY_RESTART_COUNT_OFFSET = 30
LIFECYCLE_POLICY_RESTART_COUNT_END = 32
LIFECYCLE_POLICY_DEPENDENCY_COUNT_OFFSET = 32
LIFECYCLE_POLICY_DEPENDENCY_COUNT_END = 34
LIFECYCLE_POLICY_PARAMETER_COUNT_OFFSET = 34
LIFECYCLE_POLICY_PARAMETER_COUNT_END = 36
LIFECYCLE_POLICY_TOTAL_LEN_OFFSET = 36
LIFECYCLE_POLICY_TOTAL_LEN_END = 40

LIFECYCLE_TRANSITION = struct.Struct("<IIQ")
LIFECYCLE_TRANSITION_FROM_STATE_OFFSET = 0
LIFECYCLE_TRANSITION_FROM_STATE_END = 4
LIFECYCLE_TRANSITION_TO_STATE_OFFSET = 4
LIFECYCLE_TRANSITION_TO_STATE_END = 8
LIFECYCLE_TRANSITION_RESERVED_OFFSET = 8
LIFECYCLE_TRANSITION_RESERVED_END = 16

LIFECYCLE_RESTART = struct.Struct("<32sIIQI12s")
LIFECYCLE_RESTART_SUBJECT_IDENTITY_OFFSET = 0
LIFECYCLE_RESTART_SUBJECT_IDENTITY_END = 32
LIFECYCLE_RESTART_ATTEMPTS_OFFSET = 32
LIFECYCLE_RESTART_ATTEMPTS_END = 36
LIFECYCLE_RESTART_CAUSES_OFFSET = 36
LIFECYCLE_RESTART_CAUSES_END = 40
LIFECYCLE_RESTART_BACKOFF_NS_OFFSET = 40
LIFECYCLE_RESTART_BACKOFF_NS_END = 48
LIFECYCLE_RESTART_BACKOFF_FACTOR_OFFSET = 48
LIFECYCLE_RESTART_BACKOFF_FACTOR_END = 52
LIFECYCLE_RESTART_RESERVED_OFFSET = 52
LIFECYCLE_RESTART_RESERVED_END = 64

LIFECYCLE_DEPENDENCY = struct.Struct("<32s32sII")
LIFECYCLE_DEPENDENCY_SUBJECT_IDENTITY_OFFSET = 0
LIFECYCLE_DEPENDENCY_SUBJECT_IDENTITY_END = 32
LIFECYCLE_DEPENDENCY_DEPENDENCY_IDENTITY_OFFSET = 32
LIFECYCLE_DEPENDENCY_DEPENDENCY_IDENTITY_END = 64
LIFECYCLE_DEPENDENCY_REQUIRED_STATE_OFFSET = 64
LIFECYCLE_DEPENDENCY_REQUIRED_STATE_END = 68
LIFECYCLE_DEPENDENCY_RESERVED_OFFSET = 68
LIFECYCLE_DEPENDENCY_RESERVED_END = 72

LIFECYCLE_PARAMETER_GRANT = struct.Struct("<32s32sII")
LIFECYCLE_PARAMETER_GRANT_HOLDER_IDENTITY_OFFSET = 0
LIFECYCLE_PARAMETER_GRANT_HOLDER_IDENTITY_END = 32
LIFECYCLE_PARAMETER_GRANT_SUBJECT_IDENTITY_OFFSET = 32
LIFECYCLE_PARAMETER_GRANT_SUBJECT_IDENTITY_END = 64
LIFECYCLE_PARAMETER_GRANT_AUTHORITY_FLAGS_OFFSET = 64
LIFECYCLE_PARAMETER_GRANT_AUTHORITY_FLAGS_END = 68
LIFECYCLE_PARAMETER_GRANT_RESERVED_OFFSET = 68
LIFECYCLE_PARAMETER_GRANT_RESERVED_END = 72

RECORDING_POLICY_MAGIC = b"SLIMERC\0"
RECORDING_POLICY_VERSION = 1
RECORDING_POLICY_HEADER_BYTES = 32
RECORDING_POLICY_ENTRY_BYTES = 64
RECORDING_POLICY_MAX_INSTANCES = 48
RECORDING_POLICY_RECORD_BYTES = 64
RECORDING_POLICY_MAX_RECORD_CAPACITY = 64
RECORDING_POLICY_ROLE_RECORD = 1
RECORDING_POLICY_ROLE_REPLAY = 2
RECORDING_POLICY_MAX_ROLE = 2
RECORDING_POLICY_FLAG_DETERMINISTIC = 1
RECORDING_POLICY_KNOWN_FLAGS = 1
RECORDING_POLICY_ROLE_BY_MANIFEST_NAME = {
    "record": 1,
    "replay": 2,
}
RECORDING_POLICY_HEADER = struct.Struct("<8sIIQII")
RECORDING_POLICY_MAGIC_OFFSET = 0
RECORDING_POLICY_MAGIC_END = 8
RECORDING_POLICY_FORMAT_VERSION_OFFSET = 8
RECORDING_POLICY_FORMAT_VERSION_END = 12
RECORDING_POLICY_HEADER_SIZE_OFFSET = 12
RECORDING_POLICY_HEADER_SIZE_END = 16
RECORDING_POLICY_REQUIRED_FLAGS_OFFSET = 16
RECORDING_POLICY_REQUIRED_FLAGS_END = 24
RECORDING_POLICY_ENTRY_COUNT_OFFSET = 24
RECORDING_POLICY_ENTRY_COUNT_END = 28
RECORDING_POLICY_TOTAL_LEN_OFFSET = 28
RECORDING_POLICY_TOTAL_LEN_END = 32

RECORDING_POLICY_ENTRY = struct.Struct("<32sQQIII4s")
RECORDING_POLICY_ENTRY_INSTANCE_IDENTITY_OFFSET = 0
RECORDING_POLICY_ENTRY_INSTANCE_IDENTITY_END = 32
RECORDING_POLICY_ENTRY_STREAM_IDENTITY_OFFSET = 32
RECORDING_POLICY_ENTRY_STREAM_IDENTITY_END = 40
RECORDING_POLICY_ENTRY_STREAM_GRANT_IDENTITY_OFFSET = 40
RECORDING_POLICY_ENTRY_STREAM_GRANT_IDENTITY_END = 48
RECORDING_POLICY_ENTRY_ROLE_OFFSET = 48
RECORDING_POLICY_ENTRY_ROLE_END = 52
RECORDING_POLICY_ENTRY_ENTRY_FLAGS_OFFSET = 52
RECORDING_POLICY_ENTRY_ENTRY_FLAGS_END = 56
RECORDING_POLICY_ENTRY_RECORD_CAPACITY_OFFSET = 56
RECORDING_POLICY_ENTRY_RECORD_CAPACITY_END = 60
RECORDING_POLICY_ENTRY_RESERVED_OFFSET = 60
RECORDING_POLICY_ENTRY_RESERVED_END = 64

FABRIC_GRAPH_MAGIC = b"SLIMEFG\0"
FABRIC_GRAPH_VERSION = 3
FABRIC_GRAPH_HEADER_BYTES = 164
FABRIC_GRAPH_SCHEMA_ENTRY_BYTES = 48
FABRIC_GRAPH_ROUTE_ENTRY_BYTES = 48
FABRIC_GRAPH_PARTICIPANT_ENTRY_BYTES = 128
FABRIC_GRAPH_INTERPOSITION_ENTRY_BYTES = 40
MAX_FABRIC_GRAPH_SCHEMAS = 64
MAX_FABRIC_GRAPH_ROUTES = 32
MAX_FABRIC_GRAPH_PARTICIPANTS = 32
MAX_FABRIC_GRAPH_INTERPOSITION_HOPS = 16
MAX_FABRIC_GRAPH_INGRESS_SOURCES = 9
FABRIC_GRAPH_LIMIT_SAMPLE_BYTES = 1048576
FABRIC_GRAPH_LIMIT_QUEUE_DEPTH = 64
FABRIC_GRAPH_LIMIT_HISTORY_DEPTH = 64
FABRIC_GRAPH_LIMIT_EVENT_DEPTH = 64
FABRIC_GRAPH_LIMIT_RETAINED_SAMPLES = 64
FABRIC_GRAPH_LIMIT_RETRIES = 16
FABRIC_GRAPH_LIMIT_IN_FLIGHT = 32
FABRIC_GRAPH_LIMIT_BUFFERS = 32
FABRIC_GRAPH_LIMIT_CAPABILITY_SLOTS = 64
FABRIC_GRAPH_LIMIT_TRACE_DEPTH = 64
FABRIC_GRAPH_TRACE_TERMINAL_RESERVE = 2
FABRIC_GRAPH_TRACE_OVERFLOW_SATURATE = 1
FABRIC_GRAPH_FRAME_CAPACITY = 32
FABRIC_GRAPH_CONTROL_MESSAGE_BYTES = 64
MAX_FABRIC_GRAPH_ROLE_PARTICIPANTS = 4
FABRIC_GRAPH_CHANNEL_QUEUE_DEPTH = 16
FABRIC_GRAPH_KERNEL_TOTAL_PAGES = 256
FABRIC_GRAPH_KERNEL_SHARED_BUFFERS = 32
FABRIC_GRAPH_KERNEL_MAPPINGS = 64
FABRIC_GRAPH_KERNEL_LOANS = 64
FABRIC_GRAPH_INTERPOSITION_NONE = 4294967295
FABRIC_CONTRACT_KIND_STREAM = 1
FABRIC_CONTRACT_KIND_CALL = 2
FABRIC_CONTRACT_KIND_OPERATION = 3
FABRIC_DIRECTION_PUBLISH = 1
FABRIC_DIRECTION_SUBSCRIBE = 2
FABRIC_DIRECTION_CLIENT = 3
FABRIC_DIRECTION_SERVER = 4
FABRIC_VISIBILITY_PRIVATE = 1
FABRIC_VISIBILITY_GRAPH = 2
FABRIC_RELIABILITY_BEST_EFFORT = 1
FABRIC_RELIABILITY_RELIABLE = 2
FABRIC_DURABILITY_VOLATILE = 1
FABRIC_DURABILITY_RETAINED = 2
FABRIC_LIVELINESS_AUTOMATIC = 1
FABRIC_LIVELINESS_MANUAL = 2
FABRIC_ROUTE_DOMAIN = "slime-fabric-route-v1:".encode("utf-8")
FABRIC_GRANT_DOMAIN = "slime-fabric-grant-v1:".encode("utf-8")
FABRIC_COMPONENT_DOMAIN = "slime-fabric-component-v1:".encode("utf-8")
FABRIC_GRAPH_QUERY_SCHEMA_COUNT = 1
FABRIC_GRAPH_QUERY_ROUTE_COUNT = 2
FABRIC_GRAPH_QUERY_PARTICIPANT_COUNT = 3
FABRIC_GRAPH_QUERY_INTERPOSITION_COUNT = 4
FABRIC_GRAPH_QUERY_MAX_ROUTES = 5
FABRIC_GRAPH_QUERY_MAX_INGRESS_SOURCES = 6
FABRIC_GRAPH_QUERY_MAX_PUBLISHERS = 7
FABRIC_GRAPH_QUERY_MAX_SUBSCRIBERS = 8
FABRIC_GRAPH_QUERY_MAX_CLIENTS = 9
FABRIC_GRAPH_QUERY_MAX_SERVERS = 10
FABRIC_GRAPH_QUERY_MAX_SAMPLE_BYTES = 11
FABRIC_GRAPH_QUERY_MAX_QUEUE_DEPTH = 12
FABRIC_GRAPH_QUERY_MAX_HISTORY_DEPTH = 13
FABRIC_GRAPH_QUERY_MAX_EVENT_DEPTH = 14
FABRIC_GRAPH_QUERY_MAX_RETAINED_SAMPLES = 15
FABRIC_GRAPH_QUERY_MAX_RETRIES = 16
FABRIC_GRAPH_QUERY_MAX_IN_FLIGHT_CALLS = 17
FABRIC_GRAPH_QUERY_MAX_IN_FLIGHT_OPERATIONS = 18
FABRIC_GRAPH_QUERY_MAX_BUFFER_PAGES = 19
FABRIC_GRAPH_QUERY_MAX_BUFFERS = 20
FABRIC_GRAPH_QUERY_MAX_MAPPINGS = 21
FABRIC_GRAPH_QUERY_MAX_LOANS = 22
FABRIC_GRAPH_QUERY_MAX_CAPABILITY_SLOTS = 23
FABRIC_GRAPH_QUERY_TRACE_DEPTH = 24
FABRIC_GRAPH_QUERY_TRACE_OVERFLOW = 25
FABRIC_GRAPH_HEADER = struct.Struct("<8sIIQIIIIII32sIIIIIIIIIIIIIIIIIIIII")
FABRIC_GRAPH_HEADER_MAGIC_OFFSET = 0
FABRIC_GRAPH_HEADER_MAGIC_END = 8
FABRIC_GRAPH_HEADER_FORMAT_VERSION_OFFSET = 8
FABRIC_GRAPH_HEADER_FORMAT_VERSION_END = 12
FABRIC_GRAPH_HEADER_HEADER_SIZE_OFFSET = 12
FABRIC_GRAPH_HEADER_HEADER_SIZE_END = 16
FABRIC_GRAPH_HEADER_REQUIRED_FLAGS_OFFSET = 16
FABRIC_GRAPH_HEADER_REQUIRED_FLAGS_END = 24
FABRIC_GRAPH_HEADER_TOTAL_LEN_OFFSET = 24
FABRIC_GRAPH_HEADER_TOTAL_LEN_END = 28
FABRIC_GRAPH_HEADER_SCHEMA_COUNT_OFFSET = 28
FABRIC_GRAPH_HEADER_SCHEMA_COUNT_END = 32
FABRIC_GRAPH_HEADER_ROUTE_COUNT_OFFSET = 32
FABRIC_GRAPH_HEADER_ROUTE_COUNT_END = 36
FABRIC_GRAPH_HEADER_PARTICIPANT_COUNT_OFFSET = 36
FABRIC_GRAPH_HEADER_PARTICIPANT_COUNT_END = 40
FABRIC_GRAPH_HEADER_INTERPOSITION_COUNT_OFFSET = 40
FABRIC_GRAPH_HEADER_INTERPOSITION_COUNT_END = 44
FABRIC_GRAPH_HEADER_RESERVED_OFFSET = 44
FABRIC_GRAPH_HEADER_RESERVED_END = 48
FABRIC_GRAPH_HEADER_FABRIC_COMPONENT_IDENTITY_OFFSET = 48
FABRIC_GRAPH_HEADER_FABRIC_COMPONENT_IDENTITY_END = 80
FABRIC_GRAPH_HEADER_MAX_ROUTES_OFFSET = 80
FABRIC_GRAPH_HEADER_MAX_ROUTES_END = 84
FABRIC_GRAPH_HEADER_MAX_INGRESS_SOURCES_OFFSET = 84
FABRIC_GRAPH_HEADER_MAX_INGRESS_SOURCES_END = 88
FABRIC_GRAPH_HEADER_MAX_PUBLISHERS_OFFSET = 88
FABRIC_GRAPH_HEADER_MAX_PUBLISHERS_END = 92
FABRIC_GRAPH_HEADER_MAX_SUBSCRIBERS_OFFSET = 92
FABRIC_GRAPH_HEADER_MAX_SUBSCRIBERS_END = 96
FABRIC_GRAPH_HEADER_MAX_CLIENTS_OFFSET = 96
FABRIC_GRAPH_HEADER_MAX_CLIENTS_END = 100
FABRIC_GRAPH_HEADER_MAX_SERVERS_OFFSET = 100
FABRIC_GRAPH_HEADER_MAX_SERVERS_END = 104
FABRIC_GRAPH_HEADER_MAX_SAMPLE_BYTES_OFFSET = 104
FABRIC_GRAPH_HEADER_MAX_SAMPLE_BYTES_END = 108
FABRIC_GRAPH_HEADER_MAX_QUEUE_DEPTH_OFFSET = 108
FABRIC_GRAPH_HEADER_MAX_QUEUE_DEPTH_END = 112
FABRIC_GRAPH_HEADER_MAX_HISTORY_DEPTH_OFFSET = 112
FABRIC_GRAPH_HEADER_MAX_HISTORY_DEPTH_END = 116
FABRIC_GRAPH_HEADER_MAX_EVENT_DEPTH_OFFSET = 116
FABRIC_GRAPH_HEADER_MAX_EVENT_DEPTH_END = 120
FABRIC_GRAPH_HEADER_MAX_RETAINED_SAMPLES_OFFSET = 120
FABRIC_GRAPH_HEADER_MAX_RETAINED_SAMPLES_END = 124
FABRIC_GRAPH_HEADER_MAX_RETRIES_OFFSET = 124
FABRIC_GRAPH_HEADER_MAX_RETRIES_END = 128
FABRIC_GRAPH_HEADER_MAX_IN_FLIGHT_CALLS_OFFSET = 128
FABRIC_GRAPH_HEADER_MAX_IN_FLIGHT_CALLS_END = 132
FABRIC_GRAPH_HEADER_MAX_IN_FLIGHT_OPERATIONS_OFFSET = 132
FABRIC_GRAPH_HEADER_MAX_IN_FLIGHT_OPERATIONS_END = 136
FABRIC_GRAPH_HEADER_MAX_BUFFER_PAGES_OFFSET = 136
FABRIC_GRAPH_HEADER_MAX_BUFFER_PAGES_END = 140
FABRIC_GRAPH_HEADER_MAX_BUFFERS_OFFSET = 140
FABRIC_GRAPH_HEADER_MAX_BUFFERS_END = 144
FABRIC_GRAPH_HEADER_MAX_MAPPINGS_OFFSET = 144
FABRIC_GRAPH_HEADER_MAX_MAPPINGS_END = 148
FABRIC_GRAPH_HEADER_MAX_LOANS_OFFSET = 148
FABRIC_GRAPH_HEADER_MAX_LOANS_END = 152
FABRIC_GRAPH_HEADER_MAX_CAPABILITY_SLOTS_OFFSET = 152
FABRIC_GRAPH_HEADER_MAX_CAPABILITY_SLOTS_END = 156
FABRIC_GRAPH_HEADER_TRACE_DEPTH_OFFSET = 156
FABRIC_GRAPH_HEADER_TRACE_DEPTH_END = 160
FABRIC_GRAPH_HEADER_TRACE_OVERFLOW_OFFSET = 160
FABRIC_GRAPH_HEADER_TRACE_OVERFLOW_END = 164

FABRIC_GRAPH_SCHEMA_ENTRY = struct.Struct("<32sQII")
FABRIC_GRAPH_SCHEMA_ENTRY_IDENTITY_OFFSET = 0
FABRIC_GRAPH_SCHEMA_ENTRY_IDENTITY_END = 32
FABRIC_GRAPH_SCHEMA_ENTRY_TYPE_TAG_OFFSET = 32
FABRIC_GRAPH_SCHEMA_ENTRY_TYPE_TAG_END = 40
FABRIC_GRAPH_SCHEMA_ENTRY_CONTRACT_KIND_OFFSET = 40
FABRIC_GRAPH_SCHEMA_ENTRY_CONTRACT_KIND_END = 44
FABRIC_GRAPH_SCHEMA_ENTRY_MAX_ENCODED_BYTES_OFFSET = 44
FABRIC_GRAPH_SCHEMA_ENTRY_MAX_ENCODED_BYTES_END = 48

FABRIC_GRAPH_ROUTE_ENTRY = struct.Struct("<32sIIII")
FABRIC_GRAPH_ROUTE_ENTRY_ROUTE_IDENTITY_OFFSET = 0
FABRIC_GRAPH_ROUTE_ENTRY_ROUTE_IDENTITY_END = 32
FABRIC_GRAPH_ROUTE_ENTRY_SCHEMA_INDEX_OFFSET = 32
FABRIC_GRAPH_ROUTE_ENTRY_SCHEMA_INDEX_END = 36
FABRIC_GRAPH_ROUTE_ENTRY_CONTRACT_KIND_OFFSET = 36
FABRIC_GRAPH_ROUTE_ENTRY_CONTRACT_KIND_END = 40
FABRIC_GRAPH_ROUTE_ENTRY_PARTICIPANT_COUNT_OFFSET = 40
FABRIC_GRAPH_ROUTE_ENTRY_PARTICIPANT_COUNT_END = 44
FABRIC_GRAPH_ROUTE_ENTRY_RESERVED_OFFSET = 44
FABRIC_GRAPH_ROUTE_ENTRY_RESERVED_END = 48

FABRIC_GRAPH_PARTICIPANT_ENTRY = struct.Struct("<32s32sIIIIQQQIIBBBB12x")
FABRIC_GRAPH_PARTICIPANT_ENTRY_GRANT_IDENTITY_OFFSET = 0
FABRIC_GRAPH_PARTICIPANT_ENTRY_GRANT_IDENTITY_END = 32
FABRIC_GRAPH_PARTICIPANT_ENTRY_COMPONENT_IDENTITY_OFFSET = 32
FABRIC_GRAPH_PARTICIPANT_ENTRY_COMPONENT_IDENTITY_END = 64
FABRIC_GRAPH_PARTICIPANT_ENTRY_ROUTE_INDEX_OFFSET = 64
FABRIC_GRAPH_PARTICIPANT_ENTRY_ROUTE_INDEX_END = 68
FABRIC_GRAPH_PARTICIPANT_ENTRY_DIRECTION_OFFSET = 68
FABRIC_GRAPH_PARTICIPANT_ENTRY_DIRECTION_END = 72
FABRIC_GRAPH_PARTICIPANT_ENTRY_VISIBILITY_OFFSET = 72
FABRIC_GRAPH_PARTICIPANT_ENTRY_VISIBILITY_END = 76
FABRIC_GRAPH_PARTICIPANT_ENTRY_INTERPOSITION_HEAD_OFFSET = 76
FABRIC_GRAPH_PARTICIPANT_ENTRY_INTERPOSITION_HEAD_END = 80
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_DEADLINE_NS_OFFSET = 80
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_DEADLINE_NS_END = 88
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_LIFESPAN_NS_OFFSET = 88
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_LIFESPAN_NS_END = 96
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_LEASE_NS_OFFSET = 96
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_LEASE_NS_END = 104
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_HISTORY_DEPTH_OFFSET = 104
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_HISTORY_DEPTH_END = 108
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_RETAINED_DEPTH_OFFSET = 108
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_RETAINED_DEPTH_END = 112
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_RELIABILITY_OFFSET = 112
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_RELIABILITY_END = 113
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_DURABILITY_OFFSET = 113
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_DURABILITY_END = 114
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_LIVELINESS_OFFSET = 114
FABRIC_GRAPH_PARTICIPANT_ENTRY_QOS_LIVELINESS_END = 115
FABRIC_GRAPH_PARTICIPANT_ENTRY_RESERVED_OFFSET = 115
FABRIC_GRAPH_PARTICIPANT_ENTRY_RESERVED_END = 116

FABRIC_GRAPH_INTERPOSITION_ENTRY = struct.Struct("<32sII")
FABRIC_GRAPH_INTERPOSITION_ENTRY_COMPONENT_IDENTITY_OFFSET = 0
FABRIC_GRAPH_INTERPOSITION_ENTRY_COMPONENT_IDENTITY_END = 32
FABRIC_GRAPH_INTERPOSITION_ENTRY_NEXT_HOP_OFFSET = 32
FABRIC_GRAPH_INTERPOSITION_ENTRY_NEXT_HOP_END = 36
FABRIC_GRAPH_INTERPOSITION_ENTRY_RESERVED_OFFSET = 36
FABRIC_GRAPH_INTERPOSITION_ENTRY_RESERVED_END = 40

BOOT_LAYOUT_MAGIC = b"SLIMEBL\0"
BOOT_LAYOUT_VERSION = 1
BOOT_LAYOUT_HEADER_BYTES = 40
BOOT_LAYOUT_ENTRY_BYTES = 48
MAX_BOOT_LAYOUT_ENTRIES = 64
BOOT_LAYOUT_ROLE_ENDPOINT_FACTORY = 1
BOOT_LAYOUT_ROLE_SHARED_BUFFER_FACTORY = 2
BOOT_LAYOUT_ROLE_EXECUTABLE = 3
BOOT_LAYOUT_ROLE_ENDPOINT_CLIENT = 4
BOOT_LAYOUT_ROLE_ENDPOINT_SERVICE = 5
BOOT_LAYOUT_ROLE_OBJECT_STORE = 6
BOOT_LAYOUT_ROLE_DIRECTORY_ROOT = 7
BOOT_LAYOUT_ROLE_INPUT = 8
BOOT_LAYOUT_ROLE_GENERATION_CONTROL = 9
BOOT_LAYOUT_ROLE_STORAGE_CAPABILITY = 10
BOOT_LAYOUT_ROLE_TRANSFER_RECEIVER = 11
BOOT_LAYOUT_ROLE_TRANSFER_SOURCE = 12
BOOT_LAYOUT_COMPONENT_DOMAIN = b"slime-boot-layout-component-v1:"
BOOT_LAYOUT_CHANNEL_DOMAIN = b"slime-boot-layout-channel-v1:"
BOOT_LAYOUT_HEADER = struct.Struct("<8sIIQQII")
BOOT_LAYOUT_MAGIC_OFFSET = 0
BOOT_LAYOUT_MAGIC_END = 8
BOOT_LAYOUT_FORMAT_VERSION_OFFSET = 8
BOOT_LAYOUT_FORMAT_VERSION_END = 12
BOOT_LAYOUT_HEADER_SIZE_OFFSET = 12
BOOT_LAYOUT_HEADER_SIZE_END = 16
BOOT_LAYOUT_REQUIRED_FLAGS_OFFSET = 16
BOOT_LAYOUT_REQUIRED_FLAGS_END = 24
BOOT_LAYOUT_GENERATION_NUMBER_OFFSET = 24
BOOT_LAYOUT_GENERATION_NUMBER_END = 32
BOOT_LAYOUT_ENTRY_COUNT_OFFSET = 32
BOOT_LAYOUT_ENTRY_COUNT_END = 36
BOOT_LAYOUT_TOTAL_LEN_OFFSET = 36
BOOT_LAYOUT_TOTAL_LEN_END = 40

BOOT_LAYOUT_ENTRY = struct.Struct("<32sIIQ")
BOOT_LAYOUT_ENTRY_NAME_IDENTITY_OFFSET = 0
BOOT_LAYOUT_ENTRY_NAME_IDENTITY_END = 32
BOOT_LAYOUT_ENTRY_SLOT_OFFSET = 32
BOOT_LAYOUT_ENTRY_SLOT_END = 36
BOOT_LAYOUT_ENTRY_ROLE_OFFSET = 36
BOOT_LAYOUT_ENTRY_ROLE_END = 40
BOOT_LAYOUT_ENTRY_RIGHTS_OFFSET = 40
BOOT_LAYOUT_ENTRY_RIGHTS_END = 48

NORMALIZED_SCHEMAS_MAGIC = b"SLIMENS\0"
NORMALIZED_SCHEMAS_VERSION = 1
NORMALIZED_SCHEMAS_HEADER_BYTES = 32
NORMALIZED_SCHEMAS_ENTRY_BYTES = 40
MAX_NORMALIZED_SCHEMAS = 64
MAX_NORMALIZED_SCHEMAS_ARTIFACT_BYTES = 4194304
NORMALIZED_SCHEMAS_HEADER = struct.Struct("<8sIIQII")
NORMALIZED_SCHEMAS_HEADER_MAGIC_OFFSET = 0
NORMALIZED_SCHEMAS_HEADER_MAGIC_END = 8
NORMALIZED_SCHEMAS_HEADER_FORMAT_VERSION_OFFSET = 8
NORMALIZED_SCHEMAS_HEADER_FORMAT_VERSION_END = 12
NORMALIZED_SCHEMAS_HEADER_HEADER_SIZE_OFFSET = 12
NORMALIZED_SCHEMAS_HEADER_HEADER_SIZE_END = 16
NORMALIZED_SCHEMAS_HEADER_REQUIRED_FLAGS_OFFSET = 16
NORMALIZED_SCHEMAS_HEADER_REQUIRED_FLAGS_END = 24
NORMALIZED_SCHEMAS_HEADER_SCHEMA_COUNT_OFFSET = 24
NORMALIZED_SCHEMAS_HEADER_SCHEMA_COUNT_END = 28
NORMALIZED_SCHEMAS_HEADER_TOTAL_LEN_OFFSET = 28
NORMALIZED_SCHEMAS_HEADER_TOTAL_LEN_END = 32

NORMALIZED_SCHEMAS_ENTRY = struct.Struct("<32sII")
NORMALIZED_SCHEMAS_ENTRY_IDENTITY_OFFSET = 0
NORMALIZED_SCHEMAS_ENTRY_IDENTITY_END = 32
NORMALIZED_SCHEMAS_ENTRY_NORMALIZED_LEN_OFFSET = 32
NORMALIZED_SCHEMAS_ENTRY_NORMALIZED_LEN_END = 36
NORMALIZED_SCHEMAS_ENTRY_RESERVED_OFFSET = 36
NORMALIZED_SCHEMAS_ENTRY_RESERVED_END = 40

def sha256(data: bytes) -> bytes:
    return hashlib.sha256(data).digest()


def generation_identity(data: bytes) -> bytes:
    return sha256(
        data[:GENERATION_HEADER_IDENTITY_OFFSET]
        + bytes(GENERATION_HEADER_IDENTITY_END - GENERATION_HEADER_IDENTITY_OFFSET)
        + data[GENERATION_HEADER_IDENTITY_END:]
    )


def bootstate_checksum(slot: bytes) -> bytes:
    return sha256(
        slot[:BOOTSTATE_CHECKSUM_OFFSET]
        + bytes(BOOTSTATE_CHECKSUM_END - BOOTSTATE_CHECKSUM_OFFSET)
        + slot[BOOTSTATE_CHECKSUM_END:]
    )


def bootstore_checksum(data: bytes) -> bytes:
    offset = BOOTSTORE_DIRECTORY_OFFSET + BOOTSTORE_HEADER_CHECKSUM_OFFSET
    end = BOOTSTORE_DIRECTORY_OFFSET + BOOTSTORE_HEADER_CHECKSUM_END
    return sha256(data[BOOTSTATE_SLOT_BYTES * BOOTSTATE_SLOT_COUNT : offset] + bytes(end - offset) + data[end:])
