# @generated by contracts/cpu-boot-observation/v1/schema.zt; do not edit.
FORMAT_VERSION = 1
KIND = "slime-cpu-boot-observation"
IDENTITY_DOMAIN = "slime-cpu-boot-observation-v1:".encode("utf-8")
RECORD_FILE_NAME = "slime-cpu-boot.observation.json"
REQUIRED_BOOTS = 2
COMPARISON_REGION_BYTES = 16777216
MAX_RECORD_BYTES = 65536
MAX_PATH_BYTES = 192
MAX_TEXT_BYTES = 128
MAX_BOOTS = 4
MAX_RECORD_LINES = 16
TARGET_PROFILE = "x86_64-sel4-framework13-ai300"
BOOT_OUTCOMES = ("ready", "no-boot", "firmware-refused", "wrong-profile", "faulted", )
