# @generated by contracts/devloop-diagnostics/v1/bindings.zt; do not edit.
import json

FORMAT_VERSION = 1
KIND = 'slime-devloop-diagnostics'
MAX_RECEIPT_BYTES = 8192
MAX_OUTPUT_BYTES = 65536
MAX_PATH_BYTES = 240
RECEIPT_FIELDS = ('formatVersion', 'kind', 'runKey', 'identity', 'justTarget', 'recipeExitCode', 'outputPath', 'sha256', 'capturedBytes', 'limitBytes', 'truncated')
IDENTITY_FIELDS = ('requirements', 'helper', 'code', 'policy', 'inputs', 'target', 'image', 'epoch')


def encode(receipt):
    if set(receipt) != set(RECEIPT_FIELDS) or set(receipt["identity"]) != set(IDENTITY_FIELDS):
        raise ValueError("diagnostic receipt fields do not match schema")
    def value(item):
        if isinstance(item, dict):
            return "{" + "".join(name + "=" + value(part) + ";" for name, part in item.items()) + "}"
        if type(item) is bool:
            return "true" if item else "false"
        if type(item) is int:
            return str(item)
        if isinstance(item, str):
            return json.dumps(item)
        raise ValueError("unsupported diagnostic receipt value")
    encoded = (value(receipt) + "\n").encode()
    if len(encoded) > MAX_RECEIPT_BYTES:
        raise ValueError("diagnostic receipt exceeds schema bound")
    return encoded
