# @generated by contracts/interface-schema/v1/gen_python.zt; do not edit.
FORMAT_VERSION = 1
MAX_SCHEMAS = 64
MAX_SOURCE_BYTES = 65536
MAX_NORMALIZED_BYTES = 65536
MAX_GENERATED_BYTES = 262144
MAX_NAME_BYTES = 64
MAX_TYPES = 64
MAX_FIELDS_PER_TYPE = 32
MAX_TOTAL_FIELDS = 256
MAX_DEPTH = 8
MAX_SEQUENCE_ELEMENTS = 4096
MAX_ENCODED_BYTES = 1048576
IDENTITY_DOMAIN = "slime-interface-schema-v1:".encode("utf-8")
TAG_DOMAIN = "slime-interface-type-tag-v1:".encode("utf-8")
FIELD_KINDS = ("scalar", "bytes", "record", "sequence")
CONTRACT_KINDS = ("stream", "call", "operation")
