"""MAVLink v2 HEARTBEAT framing, and a resynchronising decoder for a radio port.

A telemetry radio is a transparent serial link, so the only thing that says a
board transmitted is a frame decoded on the far side. That makes this the
instrument a UART gate reads, and it is written here rather than taken from
`pymavlink` for the reason `scripts/check/check-rpi5-boot.py` gives about
`pyserial`: the pinned shell carries neither, and one message plus a CRC is a
page of stdlib against a dependency in every gate that would import it.

Two properties matter for that use and are not obvious:

* The decoder resynchronises on the start byte and never trusts a length it has
  not checked, because the bytes arriving from a radio are not only the board's.
  A linked SiK-family radio injects its own `RADIO_STATUS` into the stream, and
  a session may begin mid-frame.
* Only HEARTBEAT is checksum-verified. Every MAVLink message mixes a per-message
  `CRC_EXTRA` into its checksum, so verifying another message would mean
  carrying that table; those frames are reported with `crc_ok` unset rather than
  silently dropped or wrongly failed.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass

#: MAVLink v2 start byte. v1 (`0xFE`) is not produced or decoded here.
STX = 0xFD

#: Message identities this module knows. `RADIO_STATUS` is not decoded beyond
#: its signal-strength bytes; it is here because a linked radio emits it into
#: the same stream and a decoder that treated it as corruption would resync
#: through a heartbeat.
HEARTBEAT_MSGID = 0
RADIO_STATUS_MSGID = 109

#: HEARTBEAT's wire payload, in MAVLink's field order (descending field width,
#: not declaration order), and the `CRC_EXTRA` its checksum mixes in.
HEARTBEAT_LEN = 9
HEARTBEAT_CRC_EXTRA = 50
HEARTBEAT_FRAME_LEN = 12 + HEARTBEAT_LEN

#: Header, payload, and checksum sizes shared by every v2 frame. A signed frame
#: carries 13 further bytes, which `incompat_flags` bit 0 announces.
HEADER_LEN = 10
CHECKSUM_LEN = 2
INCOMPAT_SIGNED = 0x01
SIGNATURE_LEN = 13

#: What this lane's heartbeat says it is: an onboard computer with no autopilot,
#: active, speaking MAVLink 2. `MAV_COMP_ID_ONBOARD_COMPUTER`,
#: `MAV_TYPE_ONBOARD_CONTROLLER`, `MAV_AUTOPILOT_INVALID`, `MAV_STATE_ACTIVE`.
DEFAULT_SYSID = 1
DEFAULT_COMPID = 191
DEFAULT_TYPE = 18
DEFAULT_AUTOPILOT = 8
DEFAULT_BASE_MODE = 0
DEFAULT_CUSTOM_MODE = 0
DEFAULT_SYSTEM_STATUS = 4
MAVLINK_VERSION = 3


def x25_crc(data: bytes, crc: int = 0xFFFF) -> int:
    """CRC-16/MCRF4XX over `data`, MAVLink's checksum.

    Reflected polynomial 0x8408, initial value 0xFFFF, no final inversion.
    `x25_crc(b"123456789") == 0x6F91` is the published check value.
    """
    for byte in data:
        scratch = byte ^ (crc & 0xFF)
        scratch = (scratch ^ (scratch << 4)) & 0xFF
        crc = ((crc >> 8) ^ (scratch << 8) ^ (scratch << 3) ^ (scratch >> 4)) & 0xFFFF
    return crc


def encode_heartbeat(
    seq: int,
    *,
    sysid: int = DEFAULT_SYSID,
    compid: int = DEFAULT_COMPID,
    mav_type: int = DEFAULT_TYPE,
    autopilot: int = DEFAULT_AUTOPILOT,
    base_mode: int = DEFAULT_BASE_MODE,
    custom_mode: int = DEFAULT_CUSTOM_MODE,
    system_status: int = DEFAULT_SYSTEM_STATUS,
    mavlink_version: int = MAVLINK_VERSION,
) -> bytes:
    """One unsigned MAVLink v2 HEARTBEAT, 21 bytes.

    The payload's last byte is `mavlink_version`, which this lane never sends as
    zero, so v2's trailing-zero truncation never shortens the frame and `len` is
    always `HEARTBEAT_LEN`.
    """
    if not 0 <= seq <= 0xFF:
        raise ValueError(f"sequence {seq} is outside a MAVLink v2 sequence byte")
    payload = struct.pack(
        "<IBBBBB",
        custom_mode,
        mav_type,
        autopilot,
        base_mode,
        system_status,
        mavlink_version,
    )
    header = bytes([HEARTBEAT_LEN, 0, 0, seq, sysid, compid, HEARTBEAT_MSGID, 0, 0])
    crc = x25_crc(bytes([HEARTBEAT_CRC_EXTRA]), x25_crc(header + payload))
    return bytes([STX]) + header + payload + struct.pack("<H", crc)


#: Frames this lane pins, so an encoder change is a test failure rather than a
#: silent rewire of what the ground station receives. Regenerated by
#: `encode_heartbeat`; asserted in `scripts/check/check-nt98690-bench-probe.py`.
PINNED_HEARTBEATS: dict[int, bytes] = {
    0: bytes.fromhex("fd0900000001bf000000000000001208000403aec6"),
    1: bytes.fromhex("fd0900000101bf000000000000001208000403be48"),
    255: bytes.fromhex("fd090000ff01bf000000000000001208000403b77c"),
}


@dataclass(frozen=True)
class Frame:
    """One decoded MAVLink v2 frame.

    `crc_ok` is `None` for every message but HEARTBEAT: this module carries one
    message's `CRC_EXTRA`, so any other frame's checksum is unchecked rather
    than assumed good or assumed bad.
    """

    msgid: int
    seq: int
    sysid: int
    compid: int
    payload: bytes
    crc_ok: bool | None
    raw: bytes


class FrameDecoder:
    """Feed bytes, take whole frames, keep the remainder.

    A frame is emitted only once its checksum bytes have arrived, so a caller
    reading fixed windows off a serial port can call `feed` with whatever each
    read returned. A frame whose checksum fails is still emitted, with
    `crc_ok=False`, and scanning resumes one byte after its start marker rather
    than past its claimed end: a corrupt length would otherwise skip whatever
    real frame follows. A frame this module cannot verify (`crc_ok=None`) is
    consumed whole: its length is as trustworthy as any other radio frame's,
    and rescanning its body would turn a 0xFD in a sequence or signal byte into
    a bogus frame that swallows the heartbeat behind it. A frame this module cannot verify (`crc_ok=None`) is
    consumed whole: its length is as trustworthy as any other radio frame's,
    and rescanning its body would turn a 0xFD in a sequence or signal byte into
    a bogus frame that swallows the heartbeat behind it.
    """

    def __init__(self) -> None:
        self._buffer = bytearray()

    def feed(self, data: bytes) -> list[Frame]:
        self._buffer.extend(data)
        frames: list[Frame] = []
        while True:
            start = self._buffer.find(STX)
            if start < 0:
                # Nothing in the buffer can begin a frame.
                self._buffer.clear()
                break
            if start:
                del self._buffer[:start]
            if len(self._buffer) < HEADER_LEN:
                break
            payload_len = self._buffer[1]
            incompat = self._buffer[2]
            total = HEADER_LEN + payload_len + CHECKSUM_LEN
            if incompat & INCOMPAT_SIGNED:
                total += SIGNATURE_LEN
            if len(self._buffer) < total:
                break
            raw = bytes(self._buffer[:total])
            frame = self._decode(raw, payload_len)
            frames.append(frame)
            # Resync past the start byte only on a checksum that failed; a
            # frame this module does not verify is still a whole frame.
            del self._buffer[: 1 if frame.crc_ok is False else total]
        return frames

    @staticmethod
    def _decode(raw: bytes, payload_len: int) -> Frame:
        msgid = int.from_bytes(raw[7:10], "little")
        payload = raw[HEADER_LEN : HEADER_LEN + payload_len]
        crc_ok: bool | None = None
        if msgid == HEARTBEAT_MSGID:
            expected = x25_crc(
                bytes([HEARTBEAT_CRC_EXTRA]),
                x25_crc(raw[1 : HEADER_LEN + payload_len]),
            )
            offset = HEADER_LEN + payload_len
            crc_ok = expected == int.from_bytes(raw[offset : offset + CHECKSUM_LEN], "little")
        return Frame(
            msgid=msgid,
            seq=raw[4],
            sysid=raw[5],
            compid=raw[6],
            payload=payload,
            crc_ok=crc_ok,
            raw=raw,
        )


def radio_status_rssi(frame: Frame) -> tuple[int, int] | None:
    """`(rssi, remrssi)` from a radio's own status frame, or `None`.

    The radio injects these into the ground-side stream, so they report the
    link rather than anything the board said. Unverified, like every non-
    heartbeat frame here.
    """
    if frame.msgid != RADIO_STATUS_MSGID or len(frame.payload) < 6:
        return None
    return frame.payload[4], frame.payload[5]
