# @generated by contracts/observation-capacity-refusal/v1/bindings.zt; do not edit.
import json

FORMAT_VERSION = 1
KIND = 'slime-observation-capacity-refusal'
OUTCOME = 'stderr-capacity'
GATE = 'just-observations'
STDERR_LIMIT_BYTES = 65536
MAX_RECEIPT_BYTES = 8192
MAX_PATH_BYTES = 240
REUSE_SECONDS = 3600
RECEIPT_FIELDS = ('formatVersion', 'kind', 'runKey', 'gate', 'justTarget', 'identity', 'outcome', 'stderrLimitBytes', 'stderrObservedBytes', 'recipeExitCode', 'diagnosticReceiptPath', 'diagnosticReceiptSha256', 'finishedAt', 'reuseUntil')
IDENTITY_FIELDS = ('requirements', 'helper', 'code', 'policy', 'inputs', 'target', 'image', 'epoch')


def encode(receipt):
    if set(receipt) != set(RECEIPT_FIELDS) or set(receipt["identity"]) != set(IDENTITY_FIELDS):
        raise ValueError("capacity refusal fields do not match schema")
    def value(item):
        if isinstance(item, dict):
            return "{" + "".join(k + "=" + value(v) + ";" for k,v in item.items()) + "}"
        if type(item) is int:
            return str(item)
        if isinstance(item, str):
            return json.dumps(item)
        raise ValueError("unsupported capacity refusal value")
    raw = (value(receipt) + "\n").encode()
    if len(raw) > MAX_RECEIPT_BYTES:
        raise ValueError("capacity refusal exceeds schema bound")
    return raw
