# @generated by contracts/system-test-run/v1/gen_python.zt; do not edit.
FORMAT_VERSION = 1
IDENTITY_DOMAIN = "slime-system-test-run-v1:".encode("utf-8")
EXECUTION_KINDS = ("emulator", "board", )
FAULT_KINDS = ("peer-death", "device", "corruption", "delay", )
MAX_SOURCE_BYTES = 131072
MAX_NORMALIZED_BYTES = 131072
MAX_NAME_BYTES = 96
MAX_PATH_BYTES = 256
MAX_TEXT_BYTES = 256
MAX_DIGEST_BYTES = 64
MAX_FIXTURES = 16
MAX_FAULT_CONTROLS = 16
MAX_FORBIDDEN_OUTCOMES = 32
MAX_TIMEOUT_SECONDS = 3600
