[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=small",
    "-C", "link-arg=--build-id=none",
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=4096",
    "--remap-path-prefix", "/home/iceice666/projects/slime_os=.",
]
