# @generated from boot contract schemas; do not edit.
from __future__ import annotations

import hashlib
import struct

GENERATION_MAGIC = b"SLIMEG2\0"
GENERATION_VERSION = 2
GENERATION_HEADER = struct.Struct("<8sIIQ32sQ32sIIIIIIIIIIQQQQQQQQQQ40x")
GENERATION_HEADER_MAGIC_OFFSET = 0
GENERATION_HEADER_MAGIC_END = 8
GENERATION_HEADER_FORMAT_VERSION_OFFSET = 8
GENERATION_HEADER_FORMAT_VERSION_END = 12
GENERATION_HEADER_HEADER_SIZE_OFFSET = 12
GENERATION_HEADER_HEADER_SIZE_END = 16
GENERATION_HEADER_REQUIRED_FLAGS_OFFSET = 16
GENERATION_HEADER_REQUIRED_FLAGS_END = 24
GENERATION_HEADER_IDENTITY_OFFSET = 24
GENERATION_HEADER_IDENTITY_END = 56
GENERATION_HEADER_GENERATION_NUMBER_OFFSET = 56
GENERATION_HEADER_GENERATION_NUMBER_END = 64
GENERATION_HEADER_PARENT_OFFSET = 64
GENERATION_HEADER_PARENT_END = 96
GENERATION_HEADER_TARGET_OFFSET_OFFSET = 96
GENERATION_HEADER_TARGET_OFFSET_END = 100
GENERATION_HEADER_KERNEL_OBJECT_OFFSET = 100
GENERATION_HEADER_KERNEL_OBJECT_END = 104
GENERATION_HEADER_BOOTSTRAP_COMPONENT_OFFSET = 104
GENERATION_HEADER_BOOTSTRAP_COMPONENT_END = 108
GENERATION_HEADER_BOOT_ATTEMPTS_OFFSET = 108
GENERATION_HEADER_BOOT_ATTEMPTS_END = 112
GENERATION_HEADER_OBJECT_COUNT_OFFSET = 112
GENERATION_HEADER_OBJECT_COUNT_END = 116
GENERATION_HEADER_COMPONENT_COUNT_OFFSET = 116
GENERATION_HEADER_COMPONENT_COUNT_END = 120
GENERATION_HEADER_DEPENDENCY_COUNT_OFFSET = 120
GENERATION_HEADER_DEPENDENCY_COUNT_END = 124
GENERATION_HEADER_GRANT_COUNT_OFFSET = 124
GENERATION_HEADER_GRANT_COUNT_END = 128
GENERATION_HEADER_STATE_COUNT_OFFSET = 128
GENERATION_HEADER_STATE_COUNT_END = 132
GENERATION_HEADER_HEALTH_COUNT_OFFSET = 132
GENERATION_HEADER_HEALTH_COUNT_END = 136
GENERATION_HEADER_OBJECT_OFFSET_OFFSET = 136
GENERATION_HEADER_OBJECT_OFFSET_END = 144
GENERATION_HEADER_COMPONENT_OFFSET_OFFSET = 144
GENERATION_HEADER_COMPONENT_OFFSET_END = 152
GENERATION_HEADER_DEPENDENCY_OFFSET_OFFSET = 152
GENERATION_HEADER_DEPENDENCY_OFFSET_END = 160
GENERATION_HEADER_GRANT_OFFSET_OFFSET = 160
GENERATION_HEADER_GRANT_OFFSET_END = 168
GENERATION_HEADER_STATE_OFFSET_OFFSET = 168
GENERATION_HEADER_STATE_OFFSET_END = 176
GENERATION_HEADER_HEALTH_OFFSET_OFFSET = 176
GENERATION_HEADER_HEALTH_OFFSET_END = 184
GENERATION_HEADER_STRING_OFFSET_OFFSET = 184
GENERATION_HEADER_STRING_OFFSET_END = 192
GENERATION_HEADER_STRING_LEN_OFFSET = 192
GENERATION_HEADER_STRING_LEN_END = 200
GENERATION_HEADER_PAYLOAD_OFFSET_OFFSET = 200
GENERATION_HEADER_PAYLOAD_OFFSET_END = 208
GENERATION_HEADER_TOTAL_LEN_OFFSET = 208
GENERATION_HEADER_TOTAL_LEN_END = 216

GENERATION_OBJECT = struct.Struct("<IIQQ32s8x")
GENERATION_OBJECT_ID_OFFSET_OFFSET = 0
GENERATION_OBJECT_ID_OFFSET_END = 4
GENERATION_OBJECT_KIND_OFFSET = 4
GENERATION_OBJECT_KIND_END = 8
GENERATION_OBJECT_PAYLOAD_OFFSET_OFFSET = 8
GENERATION_OBJECT_PAYLOAD_OFFSET_END = 16
GENERATION_OBJECT_PAYLOAD_LEN_OFFSET = 16
GENERATION_OBJECT_PAYLOAD_LEN_END = 24
GENERATION_OBJECT_DIGEST_OFFSET = 24
GENERATION_OBJECT_DIGEST_END = 56

GENERATION_COMPONENT = struct.Struct("<IIIII12x")
GENERATION_COMPONENT_NAME_OFFSET_OFFSET = 0
GENERATION_COMPONENT_NAME_OFFSET_END = 4
GENERATION_COMPONENT_OBJECT_INDEX_OFFSET = 4
GENERATION_COMPONENT_OBJECT_INDEX_END = 8
GENERATION_COMPONENT_ROLE_OFFSET = 8
GENERATION_COMPONENT_ROLE_END = 12
GENERATION_COMPONENT_DEPENDENCY_START_OFFSET = 12
GENERATION_COMPONENT_DEPENDENCY_START_END = 16
GENERATION_COMPONENT_DEPENDENCY_COUNT_OFFSET = 16
GENERATION_COMPONENT_DEPENDENCY_COUNT_END = 20

GENERATION_DEPENDENCY = struct.Struct("<I")
GENERATION_DEPENDENCY_COMPONENT_OFFSET = 0
GENERATION_DEPENDENCY_COMPONENT_END = 4

GENERATION_GRANT = struct.Struct("<IIIII12x")
GENERATION_GRANT_NAME_OFFSET_OFFSET = 0
GENERATION_GRANT_NAME_OFFSET_END = 4
GENERATION_GRANT_SOURCE_OFFSET = 4
GENERATION_GRANT_SOURCE_END = 8
GENERATION_GRANT_TARGET_OFFSET = 8
GENERATION_GRANT_TARGET_END = 12
GENERATION_GRANT_RIGHTS_OFFSET = 12
GENERATION_GRANT_RIGHTS_END = 16
GENERATION_GRANT_TRANSFERABLE_OFFSET = 16
GENERATION_GRANT_TRANSFERABLE_END = 20

GENERATION_STATE = struct.Struct("<IIII8x")
GENERATION_STATE_NAME_OFFSET_OFFSET = 0
GENERATION_STATE_NAME_OFFSET_END = 4
GENERATION_STATE_OWNER_OFFSET = 4
GENERATION_STATE_OWNER_END = 8
GENERATION_STATE_SCHEMA_VERSION_OFFSET = 8
GENERATION_STATE_SCHEMA_VERSION_END = 12
GENERATION_STATE_POLICY_OFFSET = 12
GENERATION_STATE_POLICY_END = 16

GENERATION_HEALTH = struct.Struct("<I")
GENERATION_HEALTH_COMPONENT_OFFSET = 0
GENERATION_HEALTH_COMPONENT_END = 4

MAX_GENERATION_BYTES = 16777216
MAX_OBJECTS = 64
MAX_COMPONENTS = 32
MAX_GRANTS = 128
MAX_STATES = 32
MAX_DEPENDENCIES = 128
MAX_HEALTH_COMPONENTS = 32
MAX_STRING_BYTES = 255
MAX_STRING_TABLE_BYTES = 65536
MAX_OBJECT_PAYLOAD_BYTES = 8388608

KERNEL_MAGIC = b"SLIMEKRN"
KERNEL_VERSION = 1
KERNEL_ABI_VERSION = 2
KERNEL_HEADER = struct.Struct("<8sIIIIQQIIQQ")
KERNEL_HEADER_MAGIC_OFFSET = 0
KERNEL_HEADER_MAGIC_END = 8
KERNEL_HEADER_FORMAT_VERSION_OFFSET = 8
KERNEL_HEADER_FORMAT_VERSION_END = 12
KERNEL_HEADER_HEADER_SIZE_OFFSET = 12
KERNEL_HEADER_HEADER_SIZE_END = 16
KERNEL_HEADER_KERNEL_ABI_OFFSET = 16
KERNEL_HEADER_KERNEL_ABI_END = 20
KERNEL_HEADER_REQUIRED_FLAGS_OFFSET = 20
KERNEL_HEADER_REQUIRED_FLAGS_END = 24
KERNEL_HEADER_PREFERRED_BASE_OFFSET = 24
KERNEL_HEADER_PREFERRED_BASE_END = 32
KERNEL_HEADER_ENTRY_OFFSET_OFFSET = 32
KERNEL_HEADER_ENTRY_OFFSET_END = 40
KERNEL_HEADER_SEGMENT_COUNT_OFFSET = 40
KERNEL_HEADER_SEGMENT_COUNT_END = 44
KERNEL_HEADER_RELOCATION_COUNT_OFFSET = 44
KERNEL_HEADER_RELOCATION_COUNT_END = 48
KERNEL_HEADER_PAYLOAD_OFFSET_OFFSET = 48
KERNEL_HEADER_PAYLOAD_OFFSET_END = 56
KERNEL_HEADER_TOTAL_LEN_OFFSET = 56
KERNEL_HEADER_TOTAL_LEN_END = 64

KERNEL_SEGMENT = struct.Struct("<QQQQII")
KERNEL_SEGMENT_VADDR_OFFSET_OFFSET = 0
KERNEL_SEGMENT_VADDR_OFFSET_END = 8
KERNEL_SEGMENT_MEM_LEN_OFFSET = 8
KERNEL_SEGMENT_MEM_LEN_END = 16
KERNEL_SEGMENT_FILE_OFFSET_OFFSET = 16
KERNEL_SEGMENT_FILE_OFFSET_END = 24
KERNEL_SEGMENT_FILE_LEN_OFFSET = 24
KERNEL_SEGMENT_FILE_LEN_END = 32
KERNEL_SEGMENT_FLAGS_OFFSET = 32
KERNEL_SEGMENT_FLAGS_END = 36
KERNEL_SEGMENT_RESERVED_OFFSET = 36
KERNEL_SEGMENT_RESERVED_END = 40

KERNEL_RELOCATION = struct.Struct("<Qq")
KERNEL_RELOCATION_TARGET_OFFSET_OFFSET = 0
KERNEL_RELOCATION_TARGET_OFFSET_END = 8
KERNEL_RELOCATION_ADDEND_OFFSET = 8
KERNEL_RELOCATION_ADDEND_END = 16

KERNEL_PREFERRED_BASE = 0xFFFF_FFFF_8000_0000
KERNEL_LOAD_BASE = 0xFFFF_FFFF_9000_0000
MAX_KERNEL_IMAGE_BYTES = 8388608
MAX_KERNEL_SEGMENTS = 8
MAX_KERNEL_RELOCATIONS = 16384
SEGMENT_WRITE = 1
SEGMENT_EXEC = 2

BOOTSTATE_MAGIC = b"SLIMEBS\0"
BOOTSTATE_VERSION = 2
BOOTSTATE_SLOT_BYTES = 512
BOOTSTATE_SLOT_COUNT = 2
BOOTSTATE_REQUIRED_FLAGS = 0
BOOTSTATE_SLOT = struct.Struct("<8sIIQQ32s32sII32s32sQ32s304x")
BOOTSTATE_MAGIC_OFFSET = 0
BOOTSTATE_MAGIC_END = 8
BOOTSTATE_FORMAT_VERSION_OFFSET = 8
BOOTSTATE_FORMAT_VERSION_END = 12
BOOTSTATE_HEADER_SIZE_OFFSET = 12
BOOTSTATE_HEADER_SIZE_END = 16
BOOTSTATE_REQUIRED_FLAGS_OFFSET = 16
BOOTSTATE_REQUIRED_FLAGS_END = 24
BOOTSTATE_SEQUENCE_OFFSET = 24
BOOTSTATE_SEQUENCE_END = 32
BOOTSTATE_KNOWN_GOOD_OFFSET = 32
BOOTSTATE_KNOWN_GOOD_END = 64
BOOTSTATE_PENDING_OFFSET = 64
BOOTSTATE_PENDING_END = 96
BOOTSTATE_REMAINING_ATTEMPTS_OFFSET = 96
BOOTSTATE_REMAINING_ATTEMPTS_END = 100
BOOTSTATE_RESERVED_OFFSET = 100
BOOTSTATE_RESERVED_END = 104
BOOTSTATE_GENERATION_ROOT_OFFSET = 104
BOOTSTATE_GENERATION_ROOT_END = 136
BOOTSTATE_STATE_ROOT_OFFSET = 136
BOOTSTATE_STATE_ROOT_END = 168
BOOTSTATE_ACCEPTED_RELEASE_SEQUENCE_OFFSET = 168
BOOTSTATE_ACCEPTED_RELEASE_SEQUENCE_END = 176
BOOTSTATE_CHECKSUM_OFFSET = 176
BOOTSTATE_CHECKSUM_END = 208

BOOTSTORE_HEADER = struct.Struct("<8sIIQIIQQ32s16x")
BOOTSTORE_HEADER_MAGIC_OFFSET = 0
BOOTSTORE_HEADER_MAGIC_END = 8
BOOTSTORE_HEADER_FORMAT_VERSION_OFFSET = 8
BOOTSTORE_HEADER_FORMAT_VERSION_END = 12
BOOTSTORE_HEADER_HEADER_SIZE_OFFSET = 12
BOOTSTORE_HEADER_HEADER_SIZE_END = 16
BOOTSTORE_HEADER_REQUIRED_FLAGS_OFFSET = 16
BOOTSTORE_HEADER_REQUIRED_FLAGS_END = 24
BOOTSTORE_HEADER_ENTRY_COUNT_OFFSET = 24
BOOTSTORE_HEADER_ENTRY_COUNT_END = 28
BOOTSTORE_HEADER_RESERVED_OFFSET = 28
BOOTSTORE_HEADER_RESERVED_END = 32
BOOTSTORE_HEADER_DIRECTORY_LEN_OFFSET = 32
BOOTSTORE_HEADER_DIRECTORY_LEN_END = 40
BOOTSTORE_HEADER_CAPACITY_OFFSET = 40
BOOTSTORE_HEADER_CAPACITY_END = 48
BOOTSTORE_HEADER_CHECKSUM_OFFSET = 48
BOOTSTORE_HEADER_CHECKSUM_END = 80

BOOTSTORE_ENTRY = struct.Struct("<32sQQQQ32x")
BOOTSTORE_ENTRY_IDENTITY_OFFSET = 0
BOOTSTORE_ENTRY_IDENTITY_END = 32
BOOTSTORE_ENTRY_GENERATION_OFFSET_OFFSET = 32
BOOTSTORE_ENTRY_GENERATION_OFFSET_END = 40
BOOTSTORE_ENTRY_GENERATION_LEN_OFFSET = 40
BOOTSTORE_ENTRY_GENERATION_LEN_END = 48
BOOTSTORE_ENTRY_RELEASE_OFFSET_OFFSET = 48
BOOTSTORE_ENTRY_RELEASE_OFFSET_END = 56
BOOTSTORE_ENTRY_RELEASE_LEN_OFFSET = 56
BOOTSTORE_ENTRY_RELEASE_LEN_END = 64

BOOTSTATE_RELEASE_SEQUENCE_OFFSET = BOOTSTATE_ACCEPTED_RELEASE_SEQUENCE_OFFSET
BOOTSTORE_MAGIC = b"SLIMEBT\0"
BOOTSTORE_VERSION = 1
BOOTSTORE_CAPACITY = 33554432
BOOTSTORE_DIRECTORY_OFFSET = 4096
BOOTSTORE_RELEASES_OFFSET = 8192
BOOTSTORE_GENERATIONS_OFFSET = 16384

RELEASE_MAGIC = b"SLIMERL\0"
RELEASE_VERSION = 1
RELEASE_BYTES = 512
RELEASE_HEADER_BYTES = 208
RELEASE_SIGNATURE_BYTES = 96
MAX_RELEASE_SIGNATURES = 3
MAX_TARGET_BYTES = 32
RELEASE_HEADER = struct.Struct("<8sIIQ32s32sQII32s32s32sI4s")
RELEASE_HEADER_MAGIC_OFFSET = 0
RELEASE_HEADER_MAGIC_END = 8
RELEASE_HEADER_FORMAT_VERSION_OFFSET = 8
RELEASE_HEADER_FORMAT_VERSION_END = 12
RELEASE_HEADER_HEADER_SIZE_OFFSET = 12
RELEASE_HEADER_HEADER_SIZE_END = 16
RELEASE_HEADER_REQUIRED_FLAGS_OFFSET = 16
RELEASE_HEADER_REQUIRED_FLAGS_END = 24
RELEASE_HEADER_GENERATION_IDENTITY_OFFSET = 24
RELEASE_HEADER_GENERATION_IDENTITY_END = 56
RELEASE_HEADER_PARENT_IDENTITY_OFFSET = 56
RELEASE_HEADER_PARENT_IDENTITY_END = 88
RELEASE_HEADER_RELEASE_SEQUENCE_OFFSET = 88
RELEASE_HEADER_RELEASE_SEQUENCE_END = 96
RELEASE_HEADER_TARGET_LEN_OFFSET = 96
RELEASE_HEADER_TARGET_LEN_END = 100
RELEASE_HEADER_TRUST_ROOT_VERSION_OFFSET = 100
RELEASE_HEADER_TRUST_ROOT_VERSION_END = 104
RELEASE_HEADER_TARGET_OFFSET = 104
RELEASE_HEADER_TARGET_END = 136
RELEASE_HEADER_KERNEL_IDENTITY_OFFSET = 136
RELEASE_HEADER_KERNEL_IDENTITY_END = 168
RELEASE_HEADER_AUTHORITY_MANIFEST_OFFSET = 168
RELEASE_HEADER_AUTHORITY_MANIFEST_END = 200
RELEASE_HEADER_SIGNATURE_COUNT_OFFSET = 200
RELEASE_HEADER_SIGNATURE_COUNT_END = 204
RELEASE_HEADER_RESERVED_OFFSET = 204
RELEASE_HEADER_RESERVED_END = 208

RELEASE_SIGNATURE = struct.Struct("<32s64s")
RELEASE_SIGNATURE_KEY_ID_OFFSET = 0
RELEASE_SIGNATURE_KEY_ID_END = 32
RELEASE_SIGNATURE_SIGNATURE_OFFSET = 32
RELEASE_SIGNATURE_SIGNATURE_END = 96

BOOTSTATE_TRACE_VERSION = 1
BOOTSTATE_TRACE_MAX_LINE = 640

def sha256(data: bytes) -> bytes:
    return hashlib.sha256(data).digest()


def generation_identity(data: bytes) -> bytes:
    return sha256(
        data[:GENERATION_HEADER_IDENTITY_OFFSET]
        + bytes(GENERATION_HEADER_IDENTITY_END - GENERATION_HEADER_IDENTITY_OFFSET)
        + data[GENERATION_HEADER_IDENTITY_END:]
    )


def bootstate_checksum(slot: bytes) -> bytes:
    return sha256(
        slot[:BOOTSTATE_CHECKSUM_OFFSET]
        + bytes(BOOTSTATE_CHECKSUM_END - BOOTSTATE_CHECKSUM_OFFSET)
        + slot[BOOTSTATE_CHECKSUM_END:]
    )


def bootstore_checksum(data: bytes) -> bytes:
    offset = BOOTSTORE_DIRECTORY_OFFSET + BOOTSTORE_HEADER_CHECKSUM_OFFSET
    end = BOOTSTORE_DIRECTORY_OFFSET + BOOTSTORE_HEADER_CHECKSUM_END
    return sha256(data[BOOTSTATE_SLOT_BYTES * BOOTSTATE_SLOT_COUNT : offset] + bytes(end - offset) + data[end:])
