#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "scripts" / "boot_contracts.py"
STDLIB = ROOT / "deps" / "zutai" / "stdlib"
CONTRACTS = (
    ROOT / "contracts" / "generation" / "v2",
    ROOT / "contracts" / "kernel-image" / "v1",
    ROOT / "contracts" / "bootstate" / "v1",
    ROOT / "contracts" / "bootstate" / "trace" / "v1",
)

SOURCE = '''# @generated by scripts/generate-boot-bindings.py; do not edit.
from __future__ import annotations

import hashlib
import struct

GENERATION_MAGIC = b"SLIMEG2\\0"
GENERATION_VERSION = 2
GENERATION_HEADER = struct.Struct("<8sIIQ32sQ32sIIIIIIIIIIQQQQQQQQQQ40x")
GENERATION_OBJECT = struct.Struct("<IIQQ32s8x")
GENERATION_COMPONENT = struct.Struct("<IIIII12x")
GENERATION_DEPENDENCY = struct.Struct("<I")
GENERATION_GRANT = struct.Struct("<IIIII12x")
GENERATION_STATE = struct.Struct("<IIII8x")
GENERATION_HEALTH = struct.Struct("<I")
MAX_GENERATION_BYTES = 16 * 1024 * 1024
MAX_OBJECTS = 64
MAX_COMPONENTS = 32
MAX_GRANTS = 128
MAX_STATES = 32
MAX_DEPENDENCIES = 128
MAX_HEALTH_COMPONENTS = 32
MAX_STRING_BYTES = 255
MAX_STRING_TABLE_BYTES = 64 * 1024
MAX_OBJECT_PAYLOAD_BYTES = 8 * 1024 * 1024

KERNEL_MAGIC = b"SLIMEKRN"
KERNEL_VERSION = 1
KERNEL_ABI_VERSION = 2
KERNEL_HEADER = struct.Struct("<8sIIIIQQIIQQ")
KERNEL_SEGMENT = struct.Struct("<QQQQII")
KERNEL_RELOCATION = struct.Struct("<Qq")
KERNEL_PREFERRED_BASE = 0xFFFF_FFFF_8000_0000
KERNEL_LOAD_BASE = 0xFFFF_FFFF_9000_0000
MAX_KERNEL_IMAGE_BYTES = 8 * 1024 * 1024
MAX_KERNEL_SEGMENTS = 8
MAX_KERNEL_RELOCATIONS = 16_384
SEGMENT_WRITE = 1
SEGMENT_EXEC = 2

BOOTSTATE_MAGIC = b"SLIMEBS\\0"
BOOTSTATE_VERSION = 1
BOOTSTATE_SLOT_BYTES = 512
BOOTSTATE_CHECKSUM_OFFSET = 168
BOOTSTATE_CHECKSUM_END = 200
BOOTSTORE_MAGIC = b"SLIMEBT\\0"
BOOTSTORE_VERSION = 1
BOOTSTORE_HEADER = struct.Struct("<8sIIQIIQQ32s16x")
BOOTSTORE_ENTRY = struct.Struct("<32sQQ16x")
BOOTSTORE_CAPACITY = 32 * 1024 * 1024
BOOTSTORE_DIRECTORY_OFFSET = 4096
BOOTSTORE_GENERATIONS_OFFSET = 8192

BOOTSTATE_TRACE_VERSION = 1
BOOTSTATE_TRACE_MAX_LINE = 640


def sha256(data: bytes) -> bytes:
    return hashlib.sha256(data).digest()


def generation_identity(data: bytes) -> bytes:
    return sha256(data[:24] + bytes(32) + data[56:])


def bootstate_checksum(slot: bytes) -> bytes:
    return sha256(slot[:BOOTSTATE_CHECKSUM_OFFSET] + bytes(32) + slot[BOOTSTATE_CHECKSUM_END:])


def bootstore_checksum(data: bytes) -> bytes:
    offset = BOOTSTORE_DIRECTORY_OFFSET + 48
    return sha256(data[BOOTSTATE_SLOT_BYTES * 2 : offset] + bytes(32) + data[offset + 32 :])
'''


def check_contracts() -> None:
    environment = os.environ.copy()
    environment["ZUTAI_STDLIB_ROOT"] = str(STDLIB)
    for contract in CONTRACTS:
        for name in ("schema.zt", "gen_rust.zt"):
            subprocess.run(
                [
                    "cargo", "run", "--manifest-path", str(ROOT / "deps" / "zutai" / "Cargo.toml"),
                    "-q", "-p", "zutai-cli", "--", "check", str(contract / name),
                ],
                cwd=ROOT,
                env=environment,
                check=True,
            )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    check_contracts()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != SOURCE:
            raise SystemExit("generated boot bindings are stale; run `just boot_gen`")
        print("Boot contract bindings are current")
        return
    OUTPUT.write_text(SOURCE, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
