[package]
name = "slime-component-robot-actuator"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.96"
build = "build.rs"

[[bin]]
name = "robot-actuator"
path = "src/main.rs"
test = false

[dependencies]
slime-proto = { path = "../../proto" }
slime-rt = { path = "../../runtime" }

[build-dependencies]
slime-build-support = { path = "../../build-support" }

[lints]
workspace = true
