#![no_std]
#![no_main]
#![feature(custom_test_frameworks)]
#![test_runner(slime_os_kernel::test_runner)]
#![reexport_test_harness_main = "test_main"]

extern crate alloc;

use core::panic::PanicInfo;

#[cfg(not(test))]
use boot_contracts::handoff::KernelHandoffV1;

// Platform bring-up is per-architecture: the device set and initialization
// order differ, and there is no useful shared sequence between a PC and a
// device-tree machine. Both converge on the architecture-neutral runtime.
#[cfg(target_arch = "aarch64")]
#[path = "bringup_aarch64.rs"]
mod bringup;
#[cfg(target_arch = "x86_64")]
#[path = "bringup_x86_64.rs"]
mod bringup;

#[cfg(test)]
mod testing;

/// Kernel entry point.
///
/// # Safety
///
/// Production stage-0 supplies a verified `KernelHandoffV1`; the Cargo test
/// runner uses Limine and initializes the legacy test boot context instead.
#[cfg(not(test))]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn _start(handoff: *const KernelHandoffV1) -> ! {
    // Firmware may hand off with SIMD state disabled, so establish the
    // architectural baseline the compiler assumes before calling any ordinary
    // Rust function.
    // SAFETY: this is the first instruction sequence of kernel entry, run once.
    unsafe { slime_os_kernel::arch::cpu::init_simd_baseline() };
    unsafe extern "C" {
        static mut __bss_start: u8;
        static mut __stop_data: u8;
    }
    unsafe {
        let start = core::ptr::addr_of_mut!(__bss_start);
        let end = core::ptr::addr_of_mut!(__stop_data);
        core::ptr::write_bytes(start, 0, end.offset_from(start) as usize);
    }
    unsafe { slime_os_kernel::boot::init_from_handoff(handoff) };
    bringup::bringup();
    slime_os_kernel::hlt_loop()
}

#[cfg(test)]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn _start() -> ! {
    slime_os_kernel::limine::ensure_linked();
    unsafe { slime_os_kernel::boot::init_from_limine() };
    bringup::bringup();
    // The harness entry point generated by `reexport_test_harness_main`. It
    // lives here rather than in the bring-up module because that attribute only
    // injects it into the crate root.
    test_main();
    slime_os_kernel::hlt_loop()
}

/// This function is called on panic.
///
/// Reported over serial, which every profile has, and to the framebuffer
/// console, which silently discards the write when no framebuffer was
/// initialized — as on a headless machine.
#[cfg(not(test))]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    slime_os_kernel::serial_println!("[panic] {}", info);
    slime_os_kernel::println!("{}", info);
    slime_os_kernel::hlt_loop()
}

#[cfg(test)]
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    slime_os_kernel::test_panic_handler(info)
}
