[package]
name = "slime-component-network-service"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.96"
build = "build.rs"

[[bin]]
name = "network-service"
path = "src/main.rs"
test = false

[dependencies]
boot-contracts = { path = "../../../boot-contracts" }
slime-components = { path = "../../lib" }
slime-proto = { path = "../../proto" }
slime-rt = { path = "../../runtime" }
smoltcp = { version = "=0.13.0", default-features = false, features = [
    "medium-ethernet",
    "proto-ipv4",
    "socket-tcp",
    "auto-icmp-echo-reply",
    "iface-max-addr-count-1",
    "iface-max-route-count-1",
    "iface-neighbor-cache-count-4",
] }

[build-dependencies]
slime-build-support = { path = "../../build-support" }

[lints]
workspace = true
