// @generated by contracts/block/v1/gen_rust.zt; do not edit.
// Source contract: contracts/block/v1/schema.zt

pub const FORMAT_VERSION: u32 = 1;
pub const BLOCK_MAGIC: u32 = 1162562626;
pub const BLOCK_MAGIC_BYTES: [u8; 4] = BLOCK_MAGIC.to_le_bytes();
pub const OP_READ: u8 = 1;
pub const OP_WRITE: u8 = 2;
pub const OP_FLUSH: u8 = 3;
pub const REQUEST_LEN: usize = 64;
pub const REPLY_LEN: usize = 64;

pub const OFF_REQUEST_MAGIC: usize = 0;
pub const OFF_REQUEST_VERSION: usize = 4;
pub const OFF_REQUEST_OP: usize = 8;
pub const OFF_REQUEST_FLAGS: usize = 9;
pub const OFF_REQUEST_RESERVED: usize = 10;
pub const OFF_REQUEST_LBA: usize = 12;
pub const OFF_REQUEST_SECTOR_COUNT: usize = 20;
pub const OFF_REQUEST_BUFFER_PAGES: usize = 24;
pub const OFF_REQUEST_BUFFER_PHYS: usize = 28;

pub const OFF_REPLY_MAGIC: usize = 0;
pub const OFF_REPLY_VERSION: usize = 4;
pub const OFF_REPLY_STATUS: usize = 8;
pub const OFF_REPLY_SECTORS_DONE: usize = 12;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireBlockRequest {
    pub magic: u32,
    pub version: u32,
    pub op: u8,
    pub flags: u8,
    pub reserved: u16,
    pub lba: u64,
    pub sector_count: u32,
    pub buffer_pages: u32,
    pub buffer_phys: u64,
}

impl WireBlockRequest {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REQUEST_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4]
                    .try_into()
                    .expect("generated block layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
                    .try_into()
                    .expect("generated block layout"),
            ),
            op: buf[OFF_REQUEST_OP],
            flags: buf[OFF_REQUEST_FLAGS],
            reserved: u16::from_le_bytes(
                buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 2]
                    .try_into()
                    .expect("generated block layout"),
            ),
            lba: u64::from_le_bytes(
                buf[OFF_REQUEST_LBA..OFF_REQUEST_LBA + 8]
                    .try_into()
                    .expect("generated block layout"),
            ),
            sector_count: u32::from_le_bytes(
                buf[OFF_REQUEST_SECTOR_COUNT..OFF_REQUEST_SECTOR_COUNT + 4]
                    .try_into()
                    .expect("generated block layout"),
            ),
            buffer_pages: u32::from_le_bytes(
                buf[OFF_REQUEST_BUFFER_PAGES..OFF_REQUEST_BUFFER_PAGES + 4]
                    .try_into()
                    .expect("generated block layout"),
            ),
            buffer_phys: u64::from_le_bytes(
                buf[OFF_REQUEST_BUFFER_PHYS..OFF_REQUEST_BUFFER_PHYS + 8]
                    .try_into()
                    .expect("generated block layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REQUEST_LEN] {
        let mut buf = [0u8; REQUEST_LEN];
        buf[OFF_REQUEST_MAGIC..OFF_REQUEST_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REQUEST_VERSION..OFF_REQUEST_VERSION + 4]
            .copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REQUEST_OP] = self.op;
        buf[OFF_REQUEST_FLAGS] = self.flags;
        buf[OFF_REQUEST_RESERVED..OFF_REQUEST_RESERVED + 2]
            .copy_from_slice(&self.reserved.to_le_bytes());
        buf[OFF_REQUEST_LBA..OFF_REQUEST_LBA + 8].copy_from_slice(&self.lba.to_le_bytes());
        buf[OFF_REQUEST_SECTOR_COUNT..OFF_REQUEST_SECTOR_COUNT + 4]
            .copy_from_slice(&self.sector_count.to_le_bytes());
        buf[OFF_REQUEST_BUFFER_PAGES..OFF_REQUEST_BUFFER_PAGES + 4]
            .copy_from_slice(&self.buffer_pages.to_le_bytes());
        buf[OFF_REQUEST_BUFFER_PHYS..OFF_REQUEST_BUFFER_PHYS + 8]
            .copy_from_slice(&self.buffer_phys.to_le_bytes());
        buf
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireBlockReply {
    pub magic: u32,
    pub version: u32,
    pub status: i32,
    pub sectors_done: u32,
}

impl WireBlockReply {
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < REPLY_LEN {
            return None;
        }
        Some(Self {
            magic: u32::from_le_bytes(
                buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4]
                    .try_into()
                    .expect("generated block layout"),
            ),
            version: u32::from_le_bytes(
                buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4]
                    .try_into()
                    .expect("generated block layout"),
            ),
            status: i32::from_le_bytes(
                buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4]
                    .try_into()
                    .expect("generated block layout"),
            ),
            sectors_done: u32::from_le_bytes(
                buf[OFF_REPLY_SECTORS_DONE..OFF_REPLY_SECTORS_DONE + 4]
                    .try_into()
                    .expect("generated block layout"),
            ),
        })
    }

    pub fn encode(self) -> [u8; REPLY_LEN] {
        let mut buf = [0u8; REPLY_LEN];
        buf[OFF_REPLY_MAGIC..OFF_REPLY_MAGIC + 4].copy_from_slice(&self.magic.to_le_bytes());
        buf[OFF_REPLY_VERSION..OFF_REPLY_VERSION + 4].copy_from_slice(&self.version.to_le_bytes());
        buf[OFF_REPLY_STATUS..OFF_REPLY_STATUS + 4].copy_from_slice(&self.status.to_le_bytes());
        buf[OFF_REPLY_SECTORS_DONE..OFF_REPLY_SECTORS_DONE + 4]
            .copy_from_slice(&self.sectors_done.to_le_bytes());
        buf
    }
}
